### ISSUE TITLE
[BUG] T5 extended attention mask shape mismatch with transformer engine

### ISSUE THREAD

**Issue by andrewvli** [NVIDIA/Megatron-LM#1005]
**Describe the bug**
Running the most recent version of the T5 pretraining script out of the box raises a Value Error, particularly in the following line:
```
[rank0]:   File "/home/miniconda3/lib/python3.12/site-packages/transformer_engine/pytorch/attention.py", line 243, in get_cu_seqlens_and_indices
[rank0]:     bs, seqlen = mask.shape
[rank0]:     ^^^^^^^^^^
[rank0]: ValueError: too many values to unpack (expected 2)
```
When taking a look at the T5 model, the `t5_extended_attention_mask()` function in `/megatron/core/models/T5/t5_model.py` returns a List of Tensors with shape `[b, 1, s, s]`, as shown below.
```
def t5_extended_attention_mask(attention_mask_list: List[Tensor]) -> List[Tensor]:
    def attn_mask_postprocess(attn_mask):
        # [b, 1, s, s]
        extended_attention_mask = attn_mask.unsqueeze(1)
        return extended_attention_mask

    return [attn_mask_postprocess(attn_mask) for attn_mask in attention_mask_list]
```
However, when looking at the Transformer Engine repository where the error originates, it appears that the shape of the attention mask expected should be `[b, 1, 1, s]`. The comment in `NVIDIA/TransformerEngine/transformer_engine/pytorch/attention.py` where that's indicated (line 5517) is listed as follows:

```
        attention_mask: Optional[Union[torch.Tensor, Tuple[torch.Tensor, torch.Tensor]]],
             default = `None`. Boolean tensor(s) used to mask out attention softmax input.
             It should be `None` for causal masks and "`no_mask`". For padding masks, it should be
             a single tensor of [batch_size, 1, 1, seqlen_q] for self-attention, and a tuple of
             two tensors in shapes [batch_size, 1, 1, seqlen_q] and [batch_size, 1, 1, seqlen_kv]
             for cross-attention. For "`arbitrary`" mask, it should be in a shape broadcastable
             to [batch_size, num_heads, max_seqlen_q, max_seqlen_kv]. A `True` value means
             the corresponding position is masked out and a `False` means that position
             is allowed to participate in attention.
```

Given that the attention masks produced for T5 have different dimensions (e.g. when printing out the dimensionality of the masks, I saw three tensors with dimensions `[batch_size, encoder_seqlen, encoder_seqlen], [batch_size, decoder_seqlen, decoder_seqlen], [batch_size, encoder_seqlen, decoder_seqlen]`), I was wondering if there was a fix for this issue. 

**To Reproduce**
Running the pretraining script in a base conda environment with the environment described below. 

**Expected behavior**
I'd expect the pretraining script to reach the training iterations without throwing an error.

**Stack trace/logs**
```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/Megatron-LM/pretrain_t5.py", line 257, in <module>
[rank0]:     pretrain(
[rank0]:   File "/home/Megatron-LM/megatron/training/training.py", line 278, in pretrain
[rank0]:     iteration, num_floating_point_operations_so_far = train(
[rank0]:                                                       ^^^^^^
[rank0]:   File "/home/Megatron-LM/megatron/training/training.py", line 1057, in train
[rank0]:     train_step(forward_step_func,
[rank0]:   File "/home/Megatron-LM/megatron/training/training.py", line 558, in train_step
[rank0]:     losses_reduced = forward_backward_func(
[rank0]:                      ^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/Megatron-LM/megatron/core/pipeline_parallel/schedules.py", line 399, in forward_backward_no_pipelining
[rank0]:     output_tensor, num_tokens = forward_step(
[rank0]:                                 ^^^^^^^^^^^^^
[rank0]:   File "/home/Megatron-LM/megatron/core/pipeline_parallel/schedules.py", line 206, in forward_step
[rank0]:     output_tensor, loss_func = forward_step_func(data_iterator, model)
[rank0]:                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/Megatron-LM/pretrain_t5.py", line 199, in forward_step
[rank0]:     output_tensor = model(
[rank0]:                     ^^^^^^
[rank0]:   File "/home/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/Megatron-LM/megatron/core/distributed/distributed_data_parallel.py", line 202, in forward
[rank0]:     return self.module(*inputs, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/Megatron-LM/megatron/legacy/model/module.py", line 190, in forward
[rank0]:     outputs = self.module(*inputs, **kwargs)
[rank0]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/Megatron-LM/megatron/core/models/T5/t5_model.py", line 273, in forward
[rank0]:     decoder_hidden_states = self.decoder(
[rank0]:                             ^^^^^^^^^^^^^
[rank0]:   File "/home/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/Megatron-LM/megatron/core/transformer/transformer_block.py", line 383, in forward
[rank0]:     hidden_states, context = layer(
[rank0]:                              ^^^^^^
[rank0]:   File "/home/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/Megatron-LM/megatron/core/transformer/transformer_layer.py", line 200, in forward
[rank0]:     attention_output_with_bias = self.cross_attention(
[rank0]:                                  ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/Megatron-LM/megatron/core/transformer/attention.py", line 315, in forward
[rank0]:     core_attn_out = self.core_attention(
[rank0]:                     ^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/Megatron-LM/megatron/core/transformer/custom_layers/transformer_engine.py", line 534, in forward
[rank0]:     core_attn_out = super().forward(
[rank0]:                     ^^^^^^^^^^^^^^^^
[rank0]:   File "/home/miniconda3/lib/python3.12/site-packages/transformer_engine/pytorch/attention.py", line 3862, in forward
[rank0]:     return self.flash_attention(query_layer,
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/miniconda3/lib/python3.12/site-packages/transformer_engine/pytorch/attention.py", line 2106, in forward
[rank0]:     cu_seqlens_q, indices_q = get_cu_seqlens_and_indices(
[rank0]:                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/miniconda3/lib/python3.12/site-packages/transformer_engine/pytorch/attention.py", line 243, in get_cu_seqlens_and_indices
[rank0]:     bs, seqlen = mask.shape
[rank0]:     ^^^^^^^^^^
[rank0]: ValueError: too many values to unpack (expected 2)
```

**Environment (please complete the following information):**
 - Megatron-LM commit ID: 44cc262
 - PyTorch version: 2.4.0a0+git4f14282
 - CUDA version: 12.2
 - NCCL version: 2.21.5

**Comment by shanmugamr1992** [comment]
Hi @andrewvli , this is about the transformer engine version you are using and the type of attention you are using. There are a couple of ways to fix this : 
You could set NVTE_FLASH_ATTN=0 and NVTE_FUSED_ATTN=0 , that way it goes through the unfused path, and so it accepts [b ,1,s ,s ] mask. 
The other way to do it will be to just change the mask to be [b,1,1,s] if possible, if its just a padding mask . 
@huvunvidia  Can you look if we can send [b,1,1,s] as the attention mask ? You might have to do something like what bert is doing.

**Comment by shanmugamr1992** [comment]
@andrewvli  Can you share transformer engine verison 
pip list | grep transformer

**Comment by shanmugamr1992** [comment]
@andrewvli  You just have to switch the encoder mask alone to [b,1,1,s] for any transformer engine version greater than 1.5 I think (Maybe 1.7)

**Comment by andrewvli** [comment]
@shanmugamr1992 Transformer engine has version 1.7.0+4e7caa1. Setting NVTE_FLASH_ATTN=0 and NVTE_FUSED_ATTN=0 resolves the original issue. Thanks!

**Comment by shanmugamr1992** [comment]
@andrewvli  One more thing that you can try send attn_mask_type as 'arbitrary'. Anyway @huvunvidia  is looking into this now and he will raise a fix soon
