### ISSUE TITLE
Failed to load NGC's GPT-2 checkpoint file from tools/generate_samples_gpt.py

### ISSUE THREAD

**Issue by lazykyama** [NVIDIA/Megatron-LM#101]
When I tried to run `tools/generate_samples_gpt.py` with NGC's pretrained model (https://ngc.nvidia.com/catalog/models/nvidia:megatron_lm_345m), the following error happened.

```
Traceback (most recent call last):
  File "tools/generate_samples_gpt.py", line 112, in <module>
    main()
  File "tools/generate_samples_gpt.py", line 94, in main
    _ = load_checkpoint(model, None, None)
  File "/path/to/Megatron-LM/megatron/checkpointing.py", line 341, in load_checkpoint
    fix_query_key_value_ordering(model, checkpoint_version)
  File "/path/to/Megatron-LM/megatron/checkpointing.py", line 214, in fix_query_key_value_ordering
    for name, param in model.named_parameters():
AttributeError: 'list' object has no attribute 'named_parameters'
```

As far as I checked, this issue looks like caused due to a step to verify checkpoint version and fix the model architecture. After modifying like below, the error disappeared.

```diff
diff --git a/megatron/checkpointing.py b/megatron/checkpointing.py
index 43dfa16..5f7f05f 100644
--- a/megatron/checkpointing.py
+++ b/megatron/checkpointing.py
@@ -211,6 +211,9 @@ def fix_query_key_value_ordering(model, checkpoint_version):
     version is smaller than 2.0
     """
     if checkpoint_version < 2.0:
+        if isinstance(model, list):
+            assert len(model)==1
+            model = model[0]
         for name, param in model.named_parameters():
             if name.endswith(('.query_key_value.weight', '.query_key_value.bias')):
                 if checkpoint_version == 0:
```

Is such behavior expected and is the change above ok?

Environment information is below:

* GPU driver: 450.102.04 
* Runtime: NGC container image nvcr.io/nvidia/pytorch:20.12-py3
* Runtime options: like below

```
    --tensor-model-parallel-size 1 \
    --pipeline-model-parallel-size 1 \
    --num-layers 24 \
    --hidden-size 1024 \
    --num-attention-heads 16 \
    --seq-length 1024 \
    --max-position-embeddings 1024 \
    --micro-batch-size 4 \
    --global-batch-size 8 \
    --lr 0.00015 \
    --train-iters 500000 \
    --lr-decay-iters 320000 \
    --lr-decay-style cosine \
    --vocab-file ../resources/gpt2-vocab.json \
    --merge-file ../resources/gpt2-merges.txt \
    --lr-warmup-fraction .01 \
    --fp16 \
    --load ${MODELPATH} \
    --out-seq-length 1024 \
    --temperature 1.0 \
    --genfile samples_from_file.json \
    --sample-input-file ../data/seed.txt \
    --sample-output-file ${OUTFILE_PATH} \
    --num-samples 0 \
    --top_p 0.9 \
    --no-load-optim --no-load-rng \
    --recompute
```

**Comment by lazykyama** [comment]
It looks like this issue has been already resolved by 26b49aab4fd18f8ae1defd22eb8f813a7b35704f.
