### ISSUE TITLE
TypeError: get_cpu_offload_context() takes from 0 to 4 positional arguments but 5 were given

### ISSUE THREAD

**Issue by ben-8543** [NVIDIA/Megatron-LM#1018]
te_version: 1.9.0+e79d915
```
Traceback (most recent call last):
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/swift/cli/export.py", line 5, in <module>
    export_main()
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/swift/utils/run_utils.py", line 32, in x_main
    result = llm_x(args, **kwargs)
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/swift/llm/export.py", line 302, in llm_export
    convert_hf_to_megatron(model, extra_args, args.torch_dtype)
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/swift/llm/megatron/convert.py", line 22, in convert_hf_to_megatron
    mg_model = model_provider()
  File "/home/ybZhang/miniconda3/envs/glm-m/lib/python3.8/site-packages/swift/llm/megatron/model.py", line 61, in model_provider
    model = gpt_model_cls(
  File "./Pai-Megatron-Patch/megatron_patch/model/qwen2/model.py", line 103, in __init__
    self.decoder = TransformerBlock(
  File "./Pai-Megatron-Patch/megatron_patch/model/qwen2/transformer_block.py", line 137, in __init__
    ) = get_cpu_offload_context(
  File "./Megatron-LM/megatron/core/transformer/custom_layers/transformer_engine.py", line 899, in get_cpu_offload_context
    context, sync_func = _get_cpu_offload_context(
TypeError: get_cpu_offload_context() takes from 0 to 4 positional arguments but 5 were given

```

**Comment by 1195343015** [comment]
PR #996
