### ISSUE TITLE
[BUG] Long context training using context-parallel hangs/crashes

### ISSUE THREAD

**Issue by abgoswam** [NVIDIA/Megatron-LM#1025]
**Describe the bug**

-  `--context-parallel-size` > 1  
- `--max-position-embeddings` >= 131072  (i.e. 128k tokens)

This causes megatron-lm to crash in the `get_batch` call. 

**Observations:**
1. The same config  works  for `--max-position-embeddings` <= 65536 (i.e. 64k tokens)

**To Reproduce**

Here is a sample script:
1. Uses 4 A100 GPUs
2. `--context-parallel-size` set to 4
3. `--data_path`  points to a processed data file with 131072 tokens

```
#!/bin/bash

export CUDA_DEVICE_MAX_CONNECTIONS=1

DISTRIBUTED_ARGS=(
    --nproc_per_node 4 
    --nnodes 1 
    --master_addr localhost 
    --master_port 6000
)

GPT_MODEL_ARGS=(
    --transformer-impl transformer_engine
    --normalization RMSNorm
    --num-layers 24 
    --hidden-size 128 
    --num-attention-heads 16 
    --seq-length 131072 
    --max-position-embeddings 131072 
    --position-embedding-type rope
    --rotary-percent 1.0
    --rotary-base 1000000
    --swiglu
)

TRAINING_ARGS=(
    --micro-batch-size 1
    --train-iters 128 
    --weight-decay 0.1 
    --adam-beta1 0.9 
    --adam-beta2 0.95 
    --init-method-std 0.006 
    --clip-grad 1.0 
    --bf16
    --lr 0.00015 
    --lr-decay-style cosine 
    --min-lr 6.0e-6
    --lr-warmup-fraction .001 
    --lr-decay-iters 128
    --use-flash-attn
    --attention-dropout 0.1
    --use-distributed-optimizer
)

MODEL_PARALLEL_ARGS=(
    --context-parallel-size 4
    --tensor-model-parallel-size 1
    --pipeline-model-parallel-size 1
)

DATA_ARGS=(
    --data-path "./my_long_corpus_131072_gpt2_text_document"
    --vocab-file "./gpt2-vocab.json" 
    --merge-file "./gpt2-merges.txt" 
    --split 949,50,1
)

EVAL_AND_LOGGING_ARGS=(
    --log-interval 100
    --save-interval 10000 
    --eval-interval 1000 
    --eval-iters 0
)
torchrun ${DISTRIBUTED_ARGS[@]} pretrain_gpt.py \
    ${GPT_MODEL_ARGS[@]} \
    ${TRAINING_ARGS[@]} \
    ${MODEL_PARALLEL_ARGS[@]} \
    ${DATA_ARGS[@]} \
    ${EVAL_AND_LOGGING_ARGS[@]}
```

**Expected behavior**

Since the same config works for 64k tokens, we expect it to work for  128k tokens.   The whole promise of context-parallel is for long sequence training.

**Stack trace/logs**

```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/tmp/amlt-code-download/Megatron-LM/pretrain_gpt.py", line 245, in <module>
[rank0]:     pretrain(
[rank0]:   File "/tmp/amlt-code-download/Megatron-LM/megatron/training/training.py", line 312, in pretrain
[rank0]:     iteration, num_floating_point_operations_so_far = train(
[rank0]:   File "/tmp/amlt-code-download/Megatron-LM/megatron/training/training.py", line 1115, in train
[rank0]:     train_step(forward_step_func,
[rank0]:   File "/tmp/amlt-code-download/Megatron-LM/megatron/training/training.py", line 611, in train_step
[rank0]:     losses_reduced = forward_backward_func(
[rank0]:   File "/tmp/amlt-code-download/Megatron-LM/megatron/core/pipeline_parallel/schedules.py", line 460, in forward_backward_no_pipelining
[rank0]:     output_tensor, num_tokens = forward_step(
[rank0]:   File "/tmp/amlt-code-download/Megatron-LM/megatron/core/pipeline_parallel/schedules.py", line 266, in forward_step
[rank0]:     output_tensor, loss_func = forward_step_func(data_iterator, model)
[rank0]:   File "/tmp/amlt-code-download/Megatron-LM/pretrain_gpt.py", line 169, in forward_step
[rank0]:     tokens, labels, loss_mask, attention_mask, position_ids = get_batch(
[rank0]:   File "/tmp/amlt-code-download/Megatron-LM/pretrain_gpt.py", line 104, in get_batch
[rank0]:     batch = get_batch_on_this_tp_rank(data_iterator)
[rank0]:   File "/tmp/amlt-code-download/Megatron-LM/megatron/training/utils.py", line 313, in get_batch_on_this_tp_rank
[rank0]:     data = next(data_iterator)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 629, in __next__
[rank0]:     data = self._next_data()
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1326, in _next_data
[rank0]:     idx, data = self._get_data()
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1282, in _get_data
[rank0]:     success, data = self._try_get_data()
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1130, in _try_get_data
[rank0]:     data = self._data_queue.get(timeout=timeout)
[rank0]:   File "/usr/lib/python3.10/queue.py", line 180, in get
[rank0]:     self.not_empty.wait(remaining)
[rank0]:   File "/usr/lib/python3.10/threading.py", line 324, in wait
[rank0]:     gotit = waiter.acquire(True, timeout)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
[rank0]:     _error_if_any_worker_fails()
```

**Environment (please complete the following information):**
 - Megatron-LM commit ID: c873429cbaa43257d4d4fc01df2a7a50453b7984
 - base image: nvcr.io/nvidia/pytorch:24.06-py3

**Proposed fix**
- NA

**Additional context**
- NA

**Comment by ethanhe42** [comment]
can you try `--no-create-attention-mask-in-dataloader`?

**Comment by abgoswam** [comment]
Thanks @ethanhe42 for the tip.  The `--no-create-attention-mask-in-dataloader`  indeed helps out here. 

Closing the issue.
