### ISSUE TITLE
The program got stuck in ”compiling and loading fused kernels ...“ and timed out after ten minutes

### ISSUE THREAD

**Issue by qq1243196045** [NVIDIA/Megatron-LM#1050]
when I try to train gpt3, program got stuck in "”compiling and loading fused kernels ",I Don't know what happend
```
> initialized tensor model parallel with size 2
> initialized pipeline model parallel with size 4
> setting random seeds to 1234 ...
> compiling dataset index builder ...
make: Entering directory '/home/m01119/projects/Megatron-LM/megatron/core/datasets'
make: Nothing to be done for 'default'.
make: Leaving directory '/home/m01119/projects/Megatron-LM/megatron/core/datasets'
>>> done with dataset index builder. Compilation time: 0.016 seconds
> compiling and loading fused kernels ...

```

and timed out after ten minutes:
```
> compiling and loading fused kernels ...
compiling and loading fused kernels[rank1]:[E829 16:32:30.656674606 ProcessGroupNCCL.cpp:607] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=600000) ran for 600062 milliseconds before timing out.
[rank1]:[E829 16:32:30.657006650 ProcessGroupNCCL.cpp:1664] [PG 0 (default_pg) Rank 1] Exception (either an error or timeout) detected by watchdog at work: 1, last enqueued NCCL work: 1, last completed NCCL work: -1.
[rank0]:[E829 16:32:31.155765764 ProcessGroupNCCL.cpp:607] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=600000) ran for 600079 milliseconds before timing out.
[rank0]:[E829 16:32:31.156044057 ProcessGroupNCCL.cpp:1664] [PG 0 (default_pg) Rank 0] Exception (either an error or timeout) detected by watchdog at work: 1, last enqueued NCCL work: 1, last completed NCCL work: -1.
swdevops-netr-b01:81609:83955 [0] NCCL INFO [Service thread] Connection closed by localRank 0
swdevops-netr-b01:81609:83309 [0] NCCL INFO comm 0xa8e9da0 rank 0 nranks 8 cudaDev 0 busId 4f000 - Abort COMPLETE
[rank0]:[E829 16:32:32.273721273 ProcessGroupNCCL.cpp:1709] [PG 0 (default_pg) Rank 0] Timeout at NCCL work: 1, last enqueued NCCL work: 1, last completed NCCL work: -1.
[rank0]:[E829 16:32:32.273735274 ProcessGroupNCCL.cpp:621] [Rank 0] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank0]:[E829 16:32:32.273743857 ProcessGroupNCCL.cpp:627] [Rank 0] To avoid data inconsistency, we are taking the entire process down.
[rank0]:[E829 16:32:32.274971279 ProcessGroupNCCL.cpp:1515] [PG 0 (default_pg) Rank 0] Process group watchdog thread terminated with exception: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=600000) ran for 600079 milliseconds before timing out.
Exception raised from checkTimeout at /opt/conda/conda-bld/pytorch_1720538439675/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:609 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7fafdfae1f86 in /home/m01119/miniconda3/envs/megatron/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x1d2 (0x7fafe0dc50b2 in /home/m01119/miniconda3/envs/megatron/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::watchdogHandler() + 0x233 (0x7fafe0dcbaf3 in /home/m01119/miniconda3/envs/megatron/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x10c (0x7fafe0dcdedc in /home/m01119/miniconda3/envs/megatron/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xdbbf4 (0x7fb0308d3bf4 in /home/m01119/miniconda3/envs/megatron/lib/python3.12/site-packages/torch/lib/../../../.././libstdc++.so.6)
frame #5: <unknown function> + 0x76db (0x7fb03a0f86db in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #6: clone + 0x3f (0x7fb03967c61f in /lib/x86_64-linux-gnu/libc.so.6)

W0829 16:32:33.985000 140611253834240 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 81610 closing signal SIGTERM
W0829 16:32:33.989000 140611253834240 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 81611 closing signal SIGTERM
W0829 16:32:33.993000 140611253834240 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 81612 closing signal SIGTERM
W0829 16:32:33.996000 140611253834240 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 81613 closing signal SIGTERM
W0829 16:32:33.998000 140611253834240 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 81615 closing signal SIGTERM
W0829 16:32:34.015000 140611253834240 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 81616 closing signal SIGTERM
W0829 16:32:34.022000 140611253834240 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 81617 closing signal SIGTERM
E0829 16:32:39.298000 140611253834240 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: -6) local_rank: 0 (pid: 81609) of binary: /home/m01119/miniconda3/envs/megatron/bin/python
Traceback (most recent call last):
  File "/home/m01119/miniconda3/envs/megatron/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.4.0', 'console_scripts', 'torchrun')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m01119/miniconda3/envs/megatron/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/m01119/miniconda3/envs/megatron/lib/python3.12/site-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/home/m01119/miniconda3/envs/megatron/lib/python3.12/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/home/m01119/miniconda3/envs/megatron/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m01119/miniconda3/envs/megatron/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
======================================================
pretrain_gpt.py FAILED
------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-08-29_16:32:33
  host      : swdevops-netr-b01
  rank      : 0 (local_rank: 0)
  exitcode  : -6 (pid: 81609)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 81609
======================================================
```
what should I do?

**Comment by KookHoiKim** [comment]
https://github.com/NVIDIA/Megatron-LM/issues/998

Hope this help you.

**Comment by qq1243196045** [comment]
> [#998](https://github.com/NVIDIA/Megatron-LM/issues/998)
> 
> Hope this help you.

IT WORKS! thank you :)

**Comment by zuoyanzhang** [comment]
you can delete the megatron/fused_kernels/build, and rerun, it will rebuild the library and will be ok.
