### ISSUE TITLE
[QUESTION] which ngc version is ok？

### ISSUE THREAD

**Issue by ltm920716** [NVIDIA/Megatron-LM#1122]
**Your question**
Ask a clear and concise question about Megatron-LM.
I tried two ngc pytorch image as base env，neither is ok.

test script:
```
PYTHONPATH=$PYTHONPATH:./megatron torchrun --nproc-per-node 2 examples/run_simple_mcore_train_loop.py
```
for  nvcr.io/nvidia/pytorch:23.10-py3
```
Traceback (most recent call last):
  File "/home/Megatron-LM/examples/run_simple_mcore_train_loop.py", line 13, in <module>
    from megatron.core.models.gpt.gpt_model import GPTModel
  File "/home/Megatron-LM/megatron/core/models/gpt/__init__.py", line 2, in <module>
    from .gpt_model import GPTModel
  File "/home/Megatron-LM/megatron/core/models/gpt/gpt_model.py", line 17, in <module>
    from megatron.core.transformer.transformer_block import TransformerBlock
  File "/home/Megatron-LM/megatron/core/transformer/transformer_block.py", line 23, in <module>
    from megatron.core.extensions.transformer_engine import (
  File "/home/Megatron-LM/megatron/core/extensions/transformer_engine.py", line 853, in <module>
Traceback (most recent call last):
  File "/home/Megatron-LM/examples/run_simple_mcore_train_loop.py", line 13, in <module>
    from megatron.core.models.gpt.gpt_model import GPTModel
  File "/home/Megatron-LM/megatron/core/models/gpt/__init__.py", line 2, in <module>
    class TECudaRNGStatesTracker(te.pytorch.distributed.CudaRNGStatesTracker):
AttributeError: module 'transformer_engine.pytorch.distributed' has no attribute 'CudaRNGStatesTracker'    from .gpt_model import GPTModel

  File "/home/Megatron-LM/megatron/core/models/gpt/gpt_model.py", line 17, in <module>
    from megatron.core.transformer.transformer_block import TransformerBlock
  File "/home/Megatron-LM/megatron/core/transformer/transformer_block.py", line 23, in <module>
    from megatron.core.extensions.transformer_engine import (
  File "/home/Megatron-LM/megatron/core/extensions/transformer_engine.py", line 853, in <module>
    class TECudaRNGStatesTracker(te.pytorch.distributed.CudaRNGStatesTracker):
AttributeError: module 'transformer_engine.pytorch.distributed' has no attribute 'CudaRNGStatesTracker'
[2024-09-06 14:12:46,521] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 498) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
```

for nvcr.io/nvidia/pytorch:23.05-py3
```
Traceback (most recent call last):
  File "/home/Megatron-LM/examples/run_simple_mcore_train_loop.py", line 8, in <module>
    from megatron.core import parallel_state
  File "/home/Megatron-LM/megatron/core/__init__.py", line 5, in <module>
    from megatron.core.distributed import DistributedDataParallel
  File "/home/Megatron-LM/megatron/core/distributed/__init__.py", line 3, in <module>
    from .distributed_data_parallel import DistributedDataParallel
  File "/home/Megatron-LM/megatron/core/distributed/distributed_data_parallel.py", line 15, in <module>
    from .param_and_grad_buffer import BucketGroup, ParamAndGradBuffer, partition_buckets
  File "/home/Megatron-LM/megatron/core/distributed/param_and_grad_buffer.py", line 10, in <module>
    from torch.distributed import _coalescing_manager
ImportError: cannot import name '_coalescing_manager' from 'torch.distributed' (/usr/local/lib/python3.10/dist-packages/torch/distributed/__init__.py)
Traceback (most recent call last):
  File "/home/Megatron-LM/examples/run_simple_mcore_train_loop.py", line 8, in <module>
    from megatron.core import parallel_state
  File "/home/Megatron-LM/megatron/core/__init__.py", line 5, in <module>
```

so sad

I  install pytorch locally and do not install transformer_engine, and I  have to change some source code to run

**Comment by 1195343015** [comment]
[24.02](https://docs.nvidia.com/megatron-core/developer-guide/latest/user-guide/index.html)

**Comment by ltm920716** [comment]
> [24.02](https://docs.nvidia.com/megatron-core/developer-guide/latest/user-guide/index.html)

thanks,  it is ok!

I recompile TransformerEngine from source is ok too by pytorch:23.10-py3

**Comment by Rmie9** [comment]
If i want to use conda to install pytorch, Which version of ngc24.02 corresponds to in conda？
thank！

**Comment by Rmie9** [comment]
thx，i have found it in https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel-24-02.html.
PyTorch quantization wheel 2.1.2
