### ISSUE TITLE
[QUESTION] Adding new parameters in ColumnParallelLinear/RowParallelLinear raises AssertionError (Communication call has not been issued for this bucket) when using overlap-grad-reduce

### ISSUE THREAD

**Issue by haolibai** [NVIDIA/Megatron-LM#1150]
Hi, I am trying to add some new learnable parameters inside ColumnParallelLinear/RowParallelLinear, and the following is an example code snippet:

```python
class ColumnParallelLinear(torch.nn.Module):
    """Linear layer with column parallelism.

    The linear layer is defined as Y = XA + b. A is parallelized along
    its second dimension as A = [A_1, ..., A_p].

    Args:
        input_size: first dimension of matrix A.
        output_size: second dimension of matrix A.
        bias: If true, add bias
        gather_output: If true, call all-gather on output and make Y available to all GPUs, otherwise, every GPU will have its output which is Y_i = XA_i
        init_method: method to initialize weights. Note that bias is always set to zero.
        stride: For the strided linear layers.
        keep_master_weight_for_test: This was added for testing and should be set to False. It returns the master weights used for initialization.
        skip_bias_add: If True, do not add the bias term, instead return it to be added by the caller. This enables performance optimations where bias can be fused with other elementwise operations.
        skip_weight_param_allocation: If True, weight parameter is not allocated and must be passed as a keyword argument `weight` during the forward pass. Note that this does not affect bias, which will be allocated if bias is True. Defaults to False.
        embedding_activation_buffer: This buffer holds the input activations of the final embedding linear layer on the last pipeline stage when defer_embedding_wgrad_compute is enabled.
        grad_output_buffer: This buffer holds the gradient outputs of the final embedding linear layer on the last pipeline stage when defer_embedding_wgrad_compute is enabled.
        is_expert: If True, the layer is treated as an MoE expert layer.
        config: ModelParallelConfig object
        tp_comm_buffer_name: Communication buffer name is not used in non-Transformer-Engine modules.
    """

    def __init__(
        self,
        input_size,
        output_size,
        *,
        config: ModelParallelConfig,
        init_method: Callable,
        bias=True,
        gather_output=False,
        stride=1,
        keep_master_weight_for_test=False,
        skip_bias_add=False,
        skip_weight_param_allocation: bool = False,
        embedding_activation_buffer: Optional[List[torch.Tensor]] = None,
        grad_output_buffer: Optional[List[torch.Tensor]] = None,
        is_expert: bool = False,
        tp_comm_buffer_name: str = None,  # Not used
    ):
        super(ColumnParallelLinear, self).__init__()
        ...
        # NOTE: a new parameter defined here (for example)
        self.new_param = Parameter(torch.randn(config.hidden_size, dtype=config.params_dtype, device=torch.cuda.current_device()))
    ))

    def forward(self, input_: torch.Tensor, weight: Optional[torch.Tensor] = None):
        ...
        output = output * self.new_param
        return output
```

However, this gives me the following error during training. 

```log
Traceback (most recent call last):
  File "/home/ma-user/work/haoli/code/PanGu/pretrain_gpt.py", line 343, in main
    pretrain(train_valid_test_datasets_provider,
  File "/home/ma-user/work/haoli/code/PanGu/pangu/training/training.py", line 271, in pretrain
    iteration, num_floating_point_operations_so_far = train(
  File "/home/ma-user/work/haoli/code/PanGu/pangu/training/training.py", line 441, in train
    train_step(forward_step_func,
  File "/home/ma-user/work/haoli/code/third_party/Megatron-LM/megatron/training/training.py", line 553, in train_step
    losses_reduced = forward_backward_func(
  File "/home/ma-user/work/haoli/code/third_party/Megatron-LM/megatron/core/pipeline_parallel/schedules.py", line 395, in forward_backward_no_pipelining
    config.finalize_model_grads_func([model])
  File "/home/ma-user/work/haoli/code/third_party/Megatron-LM/megatron/core/distributed/finalize_model_grads.py", line 135, in finalize_model_grads
    model_chunk.finish_grad_sync()
  File "/home/ma-user/work/haoli/code/third_party/Megatron-LM/megatron/core/distributed/distributed_data_parallel.py", line 242, in finish_grad_sync
    buffer.finish_grad_sync()
  File "/home/ma-user/work/haoli/code/third_party/Megatron-LM/megatron/core/distributed/param_and_grad_buffer.py", line 512, in finish_grad_sync
    bucket.finish_grad_sync()
Traceback (most recent call last):
  File "/home/ma-user/work/haoli/code/pangu_sophon_pytorch/third_party/Megatron-LM/megatron/core/distributed/param_and_grad_buffer.py", line 157, in finish_grad_sync
    assert self.communication_handle is not None and self.communication_issued, (
AssertionError: Communication call has not been issued for this bucket (1/2 params have grad available)
```

This happens when the following arguments are passed for training:
```log
--overlap-param-gather
--overlap-grad-reduce
```
It seems the newly added parameter is not counted into `self.params_with_grad`.

However, the training goes normal when I do the same procedure in other places, e.g., the __init__ fucntion of ParallelAttention, or ParallelMLP, with no such errors.

**Comment by liu09114** [comment]
Did you solve this problem? I meet the same problem.

**Comment by haolibai** [comment]
Not yet. But I found more colleagues around me also meet this problem.

**Comment by KookHoiKim** [comment]
same issue when using  
 --overlap-param-gather \
 --overlap-grad-reduce \

**Comment by jpilaul** [comment]
Also getting this error with
```
--overlap-param-gather
--overlap-grad-reduce
```

**Comment by tfigliolia** [comment]
I am having exactly the same issue. Using the distributed optimizer with EP, and enabling 
--overlap-param-gather
--overlap-grad-reduce
I get the same bucket problem

**Comment by SeunghyunSEO** [comment]
whatup guys, maybe [my issue](https://github.com/NVIDIA/Megatron-LM/issues/1292) is related and if I'm right, you can fix this by locating custom layers in forward order

**Comment by liuyijiang1994** [comment]
+1+1+1+1

**Comment by haolibai** [comment]
> same issue when using --overlap-param-gather --overlap-grad-reduce \

Some quick update. I can avoid this issue and start training by removing these configs. Hope this can help more people. 

But it seems it is still not clear to me what's the mechanism that causes this issue.

**Comment by new-TonyWang** [comment]
Bugs still appear. No idea how to do with it.

**Comment by RadhaGulhane13** [comment]
This issue occurs when new parameters that require gradients are defined in the model, but not used during the forward pass.

The backward hooks and the parameters placed into buckets are registered based on the parameters defined in the model (e.g., register backward hook : [register backward hook](https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/core/distributed/distributed_data_parallel.py#L344)  and bucketing for params [partition_buckets](https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/core/distributed/distributed_data_parallel.py#L224)). However, if the actual computational graph constructed during the forward pass does not use a given parameter, the backward hook for that parameter will not be called even if the hook was registered according to PyTorch’s implementation.

As a result, the condition if len(self.params_with_grad) == len(self.params) inside [register_grad_ready()](https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/core/distributed/param_and_grad_buffer.py#L563) will never be satisfied.


In my case, I had a conditional implementation (see example below). I needed to ensure that `self.param2` was used during the forward pass, regardless of the condition.
```
class TinyModel(nn.Module):
    def __init__(self):
        super().__init__()
        # Define learnable parameters
        self.param1 = nn.Parameter(torch.randn(...))  # shape as needed
        self.param2 = nn.Parameter(torch.randn(...))  # shape as needed

    def forward(self, x):
        x = self.param1 * func(x)

        # Optional conditional branch
        if condition:
            x = self.param2 * func(x)
        return x
```

On final note, I believe the implementation for overlap-grad-reduce is correct but we explicitly need to make sure params requiring grads defined in model definition would actually be used in forward computational graph. I hope this is helpful!

**Comment by Connor-XY** [comment]
Hello @haolibai and everyone who added repro notes, thanks for keeping the overlap-grad-reduce failure visible.

Based on the repro and the later explanation in the thread, this usually happens when a parameter that requires grad is registered into Megatron DDP buckets, but that parameter does not actually participate in the forward/backward graph for that step. With overlapped grad reduce, the bucket waits for all registered parameter hooks to fire; if one parameter is unused or conditionally skipped, the bucket never reaches the expected `params_with_grad == params` state and the assertion fires.

The remaining maintainer question is whether this should be documented as an unsupported/expected user error for overlapped DDP, or whether we can support unused parameters in this path. I am routing this to the distributed-data-parallel owner to confirm the intended behavior.

**Comment by wujingyue** [comment]
The error message seems to be pretty clear and close to the root cause. So I'd keep code as is unless there's an objection.
