### ISSUE TITLE
[BUG] Unable to Convert Mamba PP=1 TP=1 to PP>1 TP>1 Using convert.py

### ISSUE THREAD

**Issue by zixianwang2022** [NVIDIA/Megatron-LM#1153]
**Describe the bug**
Hi, I am unable to use `tools/checkpoint/convert.py` to convert my [pretrained mamba 8b checkpoint](https://huggingface.co/nvidia/mamba2-8b-3t-4k) to PP>1 and/or TP>1. So that I can fine-tune from the pretrained checkpoint in a distributed manner. 

**To Reproduce**
Launch a docker and save the model under desired directory. 
```
python tools/checkpoint/convert.py \
        --model-type GPT \
        --load-dir /workspace/data/ssm-retrieval/mamba2-8b/mamba2-8b-3t-4k/ \
        --save-dir /workspace/data/ssm-retrieval/mamba2-8b/pp1_tp2/ \
        --target-tensor-parallel-size 2 \
        --target-pipeline-parallel-size 1 \
        --megatron-path /workspace/megatron
``` 

**Expected behavior**
Well, ideally it should work fine out of box. 

**Stack trace/logs**
```
micro_batch_times_data_parallel:1
setting number of micro-batches to constant 1
building GPT model ...
 loading release checkpoint from /workspace/data/ssm-retrieval/mamba2-8b/mamba2-8b-3t-4k/
Traceback (most recent call last):
  File "/workspace/megatron/tools/checkpoint/convert.py", line 154, in <module>
Loader exited, exiting saver
    main()
  File "/workspace/megatron/tools/checkpoint/convert.py", line 147, in main
    loader.load_checkpoint(queue, args)
  File "/workspace/megatron/tools/checkpoint/loader_megatron.py", line 375, in load_checkpoint
    _load_checkpoint(queue, args)
  File "/workspace/megatron/tools/checkpoint/loader_megatron.py", line 237, in _load_checkpoint
    all_models = [get_models(tp_size, md.params_dtype)]
  File "/workspace/megatron/tools/checkpoint/loader_megatron.py", line 165, in get_models
    load_checkpoint(model_, None, None)
  File "/workspace/megatron/megatron/training/checkpointing.py", line 767, in load_checkpoint
    model[0].load_state_dict(state_dict['model'], strict=strict)
  File "/workspace/megatron/megatron/legacy/model/gpt_model.py", line 122, in load_state_dict
    self.language_model.load_state_dict(state_dict, strict=strict)
  File "/workspace/megatron/megatron/legacy/model/language_model.py", line 608, in load_state_dict
    self.encoder.load_state_dict(state_dict_, strict=strict)
  File "/workspace/megatron/megatron/legacy/model/transformer.py", line 1814, in load_state_dict
    super().load_state_dict(state_dict_, strict)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ParallelTransformer:
        Missing key(s) in state_dict: "layers.0.input_norm.weight", "layers.0.self_attention.query_key_value.weight", "layers.0.self_attention.dense.weight", "layers.0.post_attention_norm.weight", "layers.0.mlp.dense_h_to_4h.weight", "layers.0.mlp.dense_4h_to_h.weight", "layers.1.input_norm.weight", "layers.1.self_attention.query_key_value.weight", "layers.1.self_attention.dense.weight", "layers.1.post_attention_norm.weight", "layers.1.mlp.dense_h_to_4h.weight", "layers.1.mlp.dense_4h_to_h.weight", "layers.2.input_norm.weight", "layers.2.self_attention.query_key_value.weight", "layers.2.self_attention.dense.weight", "layers.2.post_attention_norm.weight", "layers.2.mlp.dense_h_to_4h.weight", "layers.2.mlp.dense_4h_to_h.weight", "layers.3.input_norm.weight", "layers.3.self_attention.query_key_value.weight", "layers.3.self_attention.dense.weight", "layers.3.post_attention_norm.weight", "layers.3.mlp.dense_h_to_4h.weight", "layers.3.mlp.dense_4h_to_h.weight", "layers.4.input_norm.weight", "layers.4.self_attention.query_key_value.weight", "layers.4.self_attention.dense.weight", "layers.4.post_attention_norm.weight", "layers.4.mlp.dense_h_to_4h.weight", "layers.4.mlp.dense_4h_to_h.weight", "layers.5.input_norm.weight", "layers.5.self_attention.query_key_value.weight", "layers.5.self_attention.dense.weight", "layers.5.post_attention_norm.weight", "layers.5.mlp.dense_h_to_4h.weight", "layers.5.mlp.dense_4h_to_h.weight", "layers.6.input_norm.weight", "layers.6.self_attention.query_key_value.weight", "layers.6.self_attention.dense.weight", "layers.6.post_attention_norm.weight", "layers.6.mlp.dense_h_to_4h.weight", "layers.6.mlp.dense_4h_to_h.weight", "layers.7.input_norm.weight", "layers.7.self_attention.query_key_value.weight", "layers.7.self_attention.dense.weight", "layers.7.post_attention_norm.weight", "layers.7.mlp.dense_h_to_4h.weight", "layers.7.mlp.dense_4h_to_h.weight", "layers.8.input_norm.weight", "layers.8.self_attention.query_key_value.weight", "layers.8.self_attention.dense.weight", "layers.8.post_attention_norm.weight", "layers.8.mlp.dense_h_to_4h.weight", "layers.8.mlp.dense_4h_to_h.weight", "layers.9.input_norm.weight", "layers.9.self_attention.query_key_value.weight", "layers.9.self_attention.dense.weight", "layers.9.post_attention_norm.weight", "layers.9.mlp.dense_h_to_4h.weight", "layers.9.mlp.dense_4h_to_h.weight", "layers.10.input_norm.weight", "layers.10.self_attention.query_key_value.weight", "layers.10.self_attention.dense.weight", "layers.10.post_attention_norm.weight", "layers.10.mlp.dense_h_to_4h.weight", "layers.10.mlp.dense_4h_to_h.weight", "layers.11.input_norm.weight", "layers.11.self_attention.query_key_value.weight", "layers.11.self_attention.dense.weight", "layers.11.post_attention_norm.weight", "layers.11.mlp.dense_h_to_4h.weight", "layers.11.mlp.dense_4h_to_h.weight", "layers.12.input_norm.weight", "layers.12.self_attention.query_key_value.weight", "layers.12.self_attention.dense.weight", "layers.12.post_attention_norm.weight", "layers.12.mlp.dense_h_to_4h.weight", "layers.12.mlp.dense_4h_to_h.weight", "layers.13.input_norm.weight", "layers.13.self_attention.query_key_value.weight", "layers.13.self_attention.dense.weight", "layers.13.post_attention_norm.weight", "layers.13.mlp.dense_h_to_4h.weight", "layers.13.mlp.dense_4h_to_h.weight", "layers.14.input_norm.weight", "layers.14.self_attention.query_key_value.weight", "layers.14.self_attention.dense.weight", "layers.14.post_attention_norm.weight", "layers.14.mlp.dense_h_to_4h.weight", "layers.14.mlp.dense_4h_to_h.weight", "layers.15.input_norm.weight", "layers.15.self_attention.query_key_value.weight", "layers.15.self_attention.dense.weight", "layers.15.post_attention_norm.weight", "layers.15.mlp.dense_h_to_4h.weight", "layers.15.mlp.dense_4h_to_h.weight", "layers.16.input_norm.weight", "layers.16.self_attention.query_key_value.weight", "layers.16.self_attention.dense.weight", "layers.16.post_attention_norm.weight", "layers.16.mlp.dense_h_to_4h.weight", "layers.16.mlp.dense_4h_to_h.weight", "layers.17.input_norm.weight", "layers.17.self_attention.query_key_value.weight", "layers.17.self_attention.dense.weight", "layers.17.post_attention_norm.weight", "layers.17.mlp.dense_h_to_4h.weight", "layers.17.mlp.dense_4h_to_h.weight", "layers.18.input_norm.weight", "layers.18.self_attention.query_key_value.weight", "layers.18.self_attention.dense.weight", "layers.18.post_attention_norm.weight", "layers.18.mlp.dense_h_to_4h.weight", "layers.18.mlp.dense_4h_to_h.weight", "layers.19.input_norm.weight", "layers.19.self_attention.query_key_value.weight", "layers.19.self_attention.dense.weight", "layers.19.post_attention_norm.weight", "layers.19.mlp.dense_h_to_4h.weight", "layers.19.mlp.dense_4h_to_h.weight", "layers.20.input_norm.weight", "layers.20.self_attention.query_key_value.weight", "layers.20.self_attention.dense.weight", "layers.20.post_attention_norm.weight", "layers.20.mlp.dense_h_to_4h.weight", "layers.20.mlp.dense_4h_to_h.weight", "layers.21.input_norm.weight", "layers.21.self_attention.query_key_value.weight", "layers.21.self_attention.dense.weight", "layers.21.post_attention_norm.weight", "layers.21.mlp.dense_h_to_4h.weight", "layers.21.mlp.dense_4h_to_h.weight", "layers.22.input_norm.weight", "layers.22.self_attention.query_key_value.weight", "layers.22.self_attention.dense.weight", "layers.22.post_attention_norm.weight", "layers.22.mlp.dense_h_to_4h.weight", "layers.22.mlp.dense_4h_to_h.weight", "layers.23.input_norm.weight", "layers.23.self_attention.query_key_value.weight", "layers.23.self_attention.dense.weight", "layers.23.post_attention_norm.weight", "layers.23.mlp.dense_h_to_4h.weight", "layers.23.mlp.dense_4h_to_h.weight", "layers.24.input_norm.weight", "layers.24.self_attention.query_key_value.weight", "layers.24.self_attention.dense.weight", "layers.24.post_attention_norm.weight", "layers.24.mlp.dense_h_to_4h.weight", "layers.24.mlp.dense_4h_to_h.weight", "layers.25.input_norm.weight", "layers.25.self_attention.query_key_value.weight", "layers.25.self_attention.dense.weight", "layers.25.post_attention_norm.weight", "layers.25.mlp.dense_h_to_4h.weight", "layers.25.mlp.dense_4h_to_h.weight", "layers.26.input_norm.weight", "layers.26.self_attention.query_key_value.weight", "layers.26.self_attention.dense.weight", "layers.26.post_attention_norm.weight", "layers.26.mlp.dense_h_to_4h.weight", "layers.26.mlp.dense_4h_to_h.weight", "layers.27.input_norm.weight", "layers.27.self_attention.query_key_value.weight", "layers.27.self_attention.dense.weight", "layers.27.post_attention_norm.weight", "layers.27.mlp.dense_h_to_4h.weight", "layers.27.mlp.dense_4h_to_h.weight", "layers.28.input_norm.weight", "layers.28.self_attention.query_key_value.weight", "layers.28.self_attention.dense.weight", "layers.28.post_attention_norm.weight", "layers.28.mlp.dense_h_to_4h.weight", "layers.28.mlp.dense_4h_to_h.weight", "layers.29.input_norm.weight", "layers.29.self_attention.query_key_value.weight", "layers.29.self_attention.dense.weight", "layers.29.post_attention_norm.weight", "layers.29.mlp.dense_h_to_4h.weight", "layers.29.mlp.dense_4h_to_h.weight", "layers.30.input_norm.weight", "layers.30.self_attention.query_key_value.weight", "layers.30.self_attention.dense.weight", "layers.30.post_attention_norm.weight", "layers.30.mlp.dense_h_to_4h.weight", "layers.30.mlp.dense_4h_to_h.weight", "layers.31.input_norm.weight", "layers.31.self_attention.query_key_value.weight", "layers.31.self_attention.dense.weight", "layers.31.post_attention_norm.weight", "layers.31.mlp.dense_h_to_4h.weight", "layers.31.mlp.dense_4h_to_h.weight", "layers.32.input_norm.weight", "layers.32.self_attention.query_key_value.weight", "layers.32.self_attention.dense.weight", "layers.32.post_attention_norm.weight", "layers.32.mlp.dense_h_to_4h.weight", "layers.32.mlp.dense_4h_to_h.weight", "layers.33.input_norm.weight", "layers.33.self_attention.query_key_value.weight", "layers.33.self_attention.dense.weight", "layers.33.post_attention_norm.weight", "layers.33.mlp.dense_h_to_4h.weight", "layers.33.mlp.dense_4h_to_h.weight", "layers.34.input_norm.weight", "layers.34.self_attention.query_key_value.weight", "layers.34.self_attention.dense.weight", "layers.34.post_attention_norm.weight", "layers.34.mlp.dense_h_to_4h.weight", "layers.34.mlp.dense_4h_to_h.weight", "layers.35.input_norm.weight", "layers.35.self_attention.query_key_value.weight", "layers.35.self_attention.dense.weight", "layers.35.post_attention_norm.weight", "layers.35.mlp.dense_h_to_4h.weight", "layers.35.mlp.dense_4h_to_h.weight", "layers.36.input_norm.weight", "layers.36.self_attention.query_key_value.weight", "layers.36.self_attention.dense.weight", "layers.36.post_attention_norm.weight", "layers.36.mlp.dense_h_to_4h.weight", "layers.36.mlp.dense_4h_to_h.weight", "layers.37.input_norm.weight", "layers.37.self_attention.query_key_value.weight", "layers.37.self_attention.dense.weight", "layers.37.post_attention_norm.weight", "layers.37.mlp.dense_h_to_4h.weight", "layers.37.mlp.dense_4h_to_h.weight", "layers.38.input_norm.weight", "layers.38.self_attention.query_key_value.weight", "layers.38.self_attention.dense.weight", "layers.38.post_attention_norm.weight", "layers.38.mlp.dense_h_to_4h.weight", "layers.38.mlp.dense_4h_to_h.weight", "layers.39.input_norm.weight", "layers.39.self_attention.query_key_value.weight", "layers.39.self_attention.dense.weight", "layers.39.post_attention_norm.weight", "layers.39.mlp.dense_h_to_4h.weight", "layers.39.mlp.dense_4h_to_h.weight", "layers.40.input_norm.weight", "layers.40.self_attention.query_key_value.weight", "layers.40.self_attention.dense.weight", "layers.40.post_attention_norm.weight", "layers.40.mlp.dense_h_to_4h.weight", "layers.40.mlp.dense_4h_to_h.weight", "layers.41.input_norm.weight", "layers.41.self_attention.query_key_value.weight", "layers.41.self_attention.dense.weight", "layers.41.post_attention_norm.weight", "layers.41.mlp.dense_h_to_4h.weight", "layers.41.mlp.dense_4h_to_h.weight", "layers.42.input_norm.weight", "layers.42.self_attention.query_key_value.weight", "layers.42.self_attention.dense.weight", "layers.42.post_attention_norm.weight", "layers.42.mlp.dense_h_to_4h.weight", "layers.42.mlp.dense_4h_to_h.weight", "layers.43.input_norm.weight", "layers.43.self_attention.query_key_value.weight", "layers.43.self_attention.dense.weight", "layers.43.post_attention_norm.weight", "layers.43.mlp.dense_h_to_4h.weight", "layers.43.mlp.dense_4h_to_h.weight", "layers.44.input_norm.weight", "layers.44.self_attention.query_key_value.weight", "layers.44.self_attention.dense.weight", "layers.44.post_attention_norm.weight", "layers.44.mlp.dense_h_to_4h.weight", "layers.44.mlp.dense_4h_to_h.weight", "layers.45.input_norm.weight", "layers.45.self_attention.query_key_value.weight", "layers.45.self_attention.dense.weight", "layers.45.post_attention_norm.weight", "layers.45.mlp.dense_h_to_4h.weight", "layers.45.mlp.dense_4h_to_h.weight", "layers.46.input_norm.weight", "layers.46.self_attention.query_key_value.weight", "layers.46.self_attention.dense.weight", "layers.46.post_attention_norm.weight", "layers.46.mlp.dense_h_to_4h.weight", "layers.46.mlp.dense_4h_to_h.weight", "layers.47.input_norm.weight", "layers.47.self_attention.query_key_value.weight", "layers.47.self_attention.dense.weight", "layers.47.post_attention_norm.weight", "layers.47.mlp.dense_h_to_4h.weight", "layers.47.mlp.dense_4h_to_h.weight", "layers.48.input_norm.weight", "layers.48.self_attention.query_key_value.weight", "layers.48.self_attention.dense.weight", "layers.48.post_attention_norm.weight", "layers.48.mlp.dense_h_to_4h.weight", "layers.48.mlp.dense_4h_to_h.weight", "layers.49.input_norm.weight", "layers.49.self_attention.query_key_value.weight", "layers.49.self_attention.dense.weight", "layers.49.post_attention_norm.weight", "layers.49.mlp.dense_h_to_4h.weight", "layers.49.mlp.dense_4h_to_h.weight", "layers.50.input_norm.weight", "layers.50.self_attention.query_key_value.weight", "layers.50.self_attention.dense.weight", "layers.50.post_attention_norm.weight", "layers.50.mlp.dense_h_to_4h.weight", "layers.50.mlp.dense_4h_to_h.weight", "layers.51.input_norm.weight", "layers.51.self_attention.query_key_value.weight", "layers.51.self_attention.dense.weight", "layers.51.post_attention_norm.weight", "layers.51.mlp.dense_h_to_4h.weight", "layers.51.mlp.dense_4h_to_h.weight", "layers.52.input_norm.weight", "layers.52.self_attention.query_key_value.weight", "layers.52.self_attention.dense.weight", "layers.52.post_attention_norm.weight", "layers.52.mlp.dense_h_to_4h.weight", "layers.52.mlp.dense_4h_to_h.weight", "layers.53.input_norm.weight", "layers.53.self_attention.query_key_value.weight", "layers.53.self_attention.dense.weight", "layers.53.post_attention_norm.weight", "layers.53.mlp.dense_h_to_4h.weight", "layers.53.mlp.dense_4h_to_h.weight", "layers.54.input_norm.weight", "layers.54.self_attention.query_key_value.weight", "layers.54.self_attention.dense.weight", "layers.54.post_attention_norm.weight", "layers.54.mlp.dense_h_to_4h.weight", "layers.54.mlp.dense_4h_to_h.weight", "layers.55.input_norm.weight", "layers.55.self_attention.query_key_value.weight", "layers.55.self_attention.dense.weight", "layers.55.post_attention_norm.weight", "layers.55.mlp.dense_h_to_4h.weight", "layers.55.mlp.dense_4h_to_h.weight", "final_norm.weight". 
root@04d32b0bc2ef:/workspace/megatron# 
```

**Environment (please complete the following information):**
 - Megatron-LM commit ID: 703cc88
 - PyTorch version: `>>> torch.__version__.  '2.2.0a0+81ea7a4'` 
 - CUDA version
```
root@66bbe53c15b5:/workspace/megatron/examples/mamba# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Nov_22_10:17:15_PST_2023
Cuda compilation tools, release 12.3, V12.3.107
Build cuda_12.3.r12.3/compiler.33567101_0
```  
 - NCCL version `2.8.10`

**Proposed fix**
I have no clues. 

**Additional context**
The pretrained model should come from distributed training across multi-gpus and multi-nodes. At the end the pretrained model is converted into TP=1 and PP=1. So there should be a way to do this.

**Comment by zixianwang2022** [comment]
Never mind, the regular `convert.py` doesn't work for Mamba, but the `hybrid_conversion.py` does.

**Comment by fxnie** [comment]
I am using the file 'hybrid_conversion. py', but I am encountering a new error message

**Comment by fxnie** [comment]
File "/workspace/mnt/xxx/Megatron-LM/tools/checkpoint/hybrid_conversion.py", line 66, in get_split_dim
    raise Exception("Unknown tensor name {}".format(tensor_name))
Exception: Unknown tensor name decoder.layers.0.mixer.in_proj.layer_norm_weight

**Comment by zixianwang2022** [comment]
> File "/workspace/mnt/xxx/Megatron-LM/tools/checkpoint/hybrid_conversion.py", line 66, in get_split_dim raise Exception("Unknown tensor name {}".format(tensor_name)) Exception: Unknown tensor name decoder.layers.0.mixer.in_proj.layer_norm_weight

It seems like the file is not reading the correct format of the checkpoint. Are you sure the model checkpoint is in the right format?

**Comment by fxnie** [comment]
https://github.com/NVIDIA/Megatron-LM/issues/1336

**Comment by fxnie** [comment]
#!/bin/bash

# Use: ./train.sh <data-path> <tokenizer-path>

MODEL_SCALE="2.7B" # or "8B"

case "${MODEL_SCALE}" in
    "800M")
        TENSOR_MODEL_PARALLEL_SIZE=1
        NUM_LAYERS=48
        HIDDEN_SIZE=1024
        NUM_ATTENTION_HEADS=16
        GLOBAL_BATCH_SIZE=32
        ;;
    "8B")
        TENSOR_MODEL_PARALLEL_SIZE=4
        NUM_LAYERS=56
        HIDDEN_SIZE=4096
        NUM_ATTENTION_HEADS=32
        GLOBAL_BATCH_SIZE=8
        ;;
    "2.7B")
        TENSOR_MODEL_PARALLEL_SIZE=2
        NUM_LAYERS=64
        HIDDEN_SIZE=2560
        NUM_ATTENTION_HEADS=40
        GLOBAL_BATCH_SIZE=256
        ;;
    *)
        echo "Invalid version specified"
        exit 1
        ;;
esac

DATA_PATH="/workspace/mnt/xxx/process_datasets/magpie_llama3/magpie_llama3_text_document"
TOKENIZER_PATH="/workspace/mnt/xxx/model/mamba-hf/tokenizer.json"

export NCCL_IB_SL=1
export CUDA_DEVICE_MAX_CONNECTIONS=1
export NCCL_IB_TIMEOUT=19
export NCCL_IB_QPS_PER_CONNECTION=4
export CUDA_PROFILER_OUTPUT_FILE="/workspace/mnt/xxx/Megatron-LM/profile"


# mamba2
CHECKPOINT_DIR="/workspace/mnt/xxx/models/mamba2-2.7b"
save_path="/workspace/mnt/xxx/ckpt/mamba2-test"
DATACACHE_DIR="/workspace/mnt/xxx/process_datasets/magpie_llama3/magpie_llama3_text_document"
TENSORBOARD_DIR="/workspace/mnt/xxx/Megatron-LM/tensorboard/mamba2"
vocab_file="/workspace/mnt/xxx/models/mamba2-2.7b/vocab.json"
merge_file="/workspace/mnt/xxx/models/mamba2-2.7b/merges.txt"

mkdir -p ${save_path}
mkdir -p ${CHECKPOINT_DIR}
mkdir -p ${DATACACHE_DIR}
mkdir -p ${TENSORBOARD_DIR}

export TRITON_CACHE_DIR="./triton-cache/"
export TRITON_CACHE_MANAGER="megatron.core.ssm.triton_cache_manager:ParallelFileCacheManager"

SEQ_LEN=1024
# TRAIN_SAMPLES=73242188  # 300B tokens / 4096
# LR_WARMUP_SAMPLES=50000
# LR_DECAY_SAMPLES=73192188 # TRAIN_SAMPLES - LR_WARMUP_SAMPLES

options=" \
       --tensor-model-parallel-size ${TENSOR_MODEL_PARALLEL_SIZE} \
       --sequence-parallel \
       --pipeline-model-parallel-size 1 \
       --use-distributed-optimizer \
       --overlap-param-gather \
       --overlap-grad-reduce \
       --vocab-file ${vocab_file} \
       --merge-file ${merge_file} \
       --untie-embeddings-and-output-weights \
       --init-method-std 0.02 \
       --position-embedding-type none \
       --num-layers ${NUM_LAYERS} \
       --hidden-size ${HIDDEN_SIZE} \
       --num-attention-heads ${NUM_ATTENTION_HEADS} \
       --group-query-attention \
       --num-query-groups 8 \
       --hybrid-attention-ratio 0.08 \
       --hybrid-mlp-ratio 0.5 \
       --seq-length ${SEQ_LEN} \
       --max-position-embeddings ${SEQ_LEN} \
       --save ${save_path} \
       --load ${CHECKPOINT_DIR} \
       --data-path ${DATA_PATH} \
       --data-cache-path ${DATACACHE_DIR} \
       --split 100,0,0 \
       --tokenizer-type GPT2BPETokenizer \
       --tokenizer-model ${TOKENIZER_PATH} \
       --distributed-backend nccl \
       --micro-batch-size 8 \
       --global-batch-size ${GLOBAL_BATCH_SIZE} \
       --train-iters 1000 \
       --lr-warmup-fraction 0.05 \
       --lr 2e-4 \
       --min-lr 1e-5 \
       --lr-decay-style cosine \
       --weight-decay 0.1 \
       --clip-grad 1.0 \
       --attention-dropout 0.0 \
       --hidden-dropout 0.0 \
       --disable-bias-linear \
       --normalization RMSNorm \
       --adam-beta1 0.9 \
       --adam-beta2 0.95 \
       --log-interval 5 \
       --save-interval 200 \
       --eval-interval 200 \
       --eval-iters 256 \
       --fp32-residual-connection \
       --bf16 \
       --use-mcore-models \
       --use-flash-attn \
       --no-load-optim \
       --no-load-rng \
       --spec megatron.core.models.mamba.mamba_layer_specs mamba_stack_spec \
       --no-create-attention-mask-in-dataloader \
       --tensorboard-dir ${TENSORBOARD_DIR}"


torchrun --nproc_per_node 4 /workspace/mnt/xxx/Megatron-LM/pretrain_mamba.py ${options}

My training script is shown above and the checkpoint has also been successfully saved. You can see the issue I mentioned earlier。

**Comment by fxnie** [comment]
The above problem has been solved, but after conversion, it is still in pt format. How to convert it to safetensors format?

https://github.com/NVIDIA/Megatron-LM/issues/1339
