### ISSUE TITLE
Dataset does not exist

### ISSUE THREAD

**Issue by BlueCloudDev** [NVIDIA/Megatron-LM#119]
`Dataset does not exist: /data/openwebtext/subset-01
Path should be a basename that both .idx and .bin can be appended to get full filenames.
 > finished creating indexed dataset in 0.000021 seconds
Traceback (most recent call last):
  File "/mega/Megatron-LM/pretrain_gpt.py", line 124, in <module>
    pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
  File "/mega/Megatron-LM/megatron/training.py", line 131, in pretrain
    = build_train_valid_test_data_iterators(
  File "/mega/Megatron-LM/megatron/training.py", line 815, in build_train_valid_test_data_iterators
    train_ds, valid_ds, test_ds = build_train_valid_test_datasets_provider(
  File "/mega/Megatron-LM/pretrain_gpt.py", line 109, in train_valid_test_datasets_provider
    train_ds, valid_ds, test_ds = build_train_valid_test_datasets(
  File "/mega/Megatron-LM/megatron/data/gpt_dataset.py", line 54, in build_train_valid_test_datasets
    train_ds, valid_ds, test_ds = _build_train_valid_test_datasets(
  File "/mega/Megatron-LM/megatron/data/gpt_dataset.py", line 86, in _build_train_valid_test_datasets
    indexed_dataset = get_indexed_dataset_(data_prefix,
  File "/mega/Megatron-LM/megatron/data/gpt_dataset.py", line 134, in get_indexed_dataset_
    indexed_dataset.sizes.shape[0]))
AttributeError: 'NoneType' object has no attribute 'sizes'`

This folder exists, is filled with data, and is accessible from the container through --container-mounts. 

What does this error mean?

How do I provide my data in the format it expects?

**Comment by chaselwin** [comment]
I have the same problem. How can I solve it?

**Comment by zincnode** [comment]
> I have the same problem. How can I solve it?

Hi, I just had this problem and solved it. My data directory: 
```bash
root@5bc77580a1ce:/workdir/ds/data/megatron/books1_text_document# tree ./
./
├── books1_text_document.bin
├── books1_text_document.idx
├── xxxxx
```
"Path should be a basename that both .idx and .bin can be appended to get full filenames" reminded me that `DATA_PATH` should be set to `/workdir/ds/data/megatron/books1_text_document/books1_text_document` instead of `/workdir/ds /data/megatron/books1_text_document`. In my opinion, this should not be called `Path`. In my opinion, this should not be called `Path`. 😂
