### ISSUE TITLE
'BertModel' has no len()

### ISSUE THREAD

**Issue by Lavenderjiang** [NVIDIA/Megatron-LM#149]
Hello, I'm trying to use tools/merge_mp_partitions to combine BERT checkpoints trained with model parallelism. 
However, it seems like BERT model does not have __len__(), and the script gives a type error.
The checkpoints were generated by Megatron, and I did not change anything. Any help would be appreciated!

Here's the error message:
```
merging model parallel partitions ...
 > number of partitions: 2
 > checkpoint path: ./finetune_dir
 > model parameters:
    number of tokens ................ 30002 
    number of layers ................ 48
    hidden size ..................... 256
    number of attention heads ....... 256
    maximum position embeddings ..... 512
initializing torch.distributed...
torch distributed initialized!
> building the full model ...
building BERT model ...
> building BertWordPieceCase tokenizer ...
 > padded vocab (size: 30002) with 206 dummy tokens (new size: 30208)
building BERT model ...
> loading ./finetune_dir/iter_0850000/mp_rank_00/model_optim_rng.pt ...
 loading checkpoint from ./finetune_dir at iteration 850000
Traceback (most recent call last):
  File "./merge_mp_partitions.py", line 364, in <module>
    main()
  File "./merge_mp_partitions.py", line 266, in main
    load_checkpoint(model_, None, None)
  File "~/pretraining/megatron/checkpointing.py", line 359, in load_checkpoint
 if len(model) == 1:
TypeError: object of type 'BertModel' has no len()

```

**Comment by Lavenderjiang** [comment]
Resolved by putting the model in a list.
Changed [this line](https://github.com/NVIDIA/Megatron-LM/blob/3860e995269df61d234ed910d4756e104e1ab844/tools/merge_mp_partitions.py#L254) to 
`   load_checkpoint([model_], None, None)`
