### ISSUE TITLE
ModuleNotFoundError: No module named 'fused_mix_prec_layer_norm_cuda'

### ISSUE THREAD

**Issue by haolin-nju** [NVIDIA/Megatron-LM#192]
I was trying to pretrain BERT from scratch. However, I encountered a module not found error when running merge_mp_bert.sh. Here is how the error looks like.
```shell
$ sh merge_mp_bert.sh
...
> building the full model ...
building BERT model ...
Traceback (most recent call last):
  File "tools/merge_mp_partitions.py", line 352, in <module>
    main()
  File "tools/merge_mp_partitions.py", line 236, in main
    merged_model = get_model(model_type)
  File "tools/merge_mp_partitions.py", line 128, in get_model
    model = model_provider()
  File "/home/linh/opensource/Megatron-LM-2.5/pretrain_bert.py", line 40, in model_provider
    model = BertModel(
  File "/home/linh/opensource/Megatron-LM-2.5/megatron/model/bert_model.py", line 146, in __init__
    self.language_model, self._language_model_key = get_language_model(
  File "/home/linh/opensource/Megatron-LM-2.5/megatron/model/language_model.py", line 62, in get_language_model
    language_model = TransformerLanguageModel(
  File "/home/linh/opensource/Megatron-LM-2.5/megatron/model/language_model.py", line 305, in __init__
    self.encoder = ParallelTransformer(
  File "/home/linh/opensource/Megatron-LM-2.5/megatron/model/transformer.py", line 586, in __init__
    [build_layer(i + 1 + offset) for i in range(self.num_layers)])
  File "/home/linh/opensource/Megatron-LM-2.5/megatron/model/transformer.py", line 586, in <listcomp>
    [build_layer(i + 1 + offset) for i in range(self.num_layers)])
  File "/home/linh/opensource/Megatron-LM-2.5/megatron/model/transformer.py", line 557, in build_layer
    return ParallelTransformerLayer(
  File "/home/linh/opensource/Megatron-LM-2.5/megatron/model/transformer.py", line 405, in __init__
    self.input_layernorm = LayerNorm(
  File "/home/linh/opensource/Megatron-LM-2.5/megatron/model/fused_layer_norm.py", line 68, in __init__
    fused_mix_prec_layer_norm_cuda = importlib.import_module(
  File "/home/linh/anaconda3/envs/torch1.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'fused_mix_prec_layer_norm_cuda'
```

My nvcc version is
```shell
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0
```
, and my `pytorch.version.cuda` is 11.1.

I have tried to reinstall my apex according to these two issues [NVIDIA/apex#161](https://github.com/NVIDIA/apex/issues/161) and  [NVIDIA/apex#954](https://github.com/NVIDIA/apex/issues/954), but the error still exists.

**Comment by itszyin** [comment]
I have the same problem. I directly comment out this codes.

```python
global fused_mix_prec_layer_norm_cuda
# fused_mix_prec_layer_norm_cuda = importlib.import_module(
#   "fused_mix_prec_layer_norm_cuda")
fused_mix_prec_layer_norm_cuda = None
```

**Comment by mayank31398** [comment]
Can someone follow up on this?
This is happening to me as well
@jaredcasper

**Comment by mayank31398** [comment]
fused_mix_prec_layer_norm_cuda is present in fused_kernels folder.
Relaunching the job again fixed the issue for me for some reason.

**Comment by HemantTiwariGitHub** [comment]
Hi I am facing this issue while building on Windows 
`DLL load failed while importing fused_mix_prec_layer_norm_cuda: The specified module could not be found`


nvcc --version
Cuda compilation tools, release 11.1, V11.1.74
Build cuda_11.1.relgpu_drvr455TC455_06.29069683_0

NVIDIA-SMI 452.39
Driver Version: 472.50       
CUDA Version: 11.4
