### ISSUE TITLE
Finetune MNLI

### ISSUE THREAD

**Issue by Waterpine** [NVIDIA/Megatron-LM#217]
When I try to finetune MNLI on slurm, I am confronted with the following issues:

Detected CUDA files, patching ldflags
Emitting ninja build file /home/hongyiwa/Megatron-LM/megatron/fused_kernels/build/build.ninja...
Building extension module scaled_upper_triang_masked_softmax_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] /usr/bin/nvcc  -DTORCH_EXTENSION_NAME=scaled_upper_triang_masked_softmax_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/hongyiwa/.conda/envs/song/lib/python3.9/site-packages/torch/include -isystem /home/hongyiwa/.conda/envs/song/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /home/hongyiwa/.conda/envs/song/lib/python3.9/site-packages/torch/include/TH -isystem /home/hongyiwa/.conda/envs/song/lib/python3.9/site-packages/torch/include/THC -isystem /home/hongyiwa/.conda/envs/song/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 --compiler-options '-fPIC' -O3 -gencode arch=compute_70,code=sm_70 --use_fast_math -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda -gencode arch=compute_80,code=sm_80 -std=c++14 -c /home/hongyiwa/Megatron-LM/megatron/fused_kernels/scaled_upper_triang_masked_softmax_cuda.cu -o scaled_upper_triang_masked_softmax_cuda.cuda.o 
FAILED: scaled_upper_triang_masked_softmax_cuda.cuda.o 
/usr/bin/nvcc  -DTORCH_EXTENSION_NAME=scaled_upper_triang_masked_softmax_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/hongyiwa/.conda/envs/song/lib/python3.9/site-packages/torch/include -isystem /home/hongyiwa/.conda/envs/song/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /home/hongyiwa/.conda/envs/song/lib/python3.9/site-packages/torch/include/TH -isystem /home/hongyiwa/.conda/envs/song/lib/python3.9/site-packages/torch/include/THC -isystem /home/hongyiwa/.conda/envs/song/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 --compiler-options '-fPIC' -O3 -gencode arch=compute_70,code=sm_70 --use_fast_math -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda -gencode arch=compute_80,code=sm_80 -std=c++14 -c /home/hongyiwa/Megatron-LM/megatron/fused_kernels/scaled_upper_triang_masked_softmax_cuda.cu -o scaled_upper_triang_masked_softmax_cuda.cuda.o 
ERROR: No supported gcc/g++ host compiler found.
       Use 'nvcc -ccbin <compiler>' to specify a host compiler.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/hongyiwa/.conda/envs/song/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1740, in _run_ninja_build
    subprocess.run(
  File "/home/hongyiwa/.conda/envs/song/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hongyiwa/Megatron-LM/examples/../tasks/main.py", line 93, in <module>
    initialize_megatron(extra_args_provider=get_tasks_args)
  File "/home/hongyiwa/Megatron-LM/megatron/initialize.py", line 87, in initialize_megatron
    _compile_dependencies()
  File "/home/hongyiwa/Megatron-LM/megatron/initialize.py", line 135, in _compile_dependencies
    fused_kernels.load(args)
  File "/home/hongyiwa/Megatron-LM/megatron/fused_kernels/__init__.py", line 71, in load
    scaled_upper_triang_masked_softmax_cuda = _cpp_extention_load_helper(
  File "/home/hongyiwa/Megatron-LM/megatron/fused_kernels/__init__.py", line 47, in _cpp_extention_load_helper
    return cpp_extension.load(
  File "/home/hongyiwa/.conda/envs/song/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1144, in load
    return _jit_compile(
  File "/home/hongyiwa/.conda/envs/song/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1357, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/hongyiwa/.conda/envs/song/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1469, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/hongyiwa/.conda/envs/song/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1756, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'scaled_upper_triang_masked_softmax_cuda'
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 632720 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 632721 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 632722 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 632719) of binary: /home/hongyiwa/.conda/envs/song/bin/python3
Traceback (most recent call last):
  File "/home/hongyiwa/.conda/envs/song/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/hongyiwa/.conda/envs/song/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/hongyiwa/.conda/envs/song/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/hongyiwa/.conda/envs/song/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/hongyiwa/.conda/envs/song/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/hongyiwa/.conda/envs/song/lib/python3.9/site-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/home/hongyiwa/.conda/envs/song/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/hongyiwa/.conda/envs/song/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 

Could you give a hand to solve it? Thanks!

**Comment by XiaoqingNLP** [comment]
@Waterpine Hi, Do you solved this problem ? I have solved in one node, but it occured again when i training with 2 node.
