### ISSUE TITLE
Numerical difference between ColumnParallelLinear and torch.nn.Linear

### ISSUE THREAD

**Issue by yf225** [NVIDIA/Megatron-LM#248]
We have a simple script to test that `ColumnParallelLinear` and `torch.nn.Linear` always have the same weights and produce the same output if we feed in the same training data. Full version of the script is at https://gist.github.com/yf225/fb17ea158443a530ea2d5a37d2d2a066 and the key part is:
```python
class ColumnParallelLinear(torch.nn.Module):
    def __init__(self, input_size, output_size, world_size, bias=True,
                 stride=1):
        super(ColumnParallelLinear, self).__init__()

        self.input_size = input_size
        self.output_size = output_size
        # Divide the weight matrix along the last dimension.
        self.output_size_per_partition = mpu.divide(output_size, world_size)

        # Note: torch.nn.functional.linear performs XA^T + b and as a result
        # we allocate the transpose.
        self.weight = Parameter(torch.empty(
            self.output_size_per_partition, self.input_size,
            device=torch.cuda.current_device()))
        set_tensor_model_parallel_attributes(tensor=self.weight,
                                             is_parallel=True,
                                             dim=0,
                                             stride=stride)

        if bias:
            self.bias = Parameter(torch.empty(
                self.output_size_per_partition,
                device=torch.cuda.current_device()))
            set_tensor_model_parallel_attributes(tensor=self.bias,
                                                is_parallel=True,
                                                dim=0,
                                                stride=stride)
        else:
            self.register_parameter('bias', None)


    def forward(self, input_):
        input_parallel = mpu.copy_to_tensor_model_parallel_region(input_)
        bias = self.bias
        output_parallel = F.linear(input_parallel, self.weight, bias)
        output = mpu.gather_from_tensor_model_parallel_region(output_parallel)
        return output

...

model_tp = ColumnParallelLinear(input_size=8, output_size=8, world_size=tp_size, bias=False)
model_no_tp = torch.nn.Linear(8, 8, bias=False)

...

for epoch in range(num_epochs):
    ...
    for data in train_loader:
        ...
        inputs, labels = data[0].to(device), data[1].to(device)
        
        optimizer_tp.zero_grad()
        optimizer_no_tp.zero_grad()
        
        outputs_tp = model_tp(inputs)
        outputs_no_tp = model_no_tp(inputs)
        
        loss_tp = criterion(outputs_tp, labels)
        loss_no_tp = criterion(outputs_no_tp, labels)

        if torch.distributed.get_rank() == 0:
            # check outputs and loss have similar values using torch.allclose(rtol=...)
            ...

        loss_tp.backward()
        loss_no_tp.backward()

        optimizer_tp.step()
        optimizer_no_tp.step()

        if torch.distributed.get_rank() == 0:
            # check parameters and buffers have similar values
            check_param_buf_match(model_tp, model_no_tp, tp_size, iter)

        iter += 1
```

However, we observed that when input is random floating-point numbers and input and weight data types are `fp32`, the parameters of `ColumnParallelLinear` and `torch.nn.Linear` will have different values and fail the `torch.allclose(rtol=1e-5)` test (i.e. divergence) after the **first** forward-backward-step iteration:
```
iter: 0: DP rank: 0, TP rank: 0: train: outputs values match between model_tp and model_no_tp!
iter: 0: DP rank: 0, TP rank: 0: train: loss values match between model_tp and model_no_tp!
iter: 0: forward-backward-step is done!
Traceback (most recent call last):
  File "/fsx/users/willfeng/pycls-scale/tests/ColumnParallelLinear_vs_torch_nn_Linear_divergence.py", line 327, in <module>
    main()
  File "/fsx/users/willfeng/pycls-scale/tests/ColumnParallelLinear_vs_torch_nn_Linear_divergence.py", line 322, in main
    check_param_buf_match(model_tp, model_no_tp, tp_size, rtol, iter)
  File "/fsx/users/willfeng/pycls-scale/tests/ColumnParallelLinear_vs_torch_nn_Linear_divergence.py", line 207, in check_param_buf_match
    assert torch.allclose(param_tp, param_no_tp, rtol=rtol), f"iter: {iter}, DP rank: {mpu.get_data_parallel_rank()}, TP rank: {mpu.get_tensor_model_parallel_rank()}: param_tp: {param_tp}, param_no_tp: {param_no_tp}, max abs diff: {torch.max(torch.abs(param_tp - param_no_tp))}"
AssertionError: iter: 0, DP rank: 0, TP rank: 0: param_tp: Parameter containing:
tensor([[ 0.0657,  0.0117, -0.0960,  0.0514,  0.0330,  0.0709, -0.0534,  0.1271]],
       device='cuda:0', requires_grad=True), param_no_tp: tensor([[ 0.0657,  0.0117, -0.0960,  0.0514,  0.0330,  0.0709, -0.0534,  0.1272]],
       device='cuda:0', grad_fn=<SliceBackward0>), max abs diff: 2.0176172256469727e-05
```
Another interesting observation is that if input and weight are in fp16, they diverge after 10 iterations. If input and weight are in bf16, there is no divergence at all.

Our understanding is that tensor sharding in ColumnParallelLinear should not affect the matmul numerics and hence it should always match what we get from torch.nn.Linear regardless of dtype. But the experiment above seems to suggest otherwise.

Would really appreciate any help debugging this discrepancy between `ColumnParallelLinear` and `torch.nn.Linear`. Thanks!

**Comment by rmwor1d** [comment]
Hi, we are recently facing the similar problem of numerical differences between ColumnParallelLinear and torch.nn.Linear, and could you please kindly sharing the cause to this problem you found with us? thanks a lot !
