### ISSUE TITLE
T5 model run on a single gpu

### ISSUE THREAD

**Issue by HueCheng1021** [NVIDIA/Megatron-LM#266]
sh examples/pretrain_t5.sh

setting number of micro-batches to constant 1
> building BertWordPieceLowerCase tokenizer ...
 > padded vocab (size: 21230) with 18 dummy tokens (new size: 21248)
> initializing torch distributed ...
Traceback (most recent call last):
  File "pretrain_t5.py", line 181, in <module>
    forward_step, args_defaults={'tokenizer_type': 'BertWordPieceLowerCase'})
  File "/workspace/Megatron-LM-3.0/megatron/training.py", line 103, in pretrain
    args_defaults=args_defaults)
  File "/workspace/Megatron-LM-3.0/megatron/initialize.py", line 81, in initialize_megatron
    finish_mpu_init()
  File "/workspace/Megatron-LM-3.0/megatron/initialize.py", line 62, in finish_mpu_init
    _initialize_distributed()
  File "/workspace/Megatron-LM-3.0/megatron/initialize.py", line 182, in _initialize_distributed
    timeout=timedelta(minutes=10))
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 595, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/rendezvous.py", line 229, in _env_rendezvous_handler
    master_addr = _get_env_or_raise("MASTER_ADDR")
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/rendezvous.py", line 206, in _get_env_or_raise
    raise _env_error(env_var)
ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable MASTER_ADDR expected, but not set

**Comment by lessw2020** [comment]
You can workaround this by replacing "python" in the "python pretrain_t5.py" with a torchrun launch:
torchrun --nnodes=1 --nproc_per_node=1 --rdzv_id=101 --rdzv_endpoint="localhost:5969 pretrain_t5.py.

This will resolve the error you are hitting.  
Pretty clear these scripts were not tested for the single gpu case though.  
This same error is present in the gpt script as well.
