### ISSUE TITLE
Megtaron code incompatibility with pytorch 2.0

### ISSUE THREAD

**Issue by savitamittal1** [NVIDIA/Megatron-LM#293]
It looks like torch._six module is deprecated in pytorch 2.0. To have megatron compatibility with pytorch 2.0, it willr equire to remove the reference of this module from Megatron optimizer code.

Here is the traceback:
Traceback (most recent call last):
File "pretrain_gpt.py", line 28, in
from megatron.training import pretrain
File "/mnt/azureml/cr/j/d81be8a5d3ae4306b72803cebea562af/exe/wd/megatron/training.py", line 43, in
from megatron.optimizer import get_megatron_optimizer
File "/mnt/azureml/cr/j/d81be8a5d3ae4306b72803cebea562af/exe/wd/megatron/optimizer/init.py", line 23, in
from .optimizer import Float16OptimizerWithFloat16Params, FP32Optimizer
File "/mnt/azureml/cr/j/d81be8a5d3ae4306b72803cebea562af/exe/wd/megatron/optimizer/optimizer.py", line 30, in
from .clip_grads import clip_grad_norm_fp32, count_zeros_fp32
File "/mnt/azureml/cr/j/d81be8a5d3ae4306b72803cebea562af/exe/wd/megatron/optimizer/clip_grads.py", line 19, in
from torch._six import inf
ModuleNotFoundError: No module named 'torch._six'

**Comment by jon-barker** [comment]
Closing. Fixed here: https://github.com/NVIDIA/Megatron-LM/commit/f7056ab0da255378be37a8427414bd65dc9637f6
