### ISSUE TITLE
Using `--data-impl cached` breaks with "AttributeError: 'IndexedCachedDataset' object has no attribute 'get_doc_idx' 

### ISSUE THREAD

**Issue by yaroslavvb** [NVIDIA/Megatron-LM#378]
generation/reading of Megatron "cached" format appears broken in tags/23.05, tags/23.04, f7056ab

How to reproduce:
- Follow basic example under [Data preprocessing](https://github.com/NVIDIA/Megatron-LM#data-preprocessing)
- Generate `.idx` and `.bin` files, ie

```
cd ~/Megatron-LM
export MAX_JOBS=20
VOCAB_FILE=~/data/.../bert-large-uncased-vocab.txt
JSON_PATH=~/data/.../nvidia.json
OUTPUT_PREFIX=~/data/.../nvidia

python tools/preprocess_data.py \
       --input $JSON_PATH \
       --output-prefix $OUTPUT_PREFIX \
       --vocab-file $VOCAB_FILE \
       --dataset-impl cached \
       --tokenizer-type BertWordPieceLowerCase \
       --split-sentences \
        --workers 20 --chunk-size 25
```

run pretraining

```
cd ~/Megatron-LM
export CUDA_DEVICE_MAX_CONNECTIONS=1

export MAX_JOBS=20
CHECKPOINT_PATH=~/data/.../release/mp_rank_00/model_optim_rng.pt
VOCAB_FILE=~/data/.../bert-large-uncased-vocab.txt
DATA_PATH=~/data/.../nvidia_text_sentence

export CUDA_DEVICE_MAX_CONNECTIONS=1

BERT_ARGS="
    --num-layers 24 \
    --hidden-size 1024 \
    --num-attention-heads 16 \
    --seq-length 512 \
    --max-position-embeddings 512 \
    --micro-batch-size 4 \
    --global-batch-size 8 \
    --lr 0.0001 \
    --train-iters 2000000 \
    --lr-decay-iters 990000 \
    --lr-decay-style linear \
    --min-lr 0.00001 \
    --weight-decay 1e-2 \
    --lr-warmup-fraction .01 \
    --clip-grad 1.0 \
    --fp16
"

DATA_ARGS="
    --data-path $DATA_PATH \
    --vocab-file $VOCAB_FILE \
    --data-impl cached \
    --split 949,50,1
"

OUTPUT_ARGS="
    --log-interval 100 \
    --save-interval 10000 \
    --eval-interval 1000 \
    --eval-iters 10
"

torchrun pretrain_bert.py \
    $BERT_ARGS \
    $DATA_ARGS \
    $OUTPUT_ARGS \
    --save $CHECKPOINT_PATH \
    --load $CHECKPOINT_PATH
```

See the following

```
Emitting ninja build file /home/yaroslav_nvkf_ai/Megatron-LM/megatron/fused_kernels/build/build.ninja...
Building extension module scaled_softmax_cuda...
Using envvar MAX_JOBS (20) as the number of workers...
ninja: no work to do.
Loading extension module scaled_softmax_cuda...
>>> done with compiling and loading fused kernels. Compilation time: 2.190 seconds
time to initialize megatron (seconds): 4.230
[after megatron is initialized] datetime: 2023-06-16 21:43:40 
building BERT model ...
 > number of parameters on (tensor, pipeline) model parallel rank (0, 0): 336297858
> learning rate decay style: linear
WARNING: could not find the metadata file /home/yaroslav_nvkf_ai/data/jklp/release/mp_rank_00/model_optim_rng.pt/latest_checkpointed_iteration.txt 
    will not load any checkpoints and will start from random
/home/yaroslav_nvkf_ai/anaconda3/envs/megatron/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py:2562: UserWarning: torch.distributed._all_gather_base is a private function and will be deprecated. Please use torch.distributed.all_gather_into_tensor instead.
  warnings.warn(
(min, max) time across ranks (ms):
    load-checkpoint ................................: (1.74, 1.74)
[after model, optimizer, and learning rate scheduler are built] datetime: 2023-06-16 21:43:40 
> building train, validation, and test datasets ...
 > datasets target sizes (minimum size):
    train:      16000000
    validation: 160080
    test:       80
> building train, validation, and test datasets for BERT ...
 > building dataset index ...
 > finished creating indexed dataset in 0.002279 seconds
 > indexed dataset stats:
    number of documents: 2
    number of sentences: 2
 > dataset split:
    train:
     document indices in [0, 2) total of 2 documents
     sentence indices in [0, 2) total of 2 sentences
    validation:
     document indices in [2, 2) total of 0 documents
     sentence indices in [2, 2) total of 0 sentences
    test:
     document indices in [2, 2) total of 0 documents
     sentence indices in [2, 2) total of 0 sentences
Traceback (most recent call last):
  File "/home/yaroslav_nvkf_ai/Megatron-LM/pretrain_bert.py", line 134, in <module>
    pretrain(train_valid_test_datasets_provider, model_provider,
  File "/home/yaroslav_nvkf_ai/Megatron-LM/megatron/training.py", line 134, in pretrain
    = build_train_valid_test_data_iterators(
  File "/home/yaroslav_nvkf_ai/Megatron-LM/megatron/training.py", line 979, in build_train_valid_test_data_iterators
    build_train_valid_test_data_loaders(
  File "/home/yaroslav_nvkf_ai/Megatron-LM/megatron/training.py", line 940, in build_train_valid_test_data_loaders
    train_ds, valid_ds, test_ds = build_train_valid_test_datasets(
  File "/home/yaroslav_nvkf_ai/Megatron-LM/megatron/training.py", line 913, in build_train_valid_test_datasets
    return build_train_valid_test_datasets_provider(train_val_test_num_samples)
  File "/home/yaroslav_nvkf_ai/Megatron-LM/pretrain_bert.py", line 116, in train_valid_test_datasets_provider
    train_ds, valid_ds, test_ds = build_train_valid_test_datasets(
  File "/home/yaroslav_nvkf_ai/Megatron-LM/megatron/data/dataset_utils.py", line 431, in build_train_valid_test_datasets
    return _build_train_valid_test_datasets(data_prefix[0],
  File "/home/yaroslav_nvkf_ai/Megatron-LM/megatron/data/dataset_utils.py", line 589, in _build_train_valid_test_datasets
    train_dataset = build_dataset(0, 'train')
  File "/home/yaroslav_nvkf_ai/Megatron-LM/megatron/data/dataset_utils.py", line 535, in build_dataset
    doc_idx_ptr = indexed_dataset.get_doc_idx()
AttributeError: 'IndexedCachedDataset' object has no attribute 'get_doc_idx'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 43659) of binary: /home/yaroslav_nvkf_ai/anaconda3/envs/megatron/bin/python
```

**Comment by jon-barker** [comment]
I've replicated this. Debugging today.

**Comment by jon-barker** [comment]
@yaroslavvb Looking into this more it appears we've never supported `--data-impl cached`, it was carried over from fairseq but needs updating with document indexing. Can you share why you're looking to use it rather than mmap?

**Comment by yaroslavvb** [comment]
@jon-barker we ran out of memory processing Common Crawl with 10GB chunks using `--mmap` option, switching to `--cached` allowed us to process it without crashing. If `--cached` is not supported, would make sense to close this issue, perhaps a with a doc update indicating it's not supported

**Comment by jon-barker** [comment]
@yaroslavvb We have a fix incoming today for the OOM error you encountered with mmap. We'll also remove the `--cached` option and references.

**Comment by jon-barker** [comment]
@yaroslavvb Sorry for the delay getting this in, but the OOM issue you encountered with mmap option for 10GB chunks should be solved by the update to `preprocess_data.py` in https://github.com/NVIDIA/Megatron-LM/commit/4f8e9ac412eff9cabae31495b9f5f3f02fe5a9d4

References to `lazy` and `cached` have also been removed from the docs.

Closing the issue, let me know if you hit any issues with this change.
