### ISSUE TITLE
RuntimeError: Cannot process input tensor without concrete number of dimensions.

### ISSUE THREAD

**Issue by AlphaNext** [NVIDIA/Megatron-LM#409]
## 1) Environment
```
torch                         1.10.1+cu111
torchaudio                    0.10.1+cu111
torchvision                   0.11.2+cu111
```
**Note: Don't use the docker images in README**
```
docker pull nvcr.io/nvidia/pytorch:xx.xx-py3
docker run --gpus all -it --rm -v /path/to/megatron:/workspace/megatron -v /path/to/dataset:/workspace/dataset -v /path/to/checkpoints:/workspace/checkpoints nvcr.io/nvidia/pytorch:xx.xx-py3
```

## 3) ERROR log:

```
Loading extension module scaled_softmax_cuda...
>>> done with compiling and loading fused kernels. Compilation time: 6.691 seconds
/home/Code/public_algos/NV-Megatron-LM/megatron/initialize.py:277: UserWarning: FALLBACK path is taken. This is an indication that codegenFailed for some reason. To debug try disable codege
n fallback pathvia setting the env variable`export PYTORCH_CUDA_FUSER_DISABLE_FALLBACK=1` (Triggered internally at  ../torch/csrc/jit/codegen/cuda/manager.cpp:274.)
  output = bias_gelu(bias, input)
Traceback (most recent call last):
  File "pretrain_bert.py", line 139, in <module>
    forward_step, args_defaults={'tokenizer_type': 'BertWordPieceLowerCase'})
  File "/home/Code/public_algos/NV-Megatron-LM/megatron/training.py", line 93, in pretrain
    set_jit_fusion_options()
  File "/home/Code/public_algos/NV-Megatron-LM/megatron/initialize.py", line 253, in set_jit_fusion_options
    _warmup_jit_function()
  File "/home/Code/public_algos/NV-Megatron-LM/megatron/initialize.py", line 302, in _warmup_jit_function
    output = bias_dropout_add_fused_train(input, bias, residual, dropout_rate)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: Cannot process input tensor without concrete number of dimensions.

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 16017) of binary: /opt/conda/bin/python3.7
```

**Comment by SefaZeng** [comment]
hi, @AlphaNext , do you solve this problem? I met the same issue.

**Comment by GuanhuaWang** [comment]
I got same error as well.

**Comment by ydshi0** [comment]
I got same error as well.

**Comment by GuanhuaWang** [comment]
The problem is not solved.
