### ISSUE TITLE
[QUESTION] Unable to find address for: bond1

### ISSUE THREAD

**Issue by SefaZeng** [NVIDIA/Megatron-LM#436]
**Your question**
Ask a clear and concise question about Megatron-LM.
I try to run `pretrain_gpt_distributed_with_mp.sh` with 2 nodes and 8 GPUS_PER_NODE, but there is an error about `RuntimeError: [enforce fail at /root/pytorch/third_party/gloo/gloo/transport/tcp/device.cc:83] ifa != nullptr. Unable to find address for: bond1`.
The full log:
```
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/usr/local/python/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 
  warn(f"Failed to load image Python extension: {e}")
/usr/local/python/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 
  warn(f"Failed to load image Python extension: {e}")
/usr/local/python/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 
  warn(f"Failed to load image Python extension: {e}")
/usr/local/python/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 
  warn(f"Failed to load image Python extension: {e}")
/usr/local/python/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 
  warn(f"Failed to load image Python extension: {e}")
/usr/local/python/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 
  warn(f"Failed to load image Python extension: {e}")
/usr/local/python/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 
  warn(f"Failed to load image Python extension: {e}")
/usr/local/python/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 
  warn(f"Failed to load image Python extension: {e}")
You are using the legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
You are using the legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
You are using the legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
You are using the legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
You are using the legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
You are using the legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
You are using the legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
You are using the legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
/usr/local/python/lib/python3.8/site-packages/transformers/convert_slow_tokenizer.py:470: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
/usr/local/python/lib/python3.8/site-packages/transformers/convert_slow_tokenizer.py:470: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
/usr/local/python/lib/python3.8/site-packages/transformers/convert_slow_tokenizer.py:470: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
/usr/local/python/lib/python3.8/site-packages/transformers/convert_slow_tokenizer.py:470: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
/usr/local/python/lib/python3.8/site-packages/transformers/convert_slow_tokenizer.py:470: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
/usr/local/python/lib/python3.8/site-packages/transformers/convert_slow_tokenizer.py:470: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
/usr/local/python/lib/python3.8/site-packages/transformers/convert_slow_tokenizer.py:470: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
/usr/local/python/lib/python3.8/site-packages/transformers/convert_slow_tokenizer.py:470: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
Traceback (most recent call last):
  File "/workspace/Megatron-LM/pretrain_gpt.py", line 119, in <module>
    pretrain(train_valid_test_datasets_provider,
  File "/workspace/Megatron-LM/megatron/training.py", line 90, in pretrain
    initialize_megatron(extra_args_provider=extra_args_provider,
  File "/workspace/Megatron-LM/megatron/initialize.py", line 80, in initialize_megatron
    finish_mpu_init()
  File "/workspace/Megatron-LM/megatron/initialize.py", line 60, in finish_mpu_init
    _initialize_distributed()
  File "/workspace/Megatron-LM/megatron/initialize.py", line 209, in _initialize_distributed
    mpu.initialize_model_parallel(
  File "/workspace/Megatron-LM/megatron/core/parallel_state.py", line 169, in initialize_model_parallel
    group_gloo = torch.distributed.new_group(ranks, backend="gloo")
  File "/usr/local/python/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2966, in new_group
    pg = _new_process_group_helper(
  File "/usr/local/python/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 703, in _new_process_group_helper
    pg = ProcessGroupGloo(prefix_store, rank, world_size, timeout=timeout)
RuntimeError: [enforce fail at /root/pytorch/third_party/gloo/gloo/transport/tcp/device.cc:83] ifa != nullptr. Unable to find address for: bond1
Traceback (most recent call last):
  File "/workspace/Megatron-LM/pretrain_gpt.py", line 119, in <module>
    pretrain(train_valid_test_datasets_provider,
  File "/workspace/Megatron-LM/megatron/training.py", line 90, in pretrain
Traceback (most recent call last):
  File "/workspace/Megatron-LM/pretrain_gpt.py", line 119, in <module>
Traceback (most recent call last):
  File "/workspace/Megatron-LM/pretrain_gpt.py", line 119, in <module>
    initialize_megatron(extra_args_provider=extra_args_provider,
  File "/workspace/Megatron-LM/megatron/initialize.py", line 80, in initialize_megatron
    pretrain(train_valid_test_datasets_provider,
  File "/workspace/Megatron-LM/megatron/training.py", line 90, in pretrain
    pretrain(train_valid_test_datasets_provider,
  File "/workspace/Megatron-LM/megatron/training.py", line 90, in pretrain
    finish_mpu_init()
  File "/workspace/Megatron-LM/megatron/initialize.py", line 60, in finish_mpu_init
    initialize_megatron(extra_args_provider=extra_args_provider,
  File "/workspace/Megatron-LM/megatron/initialize.py", line 80, in initialize_megatron
    initialize_megatron(extra_args_provider=extra_args_provider,
  File "/workspace/Megatron-LM/megatron/initialize.py", line 80, in initialize_megatron
    _initialize_distributed()
  File "/workspace/Megatron-LM/megatron/initialize.py", line 209, in _initialize_distributed
    finish_mpu_init()
  File "/workspace/Megatron-LM/megatron/initialize.py", line 60, in finish_mpu_init
    finish_mpu_init()
  File "/workspace/Megatron-LM/megatron/initialize.py", line 60, in finish_mpu_init
    _initialize_distributed()
  File "/workspace/Megatron-LM/megatron/initialize.py", line 209, in _initialize_distributed
    mpu.initialize_model_parallel(
  File "/workspace/Megatron-LM/megatron/core/parallel_state.py", line 169, in initialize_model_parallel
    _initialize_distributed()
  File "/workspace/Megatron-LM/megatron/initialize.py", line 209, in _initialize_distributed
    mpu.initialize_model_parallel(
  File "/workspace/Megatron-LM/megatron/core/parallel_state.py", line 169, in initialize_model_parallel
    group_gloo = torch.distributed.new_group(ranks, backend="gloo")
  File "/usr/local/python/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2966, in new_group
    mpu.initialize_model_parallel(
  File "/workspace/Megatron-LM/megatron/core/parallel_state.py", line 169, in initialize_model_parallel
    group_gloo = torch.distributed.new_group(ranks, backend="gloo")
  File "/usr/local/python/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2966, in new_group
    group_gloo = torch.distributed.new_group(ranks, backend="gloo")
  File "/usr/local/python/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2966, in new_group
    pg = _new_process_group_helper(
  File "/usr/local/python/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 703, in _new_process_group_helper
    pg = ProcessGroupGloo(prefix_store, rank, world_size, timeout=timeout)
RuntimeError: [enforce fail at /root/pytorch/third_party/gloo/gloo/transport/tcp/device.cc:83] ifa != nullptr. Unable to find address for: bond1
    pg = _new_process_group_helper(
  File "/usr/local/python/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 703, in _new_process_group_helper
    pg = _new_process_group_helper(
  File "/usr/local/python/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 703, in _new_process_group_helper
    pg = ProcessGroupGloo(prefix_store, rank, world_size, timeout=timeout)
RuntimeError: [enforce fail at /root/pytorch/third_party/gloo/gloo/transport/tcp/device.cc:83] ifa != nullptr. Unable to find address for: bond1
    pg = ProcessGroupGloo(prefix_store, rank, world_size, timeout=timeout)
RuntimeError: [enforce fail at /root/pytorch/third_party/gloo/gloo/transport/tcp/device.cc:83] ifa != nullptr. Unable to find address for: bond1
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 93 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 95 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 97 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 99 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 92) of binary: /usr/local/python/bin/python3.8
ERROR:torch.distributed.elastic.agent.server.api:Error waiting on exit barrier. Elapsed: 315.7617883682251 seconds
Traceback (most recent call last):
  File "/usr/local/python/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 906, in _exit_barrier
    store_util.barrier(
  File "/usr/local/python/lib/python3.8/site-packages/torch/distributed/elastic/utils/store.py", line 67, in barrier
    synchronize(store, data, rank, world_size, key_prefix, barrier_timeout)
  File "/usr/local/python/lib/python3.8/site-packages/torch/distributed/elastic/utils/store.py", line 53, in synchronize
    agent_data = get_all(store, key_prefix, world_size)
  File "/usr/local/python/lib/python3.8/site-packages/torch/distributed/elastic/utils/store.py", line 31, in get_all
    data = store.get(f"{prefix}{idx}")
RuntimeError: Socket Timeout
Traceback (most recent call last):
  File "/usr/local/python/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/python/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/python/lib/python3.8/site-packages/torch/distributed/run.py", line 724, in main
    run(args)
  File "/usr/local/python/lib/python3.8/site-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/usr/local/python/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/python/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/workspace/Megatron-LM/pretrain_gpt.py FAILED
```

**Comment by plegresl** [comment]
Can you try running this little test program (using the same number of nodes and GPUs per node as the failure above) and see if this works on your infrastructure?

`import os
import torch
import torch.distributed as dist

dist.init_process_group(backend='gloo')

rank = os.getenv('RANK', -1)

print(rank, 'entering barrier...')
torch.distributed.barrier()
print(rank, 'through barrier...')`

**Comment by SefaZeng** [comment]
> Can you try running this little test program (using the same number of nodes and GPUs per node as the failure above) and see if this works on your infrastructure?
> 
> `import os import torch import torch.distributed as dist
> 
> dist.init_process_group(backend='gloo')
> 
> rank = os.getenv('RANK', -1)
> 
> print(rank, 'entering barrier...') torch.distributed.barrier() print(rank, 'through barrier...')`

Thank you. I will try this script. I try to comment out the gloo related code which is `group_gloo = torch.distributed.new_group(ranks, backend="gloo")` and the error above disappeared. But there is another error about NCCL: 
`RuntimeError: NCCL error in: /root/pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1102, internal error, NCCL version 21.2.12`
Is this error due to a pytorch version issue? What version of pytorch is needed for Megatron-LM, will 1.10 do?

**Comment by SefaZeng** [comment]
> Can you try running this little test program (using the same number of nodes and GPUs per node as the failure above) and see if this works on your infrastructure?
> 
> `import os import torch import torch.distributed as dist
> 
> dist.init_process_group(backend='gloo')
> 
> rank = os.getenv('RANK', -1)
> 
> print(rank, 'entering barrier...') torch.distributed.barrier() print(rank, 'through barrier...')`

The same error occurs in this program:
```
Traceback (most recent call last):
  File "/workspace/test.py", line 5, in <module>
    dist.init_process_group(backend='gloo')
  File "/usr/local/python/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 602, in init_process_group
    default_pg = _new_process_group_helper(
  File "/usr/local/python/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 703, in _new_process_group_helper
    pg = ProcessGroupGloo(prefix_store, rank, world_size, timeout=timeout)
RuntimeError: [enforce fail at /root/pytorch/third_party/gloo/gloo/transport/tcp/device.cc:83] ifa != nullptr. Unable to find address for: bond1

```

**Comment by plegresl** [comment]
Since the small test program fails with the Gloo backend there might be something wrong with your compute infrastructure. My best guess is that there is an incorrect setting of GLOO_SOCKET_IFNAME, or Gloo cannot figure out the correct network interface name and you need to provide the correct interface name in that environment variable. See https://pytorch.org/docs/stable/distributed.html#common-environment-variables for more information.

For the internal NCCL error, please rerun with the environment variable NCCL_DEBUG set to at least INFO. See https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/env.html#nccl-debug for more information.

We recommend using PyTorch containers from NGC (https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch). Also see https://github.com/NVIDIA/Megatron-LM#setup for more information.

**Comment by SefaZeng** [comment]
The problem is NCCL can not find the correct NCCL_SOCKET_IFNAME, I try to set `NCCL_SOCKET_IFNAME=eth0` but it also failed. Then I find `ifconfig` print `eth1`, I guess ifconfig will give the right IFNAME for NCCL.
But for me, I try to set `export NCCL_SOCKET_IFNAME=eth,en,em,bond` and the training goes well.
