### ISSUE TITLE
[QUESTION] torch.distributed.DistBackendError: NCCL error in: /opt/pytorch/pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1164, internal error - please report this issue to the NCCL developers, NCCL version 2.18.1

### ISSUE THREAD

**Issue by sedrick-keh-tri** [NVIDIA/Megatron-LM#450]
**Your question**
I am trying to run Megatron multi-node on Docker.

I have a docker set up on both nodes. Specifically, I run the following in each node:
 ```bash
docker run --gpus all --shm-size=1g --ipc=host --network=host --env NCCL_DEBUG=INFO --env NCCL_SOCKET_IFNAME=^docker0,lo -it --rm -v /home/${USER}:/workspace nvcr.io/nvidia/pytorch:23.06-py3
```

In Node 1, I run `examples/pretrain_gpt_distributed_with_mp.sh` with the following hyperparameters: 
```bash
MASTER_ADDR="<IP_address_of_node_1>"
MASTER_PORT=6000
NNODES=2
NODE_RANK=0
WORLD_SIZE=$(($GPUS_PER_NODE*$NNODES))
```

In Node 2, I run a similar script with the following hyperprameters: (basically the same except for `NODE_RANK`)
```bash
MASTER_ADDR="<IP_address_of_node_1>"
MASTER_PORT=6000
NNODES=2
NODE_RANK=1
WORLD_SIZE=$(($GPUS_PER_NODE*$NNODES))
```
Here, "<IP_address_of_node_1>" is the IP address of the original node (before calling `docker run`) 

The scripts above work fine outside of Docker, but when I run it inside Docker, I get the following error:
```
<cluster_name>:462:635 [3] proxy.cc:1484 NCCL WARN [Service thread] Error encountered progressing operation=Connect, res=2, closing connection
<cluster_name>:464:637 [5] NCCL INFO misc/socket.cc:583 -> 2

<cluster_name>:462:635 [3] proxy.cc:1518 NCCL WARN [Proxy Service 11] Failed to execute operation Connect from rank 11, retcode 2
<cluster_name>:464:637 [5] NCCL INFO transport/net_socket.cc:336 -> 2
<cluster_name>:464:637 [5] NCCL INFO transport/net.cc:592 -> 2
<cluster_name>:464:637 [5] NCCL INFO proxy.cc:1306 -> 2

<cluster_name>:464:637 [5] proxy.cc:1484 NCCL WARN [Service thread] Error encountered progressing operation=Connect, res=2, closing connection

<cluster_name>:464:637 [5] proxy.cc:1518 NCCL WARN [Proxy Service 13] Failed to execute operation Connect from rank 13, retcode 2

<cluster_name>:462:633 [3] misc/socket.cc:49 NCCL WARN socketProgress: Connection closed by remote peer <cluster_name>.cm.cluster<38293>
<cluster_name>:462:633 [3] NCCL INFO misc/socket.cc:746 -> 6

<cluster_name>:464:628 [5] misc/socket.cc:49 NCCL WARN socketProgress: Connection closed by remote peer <cluster_name>.cm.cluster<39443>
<cluster_name>:462:633 [3] proxy.cc:1143 NCCL WARN Socket recv failed while polling for opId=0x7ffeb707dab0
<cluster_name>:464:628 [5] NCCL INFO misc/socket.cc:746 -> 6
<cluster_name>:462:633 [3] NCCL INFO transport/net.cc:288 -> 3

Traceback (most recent call last):
  File "/workspace/Megatron-LM/pretrain_gpt.py", line 119, in <module>
Traceback (most recent call last):
  File "/workspace/Megatron-LM/pretrain_gpt.py", line 119, in <module>
    pretrain(train_valid_test_datasets_provider,
  File "/workspace/Megatron-LM/megatron/training.py", line 90, in pretrain
    pretrain(train_valid_test_datasets_provider,
  File "/workspace/Megatron-LM/megatron/training.py", line 90, in pretrain
    initialize_megatron(extra_args_provider=extra_args_provider,
  File "/workspace/Megatron-LM/megatron/initialize.py", line 86, in initialize_megatron
    initialize_megatron(extra_args_provider=extra_args_provider,
  File "/workspace/Megatron-LM/megatron/initialize.py", line 86, in initialize_megatron
    _compile_dependencies()
  File "/workspace/Megatron-LM/megatron/initialize.py", line 150, in _compile_dependencies
    _compile_dependencies()
  File "/workspace/Megatron-LM/megatron/initialize.py", line 150, in _compile_dependencies
    torch.distributed.barrier()
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 145, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 3553, in barrier
    torch.distributed.barrier()
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 145, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 3553, in barrier
    work = default_pg.barrier(opts=opts)
torch.distributed.DistBackendError: NCCL error in: /opt/pytorch/pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1164, internal error - please report this issue to the NCCL developers, NCCL version 2.18.1
ncclInternalError: Internal check failed.
Last error:
Socket recv failed while polling for opId=0x7ffeb708d1f0
    work = default_pg.barrier(opts=opts)
```

**Comment by deepakn94** [comment]
Looks like this is a NCCL setup issue, can I close this?
