### ISSUE TITLE
[BUG] argparse % escape error for --help

### ISSUE THREAD

**Issue by mare5x** [NVIDIA/Megatron-LM#472]
**Describe the bug**
Error when calling `python tools/retro/main.py --help`.

**To Reproduce**
Call from the repository root:
`python tools/retro/main.py --help` (or `python -m tools.retro.main --help`)

**Expected behavior**
Help should be shown. It isn't.

**Stack trace/logs**
```bash
$ python tools/retro/main.py --help
Traceback (most recent call last):
  File "/home/marko/dev/fl-retro/Megatron-LM/tools/retro/main.py", line 197, in <module>
    initialize_megatron(extra_args_provider=add_retro_args)
  File "/home/marko/dev/fl-retro/Megatron-LM/megatron/initialize.py", line 44, in initialize_megatron
    args = parse_args(extra_args_provider, ignore_unknown_args)
  File "/home/marko/dev/fl-retro/Megatron-LM/megatron/arguments.py", line 50, in parse_args
    args = parser.parse_args()
  File "/home/marko/miniconda3/envs/fl-retro/lib/python3.10/argparse.py", line 1833, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/home/marko/miniconda3/envs/fl-retro/lib/python3.10/argparse.py", line 1866, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/marko/miniconda3/envs/fl-retro/lib/python3.10/argparse.py", line 2079, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/home/marko/miniconda3/envs/fl-retro/lib/python3.10/argparse.py", line 2019, in consume_optional
    take_action(action, args, option_string)
  File "/home/marko/miniconda3/envs/fl-retro/lib/python3.10/argparse.py", line 1943, in take_action
    action(self, namespace, argument_values, option_string)
  File "/home/marko/miniconda3/envs/fl-retro/lib/python3.10/argparse.py", line 1106, in __call__
    parser.print_help()
  File "/home/marko/miniconda3/envs/fl-retro/lib/python3.10/argparse.py", line 2567, in print_help
    self._print_message(self.format_help(), file)
  File "/home/marko/miniconda3/envs/fl-retro/lib/python3.10/argparse.py", line 2551, in format_help
    return formatter.format_help()
  File "/home/marko/miniconda3/envs/fl-retro/lib/python3.10/argparse.py", line 283, in format_help
    help = self._root_section.format_help()
  File "/home/marko/miniconda3/envs/fl-retro/lib/python3.10/argparse.py", line 214, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/home/marko/miniconda3/envs/fl-retro/lib/python3.10/argparse.py", line 214, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/home/marko/miniconda3/envs/fl-retro/lib/python3.10/argparse.py", line 214, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/home/marko/miniconda3/envs/fl-retro/lib/python3.10/argparse.py", line 214, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/home/marko/miniconda3/envs/fl-retro/lib/python3.10/argparse.py", line 540, in _format_action
    help_text = self._expand_help(action)
  File "/home/marko/miniconda3/envs/fl-retro/lib/python3.10/argparse.py", line 637, in _expand_help
    return self._get_help_string(action) % params
ValueError: incomplete format
```

**Environment (please complete the following information):**
 - Megatron-LM commit ID: `2ea701c78ed03924069846fcfd445f3415be7b56`
 - PyTorch version: `2.0.1`
 - CUDA version: `11.8`
 - NCCL version `(2, 14, 3)`

**Proposed fix**
#473

**Comment by mare5x** [comment]
Fixed in https://github.com/NVIDIA/Megatron-LM/commit/1aa7144f8946e8b5149db6cc40bfa7224df25c75.
