### ISSUE TITLE
[QUESTION] Hello, when finetune llama2-7B, it's error: RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

### ISSUE THREAD

**Issue by 13416157913** [NVIDIA/Megatron-LM#549]
Hello, when finetune llama2-7B, it's error: RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)` like this:
Traceback (most recent call last):
  File "/home/dengkaibiao/Megatron-LM/./tasks/main.py", line 102, in <module>
    main()
  File "/home/dengkaibiao/Megatron-LM/tasks/glue/finetune.py", line 81, in main
    glue_classification(num_classes, Dataset, name_from_datapath)
  File "/home/dengkaibiao/Megatron-LM/tasks/glue/finetune.py", line 52, in glue_classification
    finetune(train_valid_datasets_provider, model_provider,
  File "/home/dengkaibiao/Megatron-LM/tasks/finetune_utils.py", line 298, in finetune
    _train(model, optimizer, opt_param_scheduler, forward_step,
  File "/home/dengkaibiao/Megatron-LM/tasks/finetune_utils.py", line 186, in _train
    out = train_step(forward_step, batch, model, optimizer, opt_param_scheduler,config)
  File "/home/dengkaibiao/Megatron-LM/megatron/training.py", line 416, in train_step
    losses_reduced = forward_backward_func(
  File "/home/dengkaibiao/Megatron-LM/megatron/core/pipeline_parallel/schedules.py", line 341, in forward_backward_no_pipelining
    output_tensor = forward_step(
  File "/home/dengkaibiao/Megatron-LM/megatron/core/pipeline_parallel/schedules.py", line 184, in forward_step
    output_tensor, loss_func = forward_step_func(data_iterator, model)
  File "/home/dengkaibiao/Megatron-LM/tasks/finetune_utils.py", line 68, in _cross_entropy_forward_step
    output_tensor = model(tokens, attention_mask, tokentype_ids=types)
  File "/home/dengkaibiao/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dengkaibiao/Megatron-LM/megatron/model/distributed.py", line 236, in forward
    return self.module(*inputs, **kwargs)
  File "/home/dengkaibiao/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dengkaibiao/Megatron-LM/megatron/model/module.py", line 181, in forward
    outputs = self.module(*inputs, **kwargs)
  File "/home/dengkaibiao/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dengkaibiao/Megatron-LM/megatron/model/classification.py", line 58, in forward
    lm_output = self.language_model(
  File "/home/dengkaibiao/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dengkaibiao/Megatron-LM/megatron/model/language_model.py", line 501, in forward
    encoder_output = self.encoder(
  File "/home/dengkaibiao/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dengkaibiao/Megatron-LM/megatron/model/transformer.py", line 1668, in forward
    hidden_states = layer(
  File "/home/dengkaibiao/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dengkaibiao/Megatron-LM/megatron/model/transformer.py", line 1057, in forward
    self.self_attention(
  File "/home/dengkaibiao/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dengkaibiao/Megatron-LM/megatron/model/transformer.py", line 573, in forward
    mixed_x_layer, _ = self.query_key_value(hidden_states)
  File "/home/dengkaibiao/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dengkaibiao/Megatron-LM/megatron/core/tensor_parallel/layers.py", line 733, in forward
    output_parallel = self._forward_impl(
  File "/home/dengkaibiao/Megatron-LM/megatron/core/tensor_parallel/layers.py", line 534, in linear_with_grad_accumulation_and_async_allreduce
    return LinearWithGradAccumulationAndAsyncCommunication.apply(*args)
  File "/home/dengkaibiao/anaconda3/lib/python3.10/site-packages/torch/cuda/amp/autocast_mode.py", line 97, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/home/dengkaibiao/Megatron-LM/megatron/core/tensor_parallel/layers.py", line 342, in forward
    output = torch.matmul(total_input, weight.t())
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`
Traceback (most recent call last):

**Comment by QwQxwqQwQ** [comment]
I'm having the same issue. How do you solve this problem?
