### ISSUE TITLE
[QUESTION]can not enbale --overlap-grad-reduce

### ISSUE THREAD

**Issue by hwdef** [NVIDIA/Megatron-LM#558]
## environments:
2 nodes
8 GPU each node
TP 1
PP 1
DP 16 == world_size
nvidia A100

## Problem:
 
When I enable `--overlap-grad-reduce`, the program will break.

```
Traceback (most recent call last):
  File "/data/edward/Megatron-LM/pretrain_gpt.py", line 187, in <module>
    pretrain(train_valid_test_datasets_provider,
  File "/data/edward/Megatron-LM/megatron/training.py", line 116, in pretrain
    model, optimizer, opt_param_scheduler = setup_model_and_optimizer(
  File "/data/edward/Megatron-LM/megatron/training.py", line 382, in setup_model_and_optimizer
    optimizer = get_megatron_optimizer(model, no_wd_decay_cond,
  File "/data/edward/Megatron-LM/megatron/optimizer/__init__.py", line 125, in get_megatron_optimizer
    return opt_ty(optimizer,
  File "/data/edward/Megatron-LM/megatron/optimizer/distrib_optimizer.py", line 397, in __init__
    self.model_gbuf_ranges.append(self.build_model_gbuf_range_map(model))
  File "/data/edward/Megatron-LM/megatron/optimizer/distrib_optimizer.py", line 190, in build_model_gbuf_range_map
    return {
  File "/data/edward/Megatron-LM/megatron/optimizer/distrib_optimizer.py", line 191, in <dictcomp>
    dtype : [cls.build_model_gbuf_range(model, dtype, bucket_index)
  File "/data/edward/Megatron-LM/megatron/optimizer/distrib_optimizer.py", line 191, in <listcomp>
    dtype : [cls.build_model_gbuf_range(model, dtype, bucket_index)
  File "/data/edward/Megatron-LM/megatron/optimizer/distrib_optimizer.py", line 149, in build_model_gbuf_range
    assert gbuf_size % data_parallel_world_size == 0, \
AssertionError: Each bucket's buffer size should be divisible by 16
```

I would like to know how to set the parameters in a reasonable way, which can be verified by the code here.

**Comment by hwdef** [comment]
@jaredcasper @deepakn94
I see you guys have submitted these codes, can you provide some help, I would appreciate it!

**Comment by deepakn94** [comment]
What is the full command-line you are using? Including model size parameters (`--hidden-size`, `--num-attention-heads`, `--num-layers`, etc.)?

**Comment by hwdef** [comment]
```shell
torchrun --nproc_per_node 8 \
    --nnodes 2 \
    --node_rank 1 \
    --master_addr <ip> \
    --master_port <port> \
    pretrain_gpt.py \
    --lr 4e-4 \
    --min-lr 2e-5 \
    --lr-decay-style cosine \
    --lr-decay-samples 43945312 \
    --lr-warmup-samples 244140 \
    --weight-decay 1e-1 \
    --optimizer adam \
    --adam-beta1 0.9 \
    --adam-beta2 0.95 \
    --adam-eps 1e-8 \
    --normalization RMSNorm \
    --tokenizer-type <self-tk> \
    --use-rotary-position-embeddings \
    --num-workers 8 \
    --seed 1234 \
    --tensor-model-parallel-size 1 \
    --pipeline-model-parallel-size 1 \
    --train-samples 48828125 \
    --num-layers 24 \
    --max-position-embeddings 2048 \
    --hidden-size 1024 \
    --num-attention-heads 16 \
    --use-distributed-optimizer \
    --seq-length 2048 \
    --micro-batch-size 7 \
    --global-batch-size 960 \
    --clip-grad 1.0 \
    --fp16 \
    --reset-position-ids \
    --reset-attention-mask \
    --eod-mask-loss \
    --swiglu \
    --no-bias-gelu-fusion \
    --ffn-hidden-size 2730 \
    --log-timers-to-tensorboard \
    --log-batch-size-to-tensorboard \
    --log-validation-ppl-to-tensorboard \
    --tensorboard-queue-size 5 \
    --data-path <data-path> \
    --tensorboard-dir <tensorboard-dir> \
    --split 950,25,25 \
    --log-interval 5 \
    --save-interval 500 \
    --eval-interval 500 \
    --eval-iters 2 \
    --distributed-backend nccl \
    --use-flash-attn \
    --overlap-grad-reduce \
    --save $CHECKPOINT_PATH \
    --load $CHECKPOINT_PATH
```

**Comment by deepakn94** [comment]
Thanks, I'll try to get back to you by the end of the week.

**Comment by deepakn94** [comment]
We have a fix for this internally, which is making its way through review. Should hopefully be pushed to Github sometime next week.

**Comment by hwdef** [comment]
> We have a fix for this internally, which is making its way through review. Should hopefully be pushed to Github sometime next week.

Thanks. Please remind me after commit.

**Comment by deepakn94** [comment]
Per-bucket padding code pushed here: https://github.com/NVIDIA/Megatron-LM/commit/443ce9f3f98fdc5a53c6b480c6e21b79944d198e. Please let me know if you run into any issues.

**Comment by hwdef** [comment]
Thank you!

**Comment by hwdef** [comment]
I will try this patch

**Comment by hwdef** [comment]
I have a new error:
```
/edward/Megatron-LM-new/megatron/optimizer/distrib_optimizer.py:429: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = bucket.data.storage()._untyped()
/edward/Megatron-LM-new/megatron/optimizer/distrib_optimizer.py:429: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = bucket.data.storage()._untyped()
setting training iterations to 87193
> learning rate decay style: cosine
 loading checkpoint from /edward/Megatron-LM/checkpoint at iteration 2500
 checkpoint version 3.0
Traceback (most recent call last):
  File "/edward/Megatron-LM-new/pretrain_gpt.py", line 230, in <module>
    pretrain(train_valid_test_datasets_provider,
  File "/edward/Megatron-LM-new/megatron/training.py", line 118, in pretrain
    model, optimizer, opt_param_scheduler = setup_model_and_optimizer(
  File "/edward/Megatron-LM-new/megatron/training.py", line 393, in setup_model_and_optimizer
    args.iteration = load_checkpoint(model, optimizer, opt_param_scheduler)
  File "/edward/Megatron-LM-new/megatron/checkpointing.py", line 611, in load_checkpoint
    optimizer.load_parameter_state(optim_checkpoint_name)
  File "/edward/Megatron-LM-new/megatron/optimizer/distrib_optimizer.py", line 739, in load_parameter_state
    world_tensor = loaded_state[model_idx][dtype][key][bucket_idx]
IndexError: list index out of range
lixin26-code-gen-master-0:16947:17791 [6] NCCL INFO [Service thread] Connection closed by localRank 0
lixin26-code-gen-master-0:16943:17784 [2] NCCL INFO [Service thread] Connection closed by localRank 0
lixin26-code-gen-master-0:16945:17787 [4] NCCL INFO [Service thread] Connection closed by localRank 0
Traceback (most recent call last):
  File "/edward/Megatron-LM-new/pretrain_gpt.py", line 230, in <module>
Traceback (most recent call last):
  File "/edward/Megatron-LM-new/pretrain_gpt.py", line 230, in <module>
    pretrain(train_valid_test_datasets_provider,
  File "/edward/Megatron-LM-new/megatron/training.py", line 118, in pretrain
    pretrain(train_valid_test_datasets_provider,
  File "/edward/Megatron-LM-new/megatron/training.py", line 118, in pretrain
    model, optimizer, opt_param_scheduler = setup_model_and_optimizer(
  File "/edward/Megatron-LM-new/megatron/training.py", line 393, in setup_model_and_optimizer
    model, optimizer, opt_param_scheduler = setup_model_and_optimizer(
  File "/edward/Megatron-LM-new/megatron/training.py", line 393, in setup_model_and_optimizer
    args.iteration = load_checkpoint(model, optimizer, opt_param_scheduler)
  File "/edward/Megatron-LM-new/megatron/checkpointing.py", line 611, in load_checkpoint
    args.iteration = load_checkpoint(model, optimizer, opt_param_scheduler)
      File "/edward/Megatron-LM-new/megatron/checkpointing.py", line 611, in load_checkpoint
optimizer.load_parameter_state(optim_checkpoint_name)
  File "/edward/Megatron-LM-new/megatron/optimizer/distrib_optimizer.py", line 748, in load_parameter_state
Traceback (most recent call last):
  File "/edward/Megatron-LM-new/pretrain_gpt.py", line 230, in <module>
Traceback (most recent call last):
  File "/edward/Megatron-LM-new/pretrain_gpt.py", line 230, in <module>
    torch.distributed.scatter(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    optimizer.load_parameter_state(optim_checkpoint_name)
  File "/edward/Megatron-LM-new/megatron/optimizer/distrib_optimizer.py", line 748, in load_parameter_state
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 3172, in scatter
Traceback (most recent call last):
    pretrain(train_valid_test_datasets_provider,
  File "/edward/Megatron-LM-new/pretrain_gpt.py", line 230, in <module>
  File "/edward/Megatron-LM-new/megatron/training.py", line 118, in pretrain
    pretrain(train_valid_test_datasets_provider,
  File "/edward/Megatron-LM-new/megatron/training.py", line 118, in pretrain
Traceback (most recent call last):
  File "/edward/Megatron-LM-new/pretrain_gpt.py", line 230, in <module>
Traceback (most recent call last):
  File "/edward/Megatron-LM-new/pretrain_gpt.py", line 230, in <module>
        model, optimizer, opt_param_scheduler = setup_model_and_optimizer(torch.distributed.scatter(

      File "/edward/Megatron-LM-new/megatron/training.py", line 393, in setup_model_and_optimizer
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
model, optimizer, opt_param_scheduler = setup_model_and_optimizer(
  File "/edward/Megatron-LM-new/megatron/training.py", line 393, in setup_model_and_optimizer
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 3172, in scatter
        args.iteration = load_checkpoint(model, optimizer, opt_param_scheduler)work.wait()

  File "/edward/Megatron-LM-new/megatron/checkpointing.py", line 611, in load_checkpoint
RuntimeError                : args.iteration = load_checkpoint(model, optimizer, opt_param_scheduler)pretrain(train_valid_test_datasets_provider,pretrain(train_valid_test_datasets_provider,pretrain(train_valid_test_datasets_provider,[/opt/pytorch/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:534] Connection closed by peer [10.178.164.177]:5850

  File "/edward/Megatron-LM-new/megatron/checkpointing.py", line 611, in load_checkpoint
    
optimizer.load_parameter_state(optim_checkpoint_name)

  File "/edward/Megatron-LM-new/megatron/training.py", line 118, in pretrain

  File "/edward/Megatron-LM-new/megatron/training.py", line 118, in pretrain
  File "/edward/Megatron-LM-new/megatron/training.py", line 118, in pretrain
  File "/edward/Megatron-LM-new/megatron/optimizer/distrib_optimizer.py", line 748, in load_parameter_state
    model, optimizer, opt_param_scheduler = setup_model_and_optimizer(
  File "/edward/Megatron-LM-new/megatron/training.py", line 393, in setup_model_and_optimizer
    optimizer.load_parameter_state(optim_checkpoint_name)
  File "/edward/Megatron-LM-new/megatron/optimizer/distrib_optimizer.py", line 748, in load_parameter_state
    torch.distributed.scatter(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    work.wait()
RuntimeError        model, optimizer, opt_param_scheduler = setup_model_and_optimizer(    
    : args.iteration = load_checkpoint(model, optimizer, opt_param_scheduler)return func(*args, **kwargs)  File "/edward/Megatron-LM-new/megatron/training.py", line 393, in setup_model_and_optimizer
model, optimizer, opt_param_scheduler = setup_model_and_optimizer(    [/opt/pytorch/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:534] Connection closed by peer [10.178.164.177]:8583


torch.distributed.scatter(
  File "/edward/Megatron-LM-new/megatron/training.py", line 393, in setup_model_and_optimizer
  File "/edward/Megatron-LM-new/megatron/checkpointing.py", line 611, in load_checkpoint
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 3172, in scatter

  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 3172, in scatter
        args.iteration = load_checkpoint(model, optimizer, opt_param_scheduler)optimizer.load_parameter_state(optim_checkpoint_name)

  File "/edward/Megatron-LM-new/megatron/checkpointing.py", line 611, in load_checkpoint
  File "/edward/Megatron-LM-new/megatron/optimizer/distrib_optimizer.py", line 748, in load_parameter_state
    args.iteration = load_checkpoint(model, optimizer, opt_param_scheduler)
  File "/edward/Megatron-LM-new/megatron/checkpointing.py", line 611, in load_checkpoint
    optimizer.load_parameter_state(optim_checkpoint_name)
  File "/edward/Megatron-LM-new/megatron/optimizer/distrib_optimizer.py", line 748, in load_parameter_state
    optimizer.load_parameter_state(optim_checkpoint_name)
    torch.distributed.scatter(  File "/edward/Megatron-LM-new/megatron/optimizer/distrib_optimizer.py", line 748, in load_parameter_state

  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    work.wait()
RuntimeError: [/opt/pytorch/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:534] Connection closed by peer [10.178.164.177]:8583
    torch.distributed.scatter(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 3172, in scatter
        torch.distributed.scatter(return func(*args, **kwargs)

  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 3172, in scatter
    work.wait()
RuntimeError    : return func(*args, **kwargs)[/opt/pytorch/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:534] Connection closed by peer [10.178.164.177]:8583

  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 3172, in scatter
    work.wait()
RuntimeError: [/opt/pytorch/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:534] Connection closed by peer [10.178.164.177]:8583
    work.wait()
RuntimeError: [/opt/pytorch/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:534] Connection closed by peer [10.178.164.177]:8583
    work.wait()
RuntimeError: [/opt/pytorch/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:534] Connection closed by peer [10.178.164.177]:8583
[2024-01-10 03:13:37,220] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 16941) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
```

I'm a little confused, for example, I use nccl as the backend, why is there a gloo log in the log?

**Comment by deepakn94** [comment]
I think you are trying to load a checkpoint that was created using the old code (i.e., the code without buckets). Can you try to not do this? (i.e., start from a fresh initialization). You should be able to load the resulting checkpoint.

I will create a patch to make it possible to load checkpoints in the old format.

**Comment by deepakn94** [comment]
We use Gloo to collect state on the CPU when loading / saving checkpoints: https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/optimizer/distrib_optimizer.py#L705.

**Comment by hwdef** [comment]
@deepakn94 Thanks,I ran it successfully.

**Comment by hwdef** [comment]
By the way, I wonder if this parameter can reduce the occupation of GPU memory?

**Comment by deepakn94** [comment]
Which parameter? `--use-distributed-optimizer` does reduce memory usage. `--overlap-grad-reduce` shouldn't affect memory usage.

**Comment by deepakn94** [comment]
To load old checkpoints, you can use this patch (will also get this merged in eventually):

```diff
commit 639f12808d7f641764abb9eb9d368733777b05ad
Author: Deepak Narayanan <dnarayanan@nvidia.com>
Date:   Fri Nov 10 11:08:25 2023 -0800

    Make checkpoint loading somewhat backwards compatible

    If current run only creates one bucket, then it is possible to load an old
    checkpoint. If current run uses --overlap-grad-reduce and splits the GradBuffer
    into multiple buckets, then an AssertionError is thrown

diff --git a/megatron/optimizer/distrib_optimizer.py b/megatron/optimizer/distrib_optimizer.py
index 9875d192d..50eb385a6 100644
--- a/megatron/optimizer/distrib_optimizer.py
+++ b/megatron/optimizer/distrib_optimizer.py
@@ -736,7 +736,14 @@ class DistributedOptimizer(MixedPrecisionOptimizer):

                         # Scatter tensor list.
                         if data_parallel_rank == 0:
-                            world_tensor = loaded_state[model_idx][dtype][key][bucket_idx]
+                            world_tensor_for_all_buckets = loaded_state[model_idx][dtype][key]
+                            if not isinstance(world_tensor_for_all_buckets, list):
+                                world_tensor_for_all_buckets = [world_tensor_for_all_buckets]
+                            assert bucket_idx < len(world_tensor_for_all_buckets), \
+                                (f"Trying to load state for bucket_id {bucket_idx} (out of "
+                                 f"{len(gbuf_range_map_for_all_buckets)} buckets) from checkpoint; "
+                                 f"checkpoint only has {len(world_tensor_for_all_buckets)} bucket(s)")
+                            world_tensor = world_tensor_for_all_buckets[bucket_idx]
                             gbuf_start_idxs = \
                                 list(range(0, gbuf_world_numel, gbuf_local_numel))
                             send_tensors = [world_tensor[i:(i+gbuf_local_numel)]
```

**Comment by hwdef** [comment]
Thanks for all your replay!
