### ISSUE TITLE
[BUG]ModuleNotFoundError: No module named 'transformer_engine'

### ISSUE THREAD

**Issue by janelu9** [NVIDIA/Megatron-LM#577]
```
from megatron.core.transformer.custom_layers.transformer_engine import (
  TEDotProductAttention,
  TELayerNormColumnParallelLinear,
  TERowParallelLinear,
  )
```

**Comment by deepakn94** [comment]
How are you running the code? Are you using a Docker container?

**Comment by TheRootOf3** [comment]
Hi, I'm facing the same issue running the preprocessing code natively on my machine.
CUDA 11.8
Python 3.11.5
Rocky Linux 9.2

```
python3 tools/preprocess_data.py  --input processed_afr.json \
--output-prefix my-gpt2 \
--vocab-file gpt2-vocab.json \
--tokenizer-type GPT2BPETokenizer \
--merge-file gpt2-merges.txt \
--append-eod
```

results in 

```
Zarr-based strategies will not be registered because of missing packages
Traceback (most recent call last):
  File "/home/aszablew/multilingual-llms-experiments/Megatron-LM/tools/preprocess_data.py", line 23, in <module>
    from megatron.tokenizer import build_tokenizer
  File "/home/aszablew/multilingual-llms-experiments/Megatron-LM/megatron/__init__.py", line 15, in <module>
    from .initialize  import initialize_megatron
  File "/home/aszablew/multilingual-llms-experiments/Megatron-LM/megatron/initialize.py", line 18, in <module>
    from megatron.arguments import parse_args, validate_args
  File "/home/aszablew/multilingual-llms-experiments/Megatron-LM/megatron/arguments.py", line 16, in <module>
    from megatron.core.models.retro import RetroConfig
  File "/home/aszablew/multilingual-llms-experiments/Megatron-LM/megatron/core/models/retro/__init__.py", line 4, in <module>
    from .decoder_spec import get_retro_decoder_block_spec
  File "/home/aszablew/multilingual-llms-experiments/Megatron-LM/megatron/core/models/retro/decoder_spec.py", line 5, in <module>
    from megatron.core.models.gpt.gpt_layer_specs import (
  File "/home/aszablew/multilingual-llms-experiments/Megatron-LM/megatron/core/models/gpt/__init__.py", line 1, in <module>
    from .gpt_model import GPTModel
  File "/home/aszablew/multilingual-llms-experiments/Megatron-LM/megatron/core/models/gpt/gpt_model.py", line 15, in <module>
    from megatron.core.transformer.transformer_block import TransformerBlock
  File "/home/aszablew/multilingual-llms-experiments/Megatron-LM/megatron/core/transformer/transformer_block.py", line 13, in <module>
    from megatron.core.transformer.custom_layers.transformer_engine import TENorm
  File "/home/aszablew/multilingual-llms-experiments/Megatron-LM/megatron/core/transformer/custom_layers/transformer_engine.py", line 6, in <module>
    import transformer_engine as te
ModuleNotFoundError: No module named 'transformer_engine'
```

I'd really appreciate some support with it! Thanks!

**Comment by deepakn94** [comment]
You need TransformerEngine too. Is it possible for you to use a docker container? For example, our code should work with this PyTorch container: https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel-23-04.html.

**Comment by TheRootOf3** [comment]
Thank you @deepakn94. I'm afraid I won't be able to use the docker container due to some limitations of the shared system I'm using. 
In this case, would it help to install TransformerEngine following:  https://docs.nvidia.com/deeplearning/transformer-engine/user-guide/installation.html ?

**Comment by deepakn94** [comment]
Yes, we have done some testing of the latest TE release (https://github.com/nvidia/transformerEngine/tree/release_v1.1) with our `main` branch, so I recommend trying that.

**Comment by TheRootOf3** [comment]
Thanks, will give it a go! 🚀

**Comment by TheRootOf3** [comment]
I managed to run the docker container with singularity. Works perfectly fine - thanks again!

**Comment by deepakn94** [comment]
Ok, great! Going to close this.

**Comment by janelu9** [comment]
who can share a wheel installation package here?
