### ISSUE TITLE
Invalid config blocking attribute value -2147483648[QUESTION]

### ISSUE THREAD

**Issue by lushizijizoude** [NVIDIA/Megatron-LM#596]
When I switched the model from distributed training to single-machine training, I encountered the following error:
```shell
Building extension module rotary_pos_emb_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module rotary_pos_emb_cuda...
dsw-226-64b7566f8b-xz9j6:71868:71868 [0] NCCL INFO Bootstrap : Using eth0:10.207.8.104<0>
dsw-226-64b7566f8b-xz9j6:71868:71868 [0] NCCL INFO Plugin name set by env to libnccl-net-none.so
dsw-226-64b7566f8b-xz9j6:71868:71868 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net-none.so), using internal implementation

dsw-226-64b7566f8b-xz9j6:71868:71868 [0] init.cc:1270 NCCL WARN Invalid config blocking attribute value -2147483648
Traceback (most recent call last):
  File "scripts/sft_gpt.py", line 151, in <module>
    sft(
  File "/cpfs/2926428ee2463e44/user/xinghai/eas/infer/7b/Project-ACE/ace/sft/training.py", line 60, in sft
    initialize_megatron(
  File "/cpfs/2926428ee2463e44/user/xinghai/eas/infer/7b/Megatron-LM-agi-33b/megatron/initialize.py", line 82, in initialize_megatron
    _compile_dependencies()
  File "/cpfs/2926428ee2463e44/user/xinghai/eas/infer/7b/Megatron-LM-agi-33b/megatron/initialize.py", line 131, in _compile_dependencies
    torch.distributed.barrier()
  File "/cpfs/2926428ee2463e44/user/xinghai/opt/miniconda/envs/py38/lib/python3.8/site-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/cpfs/2926428ee2463e44/user/xinghai/opt/miniconda/envs/py38/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 3696, in barrier
    work = default_pg.barrier(opts=opts)
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/NCCLUtils.hpp:219, invalid argument, NCCL version 2.14.3
ncclInvalidArgument: Invalid value for an argument.
Last error:
Invalid config blocking attribute value -2147483648
[2023-11-19 03:09:25,027] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 71868) of binary: /cpfs/2926428ee2463e44/user/xinghai/opt/miniconda/envs/py38/bin/python
Traceback (most recent call last):
  File "/cpfs/2926428ee2463e44/user/xinghai/opt/miniconda/envs/py38/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/cpfs/2926428ee2463e44/user/xinghai/opt/miniconda/envs/py38/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/cpfs/2926428ee2463e44/user/xinghai/opt/miniconda/envs/py38/lib/python3.8/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/cpfs/2926428ee2463e44/user/xinghai/opt/miniconda/envs/py38/lib/python3.8/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/cpfs/2926428ee2463e44/user/xinghai/opt/miniconda/envs/py38/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/cpfs/2926428ee2463e44/user/xinghai/opt/miniconda/envs/py38/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
scripts/sft_gpt.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-19_03:09:25
  host      : dsw-226-64b7566f8b-xz9j6
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 71868)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by deepakn94** [comment]
How are you running single-node training?
