### ISSUE TITLE
[QUESTION] CUDA OOM error when finetuning LLAMA2-7b with A100 40G and seq_length 64.

### ISSUE THREAD

**Issue by SefaZeng** [NVIDIA/Megatron-LM#606]
**Your question**
Ask a clear and concise question about Megatron-LM.
I try to follow the scripts for fine-tune LLAMA. So I convert the HF format checkpoint to megatron format. Then this is my fine-tune scripts:
```
TP=1
PP=1
 
GPUS_PER_NODE=8
NODE_RANK=$RANK
export LOCAL_RANK=$RANK
NNODES=${WORLD_SIZE}
 
#export NCCL_SOCKET_IFNAME=eth,en,em,bond
export NCCL_SOCKET_IFNAME=bond1
export TORCH_DISTRIBUTED_DEBUG=OFF #INFO
export NCCL_DEBUG=
export CUDA_LAUNCH_BLOCKING=1
#export LD_LIBRARY_PATH=/usr/local/nccl/lib:$LD_LIBRARY_PATH
export TRANSFORMERS_CACHE=$WORK_PATH/cache
export PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:32
export PYTHONPATH=${TOOL_PATH}:${PYTHONPATH}
export OMP_NUM_THREADS=20
export NCCL_IB_GID_INDEX=3
export NCCL_ASYNC_ERROR_HANDLING=1
export CUDA_DEVICE_MAX_CONNECTIONS=1
 
# 7 B
HIDDEN_SIZE=4096 # e.g. llama-13b: 5120
FFN_HIDDEN_SIZE=11008 # e.g. llama-13b: 13824
NUM_LAYERS=32 # e.g. llama-13b: 40
NUM_HEADS=32 # e.g. llama-13b: 40
SEQ_LENGTH=64
NUM_KV_HEADS=32 # llama2 70B uses GQA
 
MICRO_BATCH_SIZE=1
GLOBAL_BATCH_SIZE=8 
TRAIN_STEPS=2 
LR=3e-4
MIN_LR=3e-5
LR_WARMUP_STEPS=1
WEIGHT_DECAY=0.1
GRAD_CLIP=1

torchrun $DISTRIBUTED_ARGS \
       ${CODE_PATH}/pretrain_gpt.py \
       --tensor-model-parallel-size $TP \
       --pipeline-model-parallel-size $PP \
       --num-layers $NUM_LAYERS \
       --hidden-size $HIDDEN_SIZE \
       --ffn-hidden-size $FFN_HIDDEN_SIZE \
       --num-attention-heads $NUM_HEADS \
       --micro-batch-size $MICRO_BATCH_SIZE \
       --global-batch-size $GLOBAL_BATCH_SIZE \
       --seq-length $SEQ_LENGTH \                                                                                                                                                              
       --max-position-embeddings $SEQ_LENGTH \
       --train-iters $TRAIN_STEPS \
       --save $CHECKPOINT_PATH \
       --load $PREMODEL \
       --train-data-path $DATASET \
       --valid-data-path $DATASET_VALID \
       --distributed-backend nccl \
       --lr $LR \
       --lr-decay-style cosine \
       --min-lr $MIN_LR \
       --weight-decay $WEIGHT_DECAY \
       --clip-grad $GRAD_CLIP \
       --lr-warmup-iters $LR_WARMUP_STEPS \
       --optimizer adam \
       --adam-beta1 0.9 \
       --adam-beta2 0.95 \
       --log-interval 1 \ 
       --save-interval 1 \ 
       --eval-interval 10000000 \
       --eval-iters 1000 \
       --tokenizer-type Llama2Tokenizer \
       --tokenizer-model ${TOKENIZER_PATH} \
       --exit-on-missing-checkpoint \
       --use-checkpoint-args \
       --no-load-optim \
       --no-load-rng \
       --fp16 \
       --untie-embeddings-and-output-weights \
       --use-rotary-position-embeddings \
       --normalization RMSNorm \
       --no-position-embedding \
       --no-masked-softmax-fusion \
       --use-flash-attn \
       --make-vocab-size-divisible-by 512
```
and this last several lines of  log:
```
2023-11-26T14:15:35.547888511Z INFO:megatron.core.distributed.grad_buffer:    module.language_model.encoder.layers.25.post_attention_norm.weight
2023-11-26T14:15:35.547898149Z INFO:megatron.core.distributed.grad_buffer:    module.language_model.encoder.layers.16.mlp.dense_4h_to_h.weight
2023-11-26T14:15:35.547927875Z INFO:megatron.core.distributed.grad_buffer:    module.language_model.encoder.layers.12.input_norm.weight
2023-11-26T14:15:35.547934518Z INFO:megatron.core.distributed.grad_buffer:    module.language_model.encoder.layers.6.self_attention.query_key_value.weight
2023-11-26T14:15:35.547936632Z INFO:megatron.core.distributed.grad_buffer:    module.language_model.encoder.layers.1.self_attention.query_key_value.weight
2023-11-26T14:15:35.969218289Z Traceback (most recent call last):
2023-11-26T14:15:35.969235181Z   File "/Megatron-LM-git/pretrain_gpt.py", line 230, in <module>
2023-11-26T14:15:35.970025202Z     pretrain(train_valid_test_datasets_provider,
2023-11-26T14:15:35.970047654Z   File "/Megatron-LM-git/megatron/training.py", line 118, in pretrain
2023-11-26T14:15:35.970538099Z     model, optimizer, opt_param_scheduler = setup_model_and_optimizer(
2023-11-26T14:15:35.970548109Z   File "Megatron-LM-git/megatron/training.py", line 386, in setup_model_and_optimizer
2023-11-26T14:15:35.970944406Z     optimizer = get_megatron_optimizer(model, no_wd_decay_cond,
2023-11-26T14:15:35.970952391Z   File "/Megatron-LM-git/megatron/optimizer/__init__.py", line 125, in get_megatron_optimizer
2023-11-26T14:15:35.972337735Z     return opt_ty(optimizer,
2023-11-26T14:15:35.972344188Z   File "/Megatron-LM-git/megatron/optimizer/optimizer.py", line 412, in __init__
2023-11-26T14:15:35.973971719Z     main_param = param.detach().clone().float()
2023-11-26T14:15:35.973976198Z torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 192.00 MiB. GPU 7 has a total capacty of 39.59 GiB of which 176.19 MiB is free. Process 3153921 has 39.41 GiB memory in use. Of the allocated memory 37.56 GiB is allocated by PyTorch, and 1.49 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
I think this is not right. As fine-tune LLAMA2-7B with only seq_length 64 using transformers works well.

**Comment by CaesarWWK** [comment]
world_size in Megatron_lm equals to node*gpu per node.  I have the same problem using your script and fix it by changing the world size
