### ISSUE TITLE
[QUESTION] Failed to run megatron vit. pretrain_vision_classify.sh:  TypeError: init() got an unexpected keyword argument 'post_layer_norm

### ISSUE THREAD

**Issue by shiyandong** [NVIDIA/Megatron-LM#614]
***Your question***   The environment I use is nvcr.io/nvidia/pytorch:20.04-py3 official image, and I can also run gpt, bert. But when I run vit it fails.**TypeError: init() got an unexpected keyword argument 'post_layer_norm**.please help me, thank you very much！

***log***：
root@9f358e0ab58c:/workspace/Megatron-LM# bash examples/pretrain_vision_classify.sh 
Zarr-based strategies will not be registered because of missing packages
using world size: 1, data-parallel-size: 1, tensor-model-parallel size: 1, pipeline-model-parallel size: 1 
WARNING: overriding default arguments for vision_pretraining:True                        with vision_pretraining:False
using torch.float16 for parameters ...
------------------------ arguments ------------------------
setting number of micro-batches to constant 256
> building NullTokenizer tokenizer ...
 > padded vocab (size: 1) with 127 dummy tokens (new size: 128)
> initializing torch distributed ...
> initialized tensor model parallel with size 1
> initialized pipeline model parallel with size 1
> setting random seeds to 1234 ...
> compiling dataset index builder ...
make: Entering directory '/workspace/Megatron-LM/megatron/data'
make: Nothing to be done for 'default'.
make: Leaving directory '/workspace/Megatron-LM/megatron/data'
>>> done with dataset index builder. Compilation time: 0.174 seconds
> compiling and loading fused kernels ...
>>> done with compiling and loading fused kernels. Compilation time: 1.699 seconds
[GPU:0],allreduce-here,torch.Size([1]) 
time to initialize megatron (seconds): 3.106
[after megatron is initialized] datetime: 2023-12-04 07:32:40 
building VIT model ...
Traceback (most recent call last):
  File "pretrain_vision_classify.py", line 99, in <module>
    pretrain(
  File "/workspace/Megatron-LM/megatron/training.py", line 114, in pretrain
    model, optimizer, opt_param_scheduler = setup_model_and_optimizer(
  File "/workspace/Megatron-LM/megatron/training.py", line 377, in setup_model_and_optimizer
    model = get_model(model_provider_func, model_type)
  File "/workspace/Megatron-LM/megatron/training.py", line 261, in get_model
    model = model_provider_func(
  File "pretrain_vision_classify.py", line 25, in model_provider
    model = VitClassificationModel(config=config,
  File "/workspace/Megatron-LM/megatron/model/vision/classification.py", line 27, in __init__
    self.backbone = VitBackbone(
  File "/workspace/Megatron-LM/megatron/model/vision/vit_backbone.py", line 199, in __init__
    self.transformer = ParallelTransformer(
***TypeError: __init__() got an unexpected keyword argument 'post_layer_norm'***
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 123086) of binary: /opt/conda/bin/python

***pretrain_vision_classify.sh***
#! /bin/bash

export CUDA_DEVICE_MAX_CONNECTIONS=1
export NCCL_IB_SL=1

DATA_PATH_TRAIN=/workspace/Megatron-LM/train_data
DATA_PATH_VAL=/workspace/Megatron-LM/val_data

##CHECKPOINT_PATH=<Specify path>

CLASSIFIER_ARGS="
   	   --tensor-model-parallel-size 1 \
        --num-layers 12 \
        --hidden-size 768 \
        --num-attention-heads 12 \
        --patch-dim 4 \
        --seq-length 3136 \
        --max-position-embeddings 3136 \
        --img-h 224 \
        --img-w 224 \
        --mask-factor 1.0 \
        --fp16 \
        --train-iters 750000 \
        --lr-decay-style cosine \
        --micro-batch-size 4 \
        --global-batch-size 1024 \
        --lr 0.0005 \
        --min-lr 0.00001 \
        --attention-dropout 0.0 \
        --weight-decay 0.05 \
        --lr-warmup-iters 12500 \
        --clip-grad 1.0 \
        --no-gradient-accumulation-fusion \
        --num-workers 4     
     
"

##--DDP-impl torch 

DATA_ARGS="
     --tokenizer-type NullTokenizer \
     --vocab-size 0 \
     --data-path $DATA_PATH_TRAIN $DATA_PATH_VAL \
     --no-data-sharding \
     --split 8,1,1 
"

OUTPUT_ARG="
     --log-interval 1 \
     --save-interval 10000 \
     --eval-interval 2500 \
     --eval-iters 1 \
"

##--tensorboard-dir ${CHECKPOINT_PATH} \

torchrun pretrain_vision_classify.py \
     $CLASSIFIER_ARGS \
     $DATA_ARGS \
     $OUTPUT_ARGS \
     #--save $CHECKPOINT_PATH \
     #--load $CHECKPOINT_PATH

***env***
root@9f358e0ab58c:/workspace/Megatron-LM# python -m torch.utils.collect_env 
Collecting environment information...
PyTorch version: 1.12.0a0+bd13bc6
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: version 3.22.3
Libc version: glibc-2.31

Python version: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-166-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.6.124
GPU models and configuration: 
GPU 0: NVIDIA GeForce GTX 1080 Ti
GPU 1: NVIDIA GeForce GTX 1080 Ti
GPU 2: NVIDIA GeForce GTX 1080 Ti
GPU 3: NVIDIA GeForce GTX 1080 Ti

Nvidia driver version: 535.129.03

**Comment by linkedqueue** [comment]
Have you solved this problem, I met the same problem. Thanks for any reply

**Comment by Eugene29** [comment]
Hi, what you need is to change vit_backbone.py:
```
        self.transformer = ParallelTransformer(
            config,
            model_type=args.model_type,
            pre_process=self.pre_process,
            post_process=self.post_process,
            post_norm=self.post_layer_norm,  INSTEAD OF: post_layer_norm=self.post_layer_norm,
            drop_path_rate=self.drop_path_rate
        )
```
