### ISSUE TITLE
[BUG] checkpoint saved on two nodes cannot be loaded on three nodes, but it can be loaded on four nodes.

### ISSUE THREAD

**Issue by lzyubermensch** [NVIDIA/Megatron-LM#659]
**Describe the bug**
I encountered a bug while using distributed optimizer on Megatron main branch. After training with two nodes(16 GPU cards) and saving the checkpoints, I attempted to load the same checkpoints on three nodes(24 GPU cards), but an error occurred. However, loading the checkpoints with four nodes(32 GPU cards) worked without any issues.

**To Reproduce**
1.  Train with two nodes(16 GPU cards) on Megatron main branch with the parameters(TP = 1, PP =1, use-distributed-optimizer=True, overlap-param-gather=True, overlap-grad-reduce=True, accumulate_allreduce_grads_in_fp32=True).
2. Save the checkpoints after training.
3. Load the same checkpoints on three nodes(24 GPU cards) with the same parameters(TP = 1, PP =1, use-distributed-optimizer=True, overlap-param-gather=True, overlap-grad-reduce=True, accumulate_allreduce_grads_in_fp32=True).
4. Load the same checkpoints on four nodes(32 GPU cards) with the same parameters(TP = 1, PP =1, use-distributed-optimizer=True, overlap-param-gather=True, overlap-grad-reduce=True, accumulate_allreduce_grads_in_fp32=True).

**Expected behavior**
The checkpoint should be loadable and runnable on any number of machines.

**Stack trace/logs**

> Traceback (most recent call last):
  File "/megatron/code/Megatron-LM/megatron/checkpointing.py", line 611, in load_checkpoint
    optimizer.load_parameter_state(optim_checkpoint_name)
  File "/megatron/code/Megatron-LM/megatron/optimizer/distrib_optimizer.py", line 755, in load_parameter_state
    assert self.per_bucket_numel == per_bucket_numel_in_checkpoint, \
AssertionError: Number of elements in each bucket need to be the same in current run ([{torch.float32: [44576784, 89150736, 67133448, 44576784, 89150736, 67133448, 44576784, 89150736, 67133448, 44576784, 89150736, 67133448, 206053392]}]) and checkpoint ([{torch.float32: [44576768, 89150720, 67133440, 44576768, 89150720, 67133440, 44576768, 89150720, 67133440, 44576768, 89150720, 67133440, 206053376]}])

**Environment (please complete the following information):**
 - Megatron-LM commit ID: bcce6f54e075e3c3374ea67adefe54f3f2da2b07 (main branch)
 - PyTorch version: py310
 - CUDA version: cu121

**Proposed fix**
It seems like a grad_buffer issue caused by DistributedDataParallel(MegatronModule).

**Comment by lzyubermensch** [comment]
@deepakn94 Maybe you can help me, thanks!

**Comment by sbhavani** [comment]
Problem with loading distributed optimizer checkpoints on a different number of GPUs was resolved in https://github.com/NVIDIA/Megatron-LM/commit/93f80155eb778428a491cbee2951d43bf348aa5e which implements arbitrary parallelism resharding for DistOpt when using fully reshardable checkpoint formats.
