### ISSUE TITLE
Error running bert pretraining example

### ISSUE THREAD

**Issue by pritamdamania87** [NVIDIA/Megatron-LM#67]
I'm using the following data for my-corpus.json (as demonstrated in the README):

```
{"src": "www.nvidia.com", "text": "The quick brown fox", "type": "Eng", "id": "0", "title": "First Part"}
{"src": "The Internet", "text": "jumps over the lazy dog", "type": "Eng", "id": "42", "title": "Second Part"}
```

pre-processing the data as follows:

```
python tools/preprocess_data.py \
       --input my-corpus.json \
       --output-prefix my-bert \
       --vocab bert-vocab.txt \
       --dataset-impl mmap \
       --tokenizer-type BertWordPieceLowerCase \
       --split-sentences
```

And running the training script as follows (again from README):

```
CHECKPOINT_PATH=checkpoints/bert_345m
VOCAB_FILE=bert-vocab.txt
DATA_PATH=my-bert_text_sentence

BERT_ARGS="--num-layers 24 \
           --hidden-size 1024 \
           --num-attention-heads 16 \
           --seq-length 512 \
           --max-position-embeddings 512 \
           --lr 0.0001 \
           --lr-decay-iters 990000 \
           --train-iters 2000000 \
           --min-lr 0.00001 \
           --lr-warmup-fraction 0.01 \
	   --micro-batch-size 4 \	   
           --global-batch-size 8 \
           --vocab-file $VOCAB_FILE \
           --split 949,50,1 \
           --fp16"

OUTPUT_ARGS="--log-interval 10 \
             --save-interval 500 \
             --eval-interval 100 \
             --eval-iters 10 \
             --checkpoint-activations"

python pretrain_bert.py \
       $BERT_ARGS \
       $OUTPUT_ARGS \
       --save $CHECKPOINT_PATH \
       --load $CHECKPOINT_PATH \
       --data-path $DATA_PATH
```

Although, I run into the following error during training:

```
Traceback (most recent call last):
  File "pretrain_bert.py", line 155, in <module>
    args_defaults={'tokenizer_type': 'BertWordPieceLowerCase'})
  File "/data/users/pritam/Megatron-LM/megatron/training.py", line 116, in pretrain
    train_valid_test_dataset_provider)
  File "/data/users/pritam/Megatron-LM/megatron/training.py", line 1000, in build_train_valid_test_data_iterators
    valid_ds, args.consumed_valid_samples)
  File "/data/users/pritam/Megatron-LM/megatron/data/data_loaders.py", line 38, in build_pretraining_data_loader
    data_parallel_size=mpu.get_data_parallel_world_size())
  File "/data/users/pritam/Megatron-LM/megatron/data/data_loaders.py", line 62, in __init__
    'no sample to consume: {}'.format(self.total_samples)
AssertionError: no sample to consume: 0
```

Full log: https://gist.github.com/pritamdamania87/7141eadd162ba672b465a7920e62508e

**Comment by jaredcasper** [comment]
With only two sentences in your data set there isn't enough for a train/valid/test set, so you need to add more data or change the --split argument to something like `99,1,0` or something? You'll want to look at the " > dataset split:" part of the output, make sure there is data in the training and eval set.

**Comment by Lavenderjiang** [comment]
> With only two sentences in your data set there isn't enough for a train/valid/test set, so you need to add more data or change the --split argument to something like `99,1,0` or something? You'll want to look at the " > dataset split:" part of the output, make sure there is data in the training and eval set.

I tried with a dataset with ~900 samples, but still encountered the error. Here's my output

```
dataset split:
    train:
     document indices in [0, 726) total of 726 documents
     sentence indices in [0, 726) total of 726 sentences
    validation:
     document indices in [726, 817) total of 91 documents
     sentence indices in [726, 817) total of 91 sentences
    test:
     document indices in [817, 908) total of 91 documents
     sentence indices in [817, 908) total of 91 sentences
 loading indexed mapping from my-bert_text_sentence_train_indexmap_160mns_509msl_0.10ssp_1234s.npy
    loaded indexed file in 0.001 seconds
    total number of samples: 0
  loading indexed mapping from my-bert_text_sentence_valid_indexmap_240mns_509msl_0.10ssp_1234s.npy
    loaded indexed file in 0.001 seconds
    total number of samples: 0
  loading indexed mapping from my-bert_text_sentence_test_indexmap_80mns_509msl_0.10ssp_1234s.npy
    loaded indexed file in 0.000 seconds
    total number of samples: 0
finished creating BERT datasets ...
```
