### ISSUE TITLE
[BUG] TypeError: FastLayerNormFN.forward() missing 1 required positional argument: 'memory_efficient'

### ISSUE THREAD

**Issue by GSSBMW** [NVIDIA/Megatron-LM#677]
**Describe the bug**
Follow the steps of readme to run pretrain of gpt 345M model. But give error 
`TypeError: FastLayerNormFN.forward() missing 1 required positional argument: 'memory_efficient'`

**To Reproduce**
Follow the step of readme.

**Stack trace/logs**
[before the start of training step] datetime: 2024-01-24 05:41:28 
```
Traceback (most recent call last):
  File "/home/sanshang/021_debug/megatron-lm/pretrain_gpt.py", line 198, in <module>
    pretrain(train_valid_test_datasets_provider,
  File "/home/sanshang/021_debug/megatron-lm/megatron/training.py", line 246, in pretrain
    iteration, num_floating_point_operations_so_far = train(
  File "/home/sanshang/021_debug/megatron-lm/megatron/training.py", line 908, in train
    train_step(forward_step_func,
  File "/home/sanshang/021_debug/megatron-lm/megatron/training.py", line 517, in train_step
    losses_reduced = forward_backward_func(
  File "/home/sanshang/021_debug/megatron-lm/megatron/core/pipeline_parallel/schedules.py", line 343, in forward_backward_no_pipelining
    output_tensor = forward_step(
  File "/home/sanshang/021_debug/megatron-lm/megatron/core/pipeline_parallel/schedules.py", line 191, in forward_step
    output_tensor, loss_func = forward_step_func(data_iterator, model)
  File "/home/sanshang/021_debug/megatron-lm/pretrain_gpt.py", line 145, in forward_step
    output_tensor = model(tokens, position_ids, attention_mask,
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1519, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sanshang/021_debug/megatron-lm/megatron/core/distributed/distributed_data_parallel.py", line 136, in forward
    return self.module(*inputs, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1519, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sanshang/021_debug/megatron-lm/megatron/model/module.py", line 185, in forward
    outputs = self.module(*inputs, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1519, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sanshang/021_debug/megatron-lm/megatron/model/gpt_model.py", line 82, in forward
    lm_output = self.language_model(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1519, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sanshang/021_debug/megatron-lm/megatron/model/language_model.py", line 493, in forward
    encoder_output = self.encoder(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1519, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sanshang/021_debug/megatron-lm/megatron/model/transformer.py", line 1776, in forward
    hidden_states = layer(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1519, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sanshang/021_debug/megatron-lm/megatron/model/transformer.py", line 1159, in forward
    norm_output = self.input_norm(hidden_states)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1519, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sanshang/021_debug/megatron-lm/megatron/model/fused_layer_norm.py", line 86, in forward
    output = FastLayerNormFN.apply(input, weight, self.bias, self.eps)
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/function.py", line 551, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
TypeError: FastLayerNormFN.forward() missing 1 required positional argument: 'memory_efficient'
```

**Environment (please complete the following information):**
 - Megatron-LM commit ID: 2c3468a49ed51324ae9b442e0d88416f1b29422b
 - Container: nvcr.io#nvidia/pytorch:23.12-py3
 - PyTorch version: 2.2.0a0+81ea7a4
 - CUDA version: Cuda compilation tools, release 12.3, V12.3.107, given by `nvcc --version`
 - NCCL version: 2.19.3
 - Python: 3.10.12

**Proposed fix**
If you have a proposal for how to fix the issue state it here or link to a PR.

**Additional context**

**Comment by HenryHTH2020** [comment]
I encountered a similar problem. 
My error is reported as:
TypeError: forward() missing 1 required positional argument: 'memory_efficient'




```
Traceback (most recent call last):
  File "/fs1/home/huangth/git_dir/Megatron-LM/pretrain_gpt.py", line 204, in <module>
    pretrain(train_valid_test_datasets_provider,
  File "/fs1/home/huangth/git_dir/Megatron-LM/megatron/training.py", line 162, in pretrain
    iteration = train(forward_step_func,
  File "/fs1/home/huangth/git_dir/Megatron-LM/megatron/training.py", line 740, in train
    train_step(forward_step_func,
  File "/fs1/home/huangth/git_dir/Megatron-LM/megatron/training.py", line 424, in train_step
    losses_reduced = forward_backward_func(
  File "/fs1/home/huangth/git_dir/Megatron-LM/megatron/core/pipeline_parallel/schedules.py", line 368, in forward_backward_no_pipelining
    output_tensor = forward_step(
  File "/fs1/home/huangth/git_dir/Megatron-LM/megatron/core/pipeline_parallel/schedules.py", line 193, in forward_step
    output_tensor, loss_func = forward_step_func(data_iterator, model)
  File "/fs1/home/huangth/git_dir/Megatron-LM/pretrain_gpt.py", line 167, in forward_step
    output_tensor = model(tokens, position_ids, attention_mask,
  File "/fs1/home/huangth/.conda/envs/torch13/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/fs1/home/huangth/.conda/envs/torch13/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1529, in _call_impl
    return forward_call(*args, **kwargs)
  File "/fs1/home/huangth/git_dir/Megatron-LM/megatron/core/distributed.py", line 289, in forward
    return self.module(*inputs, **kwargs)
  File "/fs1/home/huangth/.conda/envs/torch13/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/fs1/home/huangth/.conda/envs/torch13/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1529, in _call_impl
    return forward_call(*args, **kwargs)
  File "/fs1/home/huangth/git_dir/Megatron-LM/megatron/model/module.py", line 181, in forward
    outputs = self.module(*inputs, **kwargs)
  File "/fs1/home/huangth/.conda/envs/torch13/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/fs1/home/huangth/.conda/envs/torch13/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1529, in _call_impl
    return forward_call(*args, **kwargs)
  File "/fs1/home/huangth/git_dir/Megatron-LM/megatron/model/gpt_model.py", line 82, in forward
    lm_output = self.language_model(
  File "/fs1/home/huangth/.conda/envs/torch13/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/fs1/home/huangth/.conda/envs/torch13/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1529, in _call_impl
    return forward_call(*args, **kwargs)
  File "/fs1/home/huangth/git_dir/Megatron-LM/megatron/model/language_model.py", line 487, in forward
    encoder_output = self.encoder(
  File "/fs1/home/huangth/.conda/envs/torch13/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/fs1/home/huangth/.conda/envs/torch13/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1529, in _call_impl
    return forward_call(*args, **kwargs)
  File "/fs1/home/huangth/git_dir/Megatron-LM/megatron/model/transformer.py", line 1747, in forward
    hidden_states = layer(
  File "/fs1/home/huangth/.conda/envs/torch13/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/fs1/home/huangth/.conda/envs/torch13/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1529, in _call_impl
    return forward_call(*args, **kwargs)
  File "/fs1/home/huangth/git_dir/Megatron-LM/megatron/model/transformer.py", line 1132, in forward
    norm_output = self.input_norm(hidden_states)
  File "/fs1/home/huangth/.conda/envs/torch13/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/fs1/home/huangth/.conda/envs/torch13/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1529, in _call_impl
    return forward_call(*args, **kwargs)
  File "/fs1/home/huangth/git_dir/Megatron-LM/megatron/model/fused_layer_norm.py", line 84, in forward
    return FusedLayerNormAffineFunction.apply(input, weight, self.bias, self.normalized_shape, self.eps)
  File "/fs1/home/huangth/.conda/envs/torch13/lib/python3.9/site-packages/torch/autograd/function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
TypeError: forward() missing 1 required positional argument: 'memory_efficient'
[2024-01-26 11:11:23,747] torch.distributed.elastic.multiprocessing.api: [ERROR] failed
```

**Comment by GSSBMW** [comment]
I think the team already has one MR in review to fix it.

**Comment by Azure-Tang** [comment]
yeah I encountered the same problem too today:

```
TypeError: FastLayerNormFN.forward() missing 1 required positional argument: 'memory_efficient'
    return forward_call(*args, **kwargs)
  File "/workspace/azy-sxf/Megatron-LM/megatron/model/module.py", line 194, in forward
    outputs = self.module(*inputs, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1519, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/azy-sxf/Megatron-LM/megatron/model/gpt_model.py", line 82, in forward
    lm_output = self.language_model(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1519, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/azy-sxf/Megatron-LM/megatron/model/language_model.py", line 501, in forward
    encoder_output = self.encoder(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1519, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/azy-sxf/Megatron-LM/megatron/model/transformer.py", line 1668, in forward
    hidden_states = layer(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1519, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/azy-sxf/Megatron-LM/megatron/model/transformer.py", line 1053, in forward
    norm_output = self.input_norm(hidden_states)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1519, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/azy-sxf/Megatron-LM/megatron/model/fused_layer_norm.py", line 86, in forward
    output = FastLayerNormFN.apply(input, weight, self.bias, self.eps)
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/function.py", line 551, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
TypeError: FastLayerNormFN.forward() missing 1 required positional argument: 'memory_efficient'
```

**Comment by Azure-Tang** [comment]
> I think the team already has one MR in review to fix it.

did you find the one?

**Comment by peiji1981** [comment]
maybe the NGC version is too new, try 23 series version

**Comment by adiprasad** [comment]
+1

**Comment by adiprasad** [comment]
Running on nvcr.io/nvidia/pytorch:23.05-py3 resolved it for me

**Comment by bodasadallah** [comment]
> Running on nvcr.io/nvidia/pytorch:23.05-py3 resolved it for me

That Solved it for me as well!

**Comment by GSSBMW** [comment]
This issue should have been resolved. Close.
