### ISSUE TITLE
PyTorch 1.2 support?

### ISSUE THREAD

**Issue by jeffra** [NVIDIA/Megatron-LM#7]
I am seeing an error with PyTorch 1.2, has this been tested with Megatron?

Traceback (most recent call last):
  File "pretrain_gpt2.py", line 752, in <module>
    main()
  File "pretrain_gpt2.py", line 690, in main
    set_random_seed(args.seed)
  File "pretrain_gpt2.py", line 621, in set_random_seed
    mpu.model_parallel_cuda_manual_seed(seed)
  File "/data/users/jerasley/Megatron-LM/mpu/random.py", line 166, in model_parallel_cuda_manual_seed
    model_parallel_seed)
  File "/data/users/jerasley/Megatron-LM/mpu/random.py", line 99, in add
    _set_cuda_rng_state(orig_rng_state)
  File "/data/users/jerasley/Megatron-LM/mpu/random.py", line 49, in _set_cuda_rng_state
    _lazy_call(cb)
  File "/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py", line 139, in _lazy_call
    callable()
  File "/data/users/jerasley/Megatron-LM/mpu/random.py", line 47, in cb
    _C._cuda_setRNGState(new_state)
AttributeError: module 'torch._C' has no attribute '_cuda_setRNGState'

Is it safe in this case to just replace the _C._cuda_setRNGState call with torch.cuda.set_rng_state?

**Comment by shoeybi** [comment]
The api for the RNG state has changed in PyTorch 1.2. We will have support for the version in a later release. In the meantime, we suggest using 1.1 version.

**Comment by jaredcasper** [comment]
@jeffra Should be fixed now, let us know if the current master doesn't work.
