### ISSUE TITLE
[BUG] Cannot train model with seq_length > 1024

### ISSUE THREAD

**Issue by 1049451037** [NVIDIA/Megatron-LM#708]
For GPT training, everything works fine when I run it with --seq-length 1024. But when I change 1024 to 2048, scripts cannot run.

This is the error reported when I run `examples/pretrain_gpt_distributed_with_mp.sh` with `--use-mcore-models`, `--max-position-embeddings 2048` and `--seq-length 2048`:

```
> finished creating GPT datasets ...                                                                                                              
[after dataloaders are built] datetime: 2024-02-26 14:15:27                                                                                       
done with setup ...                                                                                                                               
(min, max) time across ranks (ms):                                                                                                                
    model-and-optimizer-setup ......................: (341.91, 359.40)                                                                            
    train/valid/test-data-iterators-setup ..........: (163.57, 333.68)                                                                            
training ...                                                                                                                                      
[before the start of training step] datetime: 2024-02-26 14:15:28                                                                                 
[rank0]: Traceback (most recent call last):                                                                                                       
[rank0]:   File "/envs//Megatron-LM/pretrain_gpt.py", line 209, in <module>                                                              
[rank0]:     pretrain(train_valid_test_datasets_provider,                                                                                         
[rank0]:   File "/envs//Megatron-LM/megatron/training.py", line 258, in pretrain                                                         
[rank0]:     iteration, num_floating_point_operations_so_far = train(                                                                             
[rank0]:   File "/envs//Megatron-LM/megatron/training.py", line 970, in train                                                            
[rank0]:     train_step(forward_step_func,                                                                                                        
[rank0]:   File "/envs//Megatron-LM/megatron/training.py", line 535, in train_step                                                       
[rank0]:     losses_reduced = forward_backward_func(                                                                                              
[rank0]:   File "/envs//Megatron-LM/megatron/core/pipeline_parallel/schedules.py", line 1211, in forward_backward_pipelining_without_inte
rleaving                                                                                                                                          
[rank0]:     output_tensor = forward_step(                                                                                                        
[rank0]:   File "/envs//Megatron-LM/megatron/core/pipeline_parallel/schedules.py", line 192, in forward_step                             
[rank0]:     output_tensor, loss_func = forward_step_func(data_iterator, model)                                                                   
[rank0]:   File "/envs//Megatron-LM/pretrain_gpt.py", line 142, in forward_step                                                          
[rank0]:     tokens, labels, loss_mask, attention_mask, position_ids = get_batch(                                                                 
[rank0]:   File "/envs//Megatron-LM/pretrain_gpt.py", line 91, in get_batch                                                              
[rank0]:     batch = get_batch_on_this_tp_rank(data_iterator)                                                                                     
[rank0]:   File "/envs//Megatron-LM/megatron/utils.py", line 285, in get_batch_on_this_tp_rank                                           
[rank0]:     data = next(data_iterator)                                                                                                           
[rank0]:   File "/envs/megatron/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 631, in __next__             
[rank0]:     data = self._next_data()                                                                                                             
[rank0]:   File "/envs/megatron/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data          
[rank0]:     return self._process_data(data)                                                                                                      
[rank0]:   File "/envs/megatron/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data       
[rank0]:     data.reraise()                                                                                                                       
[rank0]:   File "/envs/megatron/lib/python3.10/site-packages/torch/_utils.py", line 705, in reraise                             
[rank0]:     raise exception                                                                                                                      
[rank0]: RuntimeError: Caught RuntimeError in DataLoader worker process 0.                                                                        
[rank0]: Original Traceback (most recent call last):                                                                                              
[rank0]:   File "/envs/megatron/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop      
[rank0]:     data = fetcher.fetch(index)  # type: ignore[possibly-undefined]                                                                      
[rank0]:   File "/envs/megatron/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch               
[rank0]:     return self.collate_fn(data)                                                                                                         
[rank0]:   File "/envs/megatron/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 277, in default_collate  
[rank0]:     return collate(batch, collate_fn_map=default_collate_fn_map)                                                                         
[rank0]:   File "/envs/megatron/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 129, in collate          
[rank0]:     return elem_type({key: collate([d[key] for d in batch], collate_fn_map=collate_fn_map) for key in elem})                             
[rank0]:   File "/envs/megatron/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 129, in <dictcomp>
[rank0]:     return elem_type({key: collate([d[key] for d in batch], collate_fn_map=collate_fn_map) for key in elem})           
[rank0]:   File "/envs/megatron/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 121, in collate
[rank0]:     return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)                                             
[rank0]:   File "/envs/megatron/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 173, in collate_tensor_fn
[rank0]:     out = elem.new(storage).resize_(len(batch), *list(elem.size()))       
[rank0]: RuntimeError: Trying to resize storage that is not resizable
```

**Comment by noob-ctrl** [comment]
@1049451037 I encountered the same error, have you found the reason?

**Comment by 1049451037** [comment]
Hi @noob-ctrl , it's not a bug. Just ensure that your seq_length of your data labels are right. Especially when you set `--context-parallel-size` > 1.
