### ISSUE TITLE
Can't find scaled_masked_softmax.cpp

### ISSUE THREAD

**Issue by Co1lin** [NVIDIA/Megatron-LM#80]
I want to run `bash examples/generate_text.sh`, but an error occurs:
```
Traceback (most recent call last):
  File "tools/generate_samples_gpt.py", line 116, in <module>
    main()
  File "tools/generate_samples_gpt.py", line 94, in main
    initialize_megatron(extra_args_provider=add_text_generate_args,
  File "/opt/conda/envs/as/lib/python3.8/site-packages/megatron_lm-1.1.5-py3.8.egg/megatron/initialize.py", line 48, in initialize_megatron
    set_global_variables(extra_args_provider=extra_args_provider,
  File "/opt/conda/envs/as/lib/python3.8/site-packages/megatron_lm-1.1.5-py3.8.egg/megatron/global_vars.py", line 82, in set_global_variables
    args = _parse_args(extra_args_provider=extra_args_provider,
  File "/opt/conda/envs/as/lib/python3.8/site-packages/megatron_lm-1.1.5-py3.8.egg/megatron/global_vars.py", line 97, in _parse_args
    _GLOBAL_ARGS = parse_args(extra_args_provider=extra_args_provider,
  File "/opt/conda/envs/as/lib/python3.8/site-packages/megatron_lm-1.1.5-py3.8.egg/megatron/arguments.py", line 190, in parse_args
    fused_kernels.load_scaled_masked_softmax_fusion_kernel()
  File "/opt/conda/envs/as/lib/python3.8/site-packages/megatron_lm-1.1.5-py3.8.egg/megatron/fused_kernels/__init__.py", line 88, in load_scaled_masked_softmax_fusion_kernel
    scaled_upper_triang_masked_softmax_cuda = cpp_extension.load(
  File "/opt/conda/envs/as/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1079, in load
    return _jit_compile(
  File "/opt/conda/envs/as/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1262, in _jit_compile
    version = JIT_EXTENSION_VERSIONER.bump_version_if_changed(
  File "/opt/conda/envs/as/lib/python3.8/site-packages/torch/utils/_cpp_extension_versioner.py", line 45, in bump_version_if_changed
    hash_value = hash_source_files(hash_value, source_files)
  File "/opt/conda/envs/as/lib/python3.8/site-packages/torch/utils/_cpp_extension_versioner.py", line 15, in hash_source_files
    with open(filename) as file:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/conda/envs/as/lib/python3.8/site-packages/megatron_lm-1.1.5-py3.8.egg/megatron/fused_kernels/scaled_masked_softmax.cpp'
```

It seems like that the program can't find scaled_masked_softmax.cpp. I have the directory `/opt/conda/envs/as/lib/python3.8/site-packages/megatron_lm-1.1.5-py3.8.egg/megatron/fused_kernels/`, but there are only `__init__.py  __pycache__  build`.

I am not sure that I've setup Megatron well. I have run `python setup install` in the cloned repo folder. When checking with `conda list`, it shows `megatron-lm               1.1.5                    pypi_0    pypi`.

**Comment by huangyf530** [comment]
I face the same problem and wonder how you solved this problem

**Comment by Co1lin** [comment]
> I face the same problem and wonder how you solved this problem

Just as what I said in the original issue, I have "installed" the Megatron by `python setup install`. However, it actually doesn't work in this way. I shouldn't have install it. The right way is to run Megatron directly without installing. So at last I `pip uninstall megatron-lm` and now it works well.

**Comment by huangyf530** [comment]
Thank you very much. It also works for me.
