### ISSUE TITLE
merge_file_ in MMapIndexedDatasetBuilder does not work because of _doc_idx 

### ISSUE THREAD

**Issue by bugface** [NVIDIA/Megatron-LM#81]
## task
try to merge two .bin files into one

##  code
```python
data_path_prefix = ["test1", "test2"]

class A:
    def __init__(self):
        self.tokenizer_type = 'BertWordPieceCase'
        self.rank = 0
        self.vocab_file = '/blue/yonghui.wu/alexgre/data/vocabs/bert/vocab.txt'
        self.merge_file = None
        self.make_vocab_size_divisible_by = 128
        self.tensor_model_parallel_size = 1

args = A()
tokenizer = build_tokenizer(args)

builders = indexed_dataset.make_builder(output_bin_files,  impl='mmap', vocab_size=30592)

for each in data_path_prefix:
    builders.merge_file_(each)

builders.finalize(output_idx_files)
```

##  issue
after merging, when ran training using the merged data, raise an error:
```
> building train, validation, and test datasets ...
 > datasets target sizes (minimum size):
    train:      1024000000
    validation: 107520
    test:       5120
> building train, validation, and test datasets for BERT ...
 > building dataset index ...
    reading sizes...
    reading pointers...
    reading document index...
    creating numpy buffer of mmap...
    creating memory view of numpy buffer...
Traceback (most recent call last):
  File "../Megatron-LM/pretrain_bert.py", line 154, in <module>
    pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
  File "/blue/yonghui.wu/alexgre/Megatron-LM/megatron/training.py", line 115, in pretrain
    = build_train_valid_test_data_iterators(
  File "/blue/yonghui.wu/alexgre/Megatron-LM/megatron/training.py", line 995, in build_train_valid_test_data_iterators
    train_ds, valid_ds, test_ds = build_train_valid_test_datasets_provider(
  File "../Megatron-LM/pretrain_bert.py", line 137, in train_valid_test_datasets_provider
    train_ds, valid_ds, test_ds = build_train_valid_test_datasets(
  File "/blue/yonghui.wu/alexgre/Megatron-LM/megatron/data/dataset_utils.py", line 398, in build_train_valid_test_datasets
    return _build_train_valid_test_datasets(data_prefix[0],
  File "/blue/yonghui.wu/alexgre/Megatron-LM/megatron/data/dataset_utils.py", line 453, in _build_train_valid_test_datasets
    indexed_dataset = get_indexed_dataset_(data_prefix,
  File "/blue/yonghui.wu/alexgre/Megatron-LM/megatron/data/dataset_utils.py", line 549, in get_indexed_dataset_
    assert indexed_dataset.sizes.shape[0] == indexed_dataset.doc_idx[-1]
AssertionError
```
## solution

I modify the ```merge_file_``` function of ```MMapIndexedDatasetBuilder``` class in ```indexed_dataset.py``` and now it workes
```python
class MMapIndexedDatasetBuilder(object):
    def __init__(self, out_file, dtype=np.int64):
        self._data_file = open(out_file, 'wb')
        self._dtype = dtype
        self._sizes = []
        self._doc_idx = [0]
        self._merge_idx = 0

    def add_item(self, tensor):
        np_array = np.array(tensor.numpy(), dtype=self._dtype)
        self._data_file.write(np_array.tobytes(order='C'))
        self._sizes.append(np_array.size)

    def end_document(self):
        self._doc_idx.append(len(self._sizes))

    def merge_file_(self, another_file):
        # Concatenate index
        index = MMapIndexedDataset.Index(index_file_path(another_file))
        assert index.dtype == self._dtype

        for s in index.sizes:
            self._sizes.append(s)
        
        if self._merge_idx == 0:
            self._doc_idx = []
            self._doc_idx.extend(index.doc_idx)
        else:
            start_pt = self._doc_idx[-1]
            for each in index.doc_idx:
                new_doc_idx = start_pt + each
                self._doc_idx.append(new_doc_idx)

        # Concatenate data
        with open(data_file_path(another_file), 'rb') as f:
            shutil.copyfileobj(f, self._data_file)

        self._merge_idx += 1

    def finalize(self, index_file):
        self._data_file.close()

        self._sizes = np.array(self._sizes)
        self._doc_idx = np.array(self._doc_idx)
        
        print(self._sizes.shape)
        print(self._doc_idx.shape)
        print(self._sizes.shape[0], self._doc_idx[-1])

        with MMapIndexedDataset.Index.writer(index_file, self._dtype) as index:
            index.write(self._sizes, self._doc_idx)
```
## follow up
do you want me to create a pull request on this?

**Comment by HeyDavid633** [comment]
But I had this error assert 

> indexed_dataset.sizes.shape[0] == indexed_dataset.doc_idx[-1] 

too
I tried in this way,then the training just went done in 1 second.According to the output,this train/valid/test set all is 0,seems that nothing had been done. Can you fix my problem?ball ball you ! Both Chinese never cheat Chinese!

**Comment by bugface** [comment]
> But I had this error assert
> 
> > indexed_dataset.sizes.shape[0] == indexed_dataset.doc_idx[-1]
> 
> too I tried in this way,then the training just went done in 1 second.According to the output,this train/valid/test set all is 0,seems that nothing had been done. Can you fix my problem?ball ball you ! Both Chinese never cheat Chinese!

The solution posted works for my case.  Without your code, data, and ENV, it is hard to say exactly why it does not work for you.  I am not a developer for Megatron-LM, you might want to contact the repo maintainer for a reliable solution.

**Comment by HeyDavid633** [comment]
OK ,thank you the same way.

**Comment by jaredcasper** [comment]
This was fixed with this commit: https://github.com/NVIDIA/Megatron-LM/commit/a2c5e6cd58728190e1183fd02fdabbbc57e35f0f
