### ISSUE TITLE
Fused kernel compilation could get stuck 

### ISSUE THREAD

**Issue by rhythmswing** [NVIDIA/Megatron-LM#82]
Hi, 

I've noticed that the program could get stuck at "using torch.float16 for parameters ...". I found that the problem was stuck at compilating fused_kernels and deleting megatron/fused_kernel/build seems to fix the problem. I'm not sure what causes this. 
I'm posting this in hope it could be helpful.

**Comment by huangjundashuaige** [comment]
same problem, stuck at here.
```
using world size: 1, data-parallel-size: 1, tensor-model-parallel size: 1, pipeline-model-parallel size: 1 
using torch.float16 for parameters ...
^CTraceback (most recent call last):
  File "pretrain_gpt.py", line 149, in <module>
    pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
  File "/home/superbencher/Megatron-LM/megatron/training.py", line 87, in pretrain
    initialize_megatron(extra_args_provider=extra_args_provider,
  File "/home/superbencher/Megatron-LM/megatron/initialize.py", line 49, in initialize_megatron
    set_global_variables(extra_args_provider=extra_args_provider,
  File "/home/superbencher/Megatron-LM/megatron/global_vars.py", line 82, in set_global_variables
    args = _parse_args(extra_args_provider=extra_args_provider,
  File "/home/superbencher/Megatron-LM/megatron/global_vars.py", line 97, in _parse_args
    _GLOBAL_ARGS = parse_args(extra_args_provider=extra_args_provider,
  File "/home/superbencher/Megatron-LM/megatron/arguments.py", line 188, in parse_args
    fused_kernels.load_scaled_upper_triang_masked_softmax_fusion_kernel()
  File "/home/superbencher/Megatron-LM/megatron/fused_kernels/__init__.py", line 60, in load_scaled_upper_triang_masked_softmax_fusion_kernel
    scaled_upper_triang_masked_softmax_cuda = cpp_extension.load(
  File "/home/superbencher/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1079, in load
    return _jit_compile(
  File "/home/superbencher/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1306, in _jit_compile
    baton.wait()
  File "/home/superbencher/.local/lib/python3.8/site-packages/torch/utils/file_baton.py", line 42, in wait
    time.sleep(self.wait_seconds)
KeyboardInterrupt
```

**Comment by huangjundashuaige** [comment]
skip it by setting        --no-scaled-masked-softmax-fusion.
do not how much it could affect end2end performance.

**Comment by bugface** [comment]
delete ```Megatron-LM/megatron/fused_kernels/build/``` and restart works for me.

**Comment by bottergpt** [comment]
Same issue.
Actually, I got it run by removing the `megatron/fused_kernels/build` as suggested by @bugface, 
but I am wondering if it is the right way to get it fixed?

**Comment by giacomocamposampiero** [comment]
Experiencing the same issue here, even if the observed behaviour was different on different nodes of the cluster (not sure if it was caused by different software stacks or different gpus).

Deleting `megatron/fused_kernels/build` did not work for me, and I only managed to solve the issue by completely dropping fused kernels as suggested by @huangjundashuaige. To update this solution, the arguments that do this in the current version are `--no-masked-softmax-fusion` and `--no-bias-dropout-fusion`.

**Comment by jon-barker** [comment]
Deleting `/megatron/fused_kernels/build` is recommended if you have upgraded CUDA versions or moved to different hardware.  Those changes will not automatically be detected causing a rebuild of the kernels, which may be required.

We will be addressing this issue soon by moving to using the same prebuilt kernels from Apex and not requiring this custom kernel build step. I'll close this issue when that happens.

**Comment by SefaZeng** [comment]
Got stuck when compiling the fused_kernels when training on multiple nodes. But it works well in a single node. Why?

**Comment by SefaZeng** [comment]
> Got stuck when compiling the fused_kernels when training on multiple nodes. But it works well in a single node. Why?

Here is the log:
```
2023-09-14T05:12:47.917781119Z > initialized tensor model parallel with size 2
2023-09-14T05:12:47.917798892Z > initialized pipeline model parallel with size 2
2023-09-14T05:12:47.917886152Z > setting random seeds to 1234 ...
2023-09-14T05:12:47.917964859Z > initializing model parallel cuda seeds on global rank 0, model parallel rank 0, and data parallel rank 0 with model parallel seed: 3952 and data parallel seed: 1234
2023-09-14T05:12:47.918048273Z > compiling dataset index builder ...
2023-09-14T05:12:47.929707432Z make: Entering directory '/mnt/nanjing3cephfs/pr-others-prctrans/xianfzeng/multilingual/tug/Megatron-DeepSpeed-master/megatron/data'
2023-09-14T05:12:48.033105604Z make: Nothing to be done for 'default'.
2023-09-14T05:12:48.03312589Z make: Leaving directory '/mnt/nanjing3cephfs/pr-others-prctrans/xianfzeng/multilingual/tug/Megatron-DeepSpeed-master/megatron/data'
2023-09-14T05:12:48.033296973Z >>> done with dataset index builder. Compilation time: 0.115 seconds
2023-09-14T05:12:48.033314792Z > compiling and loading fused kernels ...
2023-09-14T05:12:48.3861007Z Detected CUDA files, patching ldflags
2023-09-14T05:12:48.386118285Z Emitting ninja build file /mnt/nanjing3cephfs/pr-others-prctrans/xianfzeng/multilingual/tug/Megatron-DeepSpeed-master/megatron/fused_kernels/build/build.ninja...
2023-09-14T05:12:48.443587168Z Building extension module scaled_upper_triang_masked_softmax_cuda...
2023-09-14T05:12:48.443604099Z Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
2023-09-14T05:12:48.829732724Z ninja: no work to do.
2023-09-14T05:12:48.835825491Z Loading extension module scaled_upper_triang_masked_softmax_cuda...
2023-09-14T05:12:48.959498479Z Detected CUDA files, patching ldflags
2023-09-14T05:12:48.959508856Z Emitting ninja build file /mnt/nanjing3cephfs/pr-others-prctrans/xianfzeng/multilingual/tug/Megatron-DeepSpeed-master/megatron/fused_kernels/build/build.ninja...
2023-09-14T05:12:48.968742982Z Building extension module scaled_masked_softmax_cuda...
2023-09-14T05:12:48.968753853Z Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
2023-09-14T05:12:49.256345124Z ninja: no work to do.
2023-09-14T05:12:49.2625369Z Loading extension module scaled_masked_softmax_cuda...
2023-09-14T05:12:49.348289434Z Detected CUDA files, patching ldflags
2023-09-14T05:12:49.34830759Z Emitting ninja build file /mnt/nanjing3cephfs/pr-others-prctrans/xianfzeng/multilingual/tug/Megatron-DeepSpeed-master/megatron/fused_kernels/build/build.ninja...
2023-09-14T05:12:49.35629256Z Building extension module scaled_softmax_cuda...
2023-09-14T05:12:49.356313663Z Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
2023-09-14T05:12:49.789046242Z ninja: no work to do.
2023-09-14T05:12:49.817703279Z Loading extension module scaled_softmax_cuda...
```
Then it stucks.

**Comment by MachineGunLin** [comment]
> Got stuck when compiling the fused_kernels when training on multiple nodes. But it works well in a single node. Why?

Same here. Did you solved this problem?

**Comment by ZhenYangIACAS** [comment]
> Got stuck when compiling the fused_kernels when training on multiple nodes. But it works well in a single node. Why?
@SefaZeng  Same problem, have you fixed this problem?

**Comment by saforem2** [comment]
> > Got stuck when compiling the fused_kernels when training on multiple nodes. But it works well in a single node. Why?
> 
> Same here. Did you solved this problem?

+1 same issue here

**Comment by mfdj2002** [comment]
> Got stuck when compiling the fused_kernels when training on multiple nodes. But it works well in a single node. Why?

same here

**Comment by mfdj2002** [comment]
> Got stuck when compiling the fused_kernels when training on multiple nodes. But it works well in a single node. Why?

Actually, it seems to be a problem with pytorch barrier, and simply setting NCCL_P2P_DISABLE=1 worked for me. 
credit: https://discuss.pytorch.org/t/torch-distributed-barrier-doesnt-work-with-pytorch-2-0-and-backend-nccl/190232

**Comment by saforem2** [comment]
awesome to hear, will try this, thanks!

**Comment by kduxin** [comment]
> > Got stuck when compiling the fused_kernels when training on multiple nodes. But it works well in a single node. Why?
> 
> Actually, it seems to be a problem with pytorch barrier, and simply setting NCCL_P2P_DISABLE=1 worked for me. credit: https://discuss.pytorch.org/t/torch-distributed-barrier-doesnt-work-with-pytorch-2-0-and-backend-nccl/190232

I met this problem on one of my nodes.
Working on that node along (NNODE=1), it does not work. To solve, I applied NCCL_P2P_DISABLE=1 to that node. This seems a hardware-related / BIOS setting issue.
But distributed training by excluding that node worked for me.
