### ISSUE TITLE
bert_dataset.py - ValueError: Seed must be between 0 and 2**32 - 1

### ISSUE THREAD

**Issue by bugface** [NVIDIA/Megatron-LM#88]
Try to train a Megatron-Bert based on a 100GB text dataset.

The training was ok for the first 550k steps (minibatch=8; globalbatch=7808, distributed on 976 GPUs)

Then it raised a error:
```ValueError
: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/red/gatortron-phi/workspace/scripts/Megatron-LM/megatron/data/bert_dataset.py", line 77, in __getitem__
    np_rng = np.random.RandomState(seed=(self.seed + idx))
  File "mtrand.pyx", line 183, in numpy.random.mtrand.RandomState.__init__
return self._process_data(data)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
  File "_mt19937.pyx", line 166, in numpy.random._mt19937.MT19937._legacy_seeding
  File "_mt19937.pyx", line 180, in numpy.random._mt19937.MT19937._legacy_seeding
ValueError: Seed must be between 0 and 2**32 - 1
```

where I think the problem is located at line 77  ```np_rng = np.random.RandomState(seed=(self.seed + idx))```  where the idx is too big for int due to the large dataset.

**Comment by bugface** [comment]
a quick fix:

```
np_rng = np.random.RandomState(seed=(self.seed + idx)%2**31)
```
