### ISSUE TITLE
transformer_engine import error

### ISSUE THREAD

**Issue by yuvraj27khanna02** [NVIDIA/Megatron-LM#959]
Hello,
I am using this repo for the first time and am a beginner at MLOps so please excuse any oversight or trivial mistakes from my end.

I have the following python file called `temp.py` that contains the following code (this is to create a basic implementation of the )

```
from megatron.core.transformer.transformer_config import TransformerConfig
import torch.nn.functional as F
from megatron.core.models.gpt.gpt_model import GPTModel
import torch
from megatron.core import parallel_state
from megatron.core.models.gpt.gpt_layer_specs import get_gpt_layer_local_spec

def init_distribution(tensor_model_parallel_size = 1, pipeline_model_parallel_size = 1) -> None:
    
    parallel_state.initialize_model_parallel(tensor_model_parallel_size=tensor_model_parallel_size,
                                             pipeline_model_parallel_size=pipeline_model_parallel_size)

init_distribution()

small_config = TransformerConfig(
    num_layers=1,
    hidden_size=128,
    num_attention_heads=3,
    ffn_hidden_size=512,
    activation_func=F.relu,
    tensor_model_parallel_size=1,
    pipeline_model_parallel_size=1,
    pipeline_dtype=torch.float16
)

gpt_model = GPTModel(
    config=small_config,
    transformer_layer_spec=get_gpt_layer_local_spec(),
    vocab_size=100,
    max_sequence_length=64
)

print(gpt_model)
```

When I try to run this I get the following error:

```
python temp.py 
Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/yuvraj1/code/Megatron-LM/megatron/core/transformer/transformer_block.py", line 30, in <module>
    from megatron.core.transformer.custom_layers.transformer_engine import (
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/yuvraj1/code/Megatron-LM/megatron/core/transformer/custom_layers/transformer_engine.py", line 9, in <module>
    import transformer_engine as te
ModuleNotFoundError: No module named 'transformer_engine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/yuvraj1/code/Megatron-LM/uv_rough.py", line 3, in <module>
    from megatron.core.models.gpt.gpt_model import GPTModel
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/yuvraj1/code/Megatron-LM/megatron/core/models/gpt/__init__.py", line 2, in <module>
    from .gpt_model import GPTModel
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/yuvraj1/code/Megatron-LM/megatron/core/models/gpt/gpt_model.py", line 17, in <module>
    from megatron.core.transformer.transformer_block import TransformerBlock
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/yuvraj1/code/Megatron-LM/megatron/core/transformer/transformer_block.py", line 43, in <module>
    import apex
  File "/anaconda/envs/azureml_py38/lib/python3.9/site-packages/apex/__init__.py", line 13, in <module>
    from pyramid.session import UnencryptedCookieSessionFactoryConfig
ImportError: cannot import name 'UnencryptedCookieSessionFactoryConfig' from 'pyramid.session' (unknown location)
```

I have tried `pip install git+https://github.com/NVIDIA/TransformerEngine.git@stable` and 'docker run --gpus all -it --rm nvcr.io/nvidia/pytorch:23.10-py3' but it does not work.

I get the following error while trying to download
"""
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> transformer-engine

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
"""

I want to understand how to fix this and how to download the transformer-engine model.

**Comment by ZSL98** [comment]
Same problem. Don't know why

**Comment by wplf** [comment]
you can build TE from source, cuda 12.1 is ok for every version.

**Comment by sbhavani** [comment]
This should be resolved with current TE [installation instructions](https://github.com/NVIDIA/TransformerEngine?tab=readme-ov-file#installation). The TE installation process has been significantly improved since this issue was reported.

Please open a new issue if you're still facing installation problems.
